-- Auto-generated by pvs2lean/translator.py
-- PVS theory: complex_props
-- PVSLib library: complex
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: complex_props

Auto-generated stubs from PVSLib theory `complex_props`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.complex_props

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (Im : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} (Re : pvs_τ3 → pvs_τ4)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} {pvs_τ7 : Type*} (c_root : pvs_τ5 → pvs_τ6 → pvs_τ7)
variable {pvs_τ8 : Type*} {pvs_τ9 : Type*} (complex_ : pvs_τ8 → pvs_τ9 → Prop)
variable {pvs_τ10 : Type*} {pvs_τ11 : Type*} (conjugate : pvs_τ10 → pvs_τ11)
variable {pvs_τ12 : Type*} {pvs_τ13 : Type*} {pvs_τ14 : Type*} (cpow : pvs_τ12 → pvs_τ13 → pvs_τ14)
variable {pvs_τ15 : Type*} (real__p : pvs_τ15 → Prop)
variable {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} (root_of_unity : pvs_τ16 → pvs_τ17 → pvs_τ18)

-- pvs2lean: complex_props.add_eq_0
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x + y = complex_(0, 0) IFF x = -y
theorem add_eq_0 : x + y = complex_ 0 0 ↔ x = -y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.minus_eq_0
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x - y = complex_(0, 0) IFF x = y
theorem minus_eq_0 : x - y = complex_ 0 0 ↔ x = y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_mult_unity
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x * complex_(1, 0) = x
theorem complex_mult_unity : x * complex_ 1 0 = x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_mult_unity2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(1, 0) * x = x
theorem complex_mult_unity2 : complex_ 1 0 * x = x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_div_unity
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / complex_(1, 0) = x
theorem complex_div_unity : x / complex_ 1 0 = x := by
  -- === TCCs for complex_div_unity ===
  -- TCC: complex_div_unity_TCC1
  -- Statement: complex_(1, 0) /= complex_(0, 0)
  have complex_div_unity_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_add_unity
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x + complex_(0, 0) = x
theorem complex_add_unity : x + complex_ 0 0 = x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_minus_unity
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x - complex_(0, 0) = x
theorem complex_minus_unity : x - complex_ 0 0 = x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.real_complex_minus
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(-r, 0) = -complex_(r, 0)
theorem real_complex_minus : complex_ -r 0 = -complex_ r 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.real_times_real
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(r, 0) * complex_(r1, 0) = complex_(r * r1, 0)
theorem real_times_real : complex_ r 0 * complex_ r1 0 = complex_ (r * r1) 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_div_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / n0y = complex_(1, 0) IFF x = n0y
theorem complex_div_eq : x / n0y = complex_ 1 0 ↔ x = n0y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_div_eq2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / n0y = complex_(-1, 0) IFF x = -n0y
theorem complex_div_eq2 : x / n0y = complex_ -1 0 ↔ x = -n0y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.add_div1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (x / n0x) + (y / n0y) = (x * n0y + y * n0x) / (n0x * n0y)
theorem add_div1 : (x / n0x) + (y / n0y) = (x * n0y + y * n0x) / (n0x * n0y) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.add_div2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x + (y / n0y) = (x * n0y + y) / n0y
theorem add_div2 : x + (y / n0y) = (x * n0y + y) / n0y := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.minus_div1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (x / n0x) - (y / n0y) = (x * n0y - y * n0x) / (n0x * n0y)
theorem minus_div1 : (x / n0x) - (y / n0y) = (x * n0y - y * n0x) / (n0x * n0y) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.minus_div2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x - (y / n0y) = (x * n0y - y) / n0y
theorem minus_div2 : x - (y / n0y) = (x * n0y - y) / n0y := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.cross_mult
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (x / n0x = y / n0y) IFF (x * n0y = y * n0x)
theorem cross_mult : (x / n0x = y / n0y) ↔ (x * n0y = y * n0x) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.separate_div
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / (n0x * n0y) = (x / n0x) * (complex_(1, 0) / n0y)
theorem separate_div : x / (n0x * n0y) = (x / n0x) * (complex_ 1 0 / n0y) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.div_div_complex
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (x / n0x) / n0y = x / (n0x * n0y)
theorem div_div_complex : (x / n0x) / n0y = x / (n0x * n0y) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.real_complex
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: real_?(x) IMPLIES x = complex_(Re(x), 0)
theorem real_complex : real__p x → x = complex_ (Re x) 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.real_div_mult1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_((r / n0r) * r1, 0) = complex_(r * r1 / n0r, 0)
theorem real_div_mult1 : complex_ ((r / n0r) * r1) 0 = complex_ (r * r1 / n0r) 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.real_div_mult2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(r / n0r, 0) / n0x = complex_(r, 0) / (n0x * complex_(n0r, 0))
theorem real_div_mult2 : complex_ (r / n0r) 0 / n0x = complex_ r 0 / (n0x * complex_ n0r 0) := by
  -- === TCCs for real_div_mult2 ===
  -- TCC: real_div_mult2_TCC1
  -- Statement: FORALL (n0r: nzreal, n0x: nzcomplex):
  --   n0x * complex_(n0r, 0) /= complex_(0, 0)
  have real_div_mult2_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.real_frac_times_complex
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(r / n0r, 0) * x = complex_(r, 0) * x / complex_(n0r, 0)
theorem real_frac_times_complex : complex_ (r / n0r) 0 * x = complex_ r 0 * x / complex_ n0r 0 := by
  -- === TCCs for real_frac_times_complex ===
  -- TCC: real_frac_times_complex_TCC1
  -- Statement: FORALL (n0r: nzreal): complex_(n0r, 0) /= complex_(0, 0)
  have real_frac_times_complex_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.expr_div_complex
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / n0x = (x * n0y) / (n0x * n0y)
theorem expr_div_complex : x / n0x = (x * n0y) / (n0x * n0y) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.inv_div
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: complex_(1, 0) / (n0x / n0y) = n0y / n0x
theorem inv_div : complex_ 1 0 / (n0x / n0y) = n0y / n0x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.complex_cancel
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x / n0x = y / n0x IFF x = y
theorem complex_cancel : x / n0x = y / n0x ↔ x = y := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.complex_mult_cancel
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x * n0x = y * n0x IFF x = y
theorem complex_mult_cancel : x * n0x = y * n0x ↔ x = y := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.sq_abs_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x * conjugate(x) = complex_(Re(x) * Re(x) + Im(x) * Im(x), 0)
theorem sq_abs_def : x * conjugate x = complex_ (Re x * Re x + Im x * Im x) 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.cpow_inv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (n: nat):
--   cpow(complex_(1, 0) / n0x)(n) = complex_(1, 0) / cpow(n0x)(n)
theorem cpow_inv : ∀ (n : {i : ℝ // i ≥ 0}), cpow (complex_ 1 0 / n0x) (n) = complex_ 1 0 / cpow n0x(n) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.cpow_div
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: cpow(x / n0x)(n) = cpow(x)(n) / cpow(n0x)(n)
theorem cpow_div : cpow (x / n0x) (n) = cpow x(n) / cpow n0x(n) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: complex_props.c_root_inv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (n0x: nzcomplex):
--   EXISTS (m: nat | m <= n0):
--     complex_(1, 0) / c_root(n0x, n0) =
--      root_of_unity(n0)(m) * c_root(complex_(1, 0) / n0x, n0)
theorem c_root_inv : ∀ (n0x : {z : ℝ × ℝ // z ≠ complex_ 0 0}), ∃ (m : {m : {i : ℝ // i ≥ 0} // m ≤ n0}), complex_ 1 0 / c_root n0x n0 = root_of_unity n0(m) * c_root (complex_ 1 0 / n0x) n0 := by
  -- === TCCs for c_root_inv ===
  -- TCC: c_root_inv_TCC1
  -- Statement: FORALL (n0: posnat, n0x: nzcomplex, m: nat | m <= n0):
  --   c_root(n0x, n0) /= complex_(0, 0)
  have c_root_inv_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: complex_props.c_root_div
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x: complex, n0x: nzcomplex):
--   EXISTS (m: nat | m <= n0):
--     c_root(x, n0) / c_root(n0x, n0) =
--      root_of_unity(n0)(m) * c_root(x / n0x, n0)
theorem c_root_div : ∀ (x : ℝ × ℝ) (n0x : {z : ℝ × ℝ // z ≠ complex_ 0 0}), ∃ (m : {m : {i : ℝ // i ≥ 0} // m ≤ n0}), c_root x n0 / c_root n0x n0 = root_of_unity n0(m) * c_root (x / n0x) n0 := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.complex_props