-- Auto-generated by pvs2lean/translator.py
-- PVS theory: lcm
-- PVSLib library: ints
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: lcm

Auto-generated stubs from PVSLib theory `lcm`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.lcm

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (divides : pvs_τ1 → pvs_τ2 → Prop)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} (gcd : pvs_τ3 → pvs_τ4 → pvs_τ5)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (lcm : pvs_τ6 → pvs_τ7 → Prop)
variable {pvs_τ8 : Type*} {pvs_τ9 : Type*} (rel_prime : pvs_τ8 → pvs_τ9 → Prop)

-- pvs2lean: lcm.lcm_1
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(1, m) = m
theorem lcm_1 : lcm 1 m = m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_same
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(n, n) = n
theorem lcm_same : lcm n n = n := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_sym
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(n, m) = lcm(m, n)
theorem lcm_sym : lcm n m = lcm m n := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.divides_lcm
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: divides(n, lcm(n, m)) AND divides(m, lcm(n, m))
theorem divides_lcm : divides n (lcm n m) ∧ divides m (lcm n m) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_is_min
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: divides(n, d) AND divides(m, d) IMPLIES lcm(n, m) <= d
theorem lcm_is_min : divides n d ∧ divides m d → lcm n m ≤ d := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_times
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(d * n, d * m) = d * lcm(n, m)
theorem lcm_times : lcm (d * n) (d * m) = d * lcm n m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_rel_prime
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rel_prime(n, m) IMPLIES lcm(n, m) = n * m
theorem lcm_rel_prime : rel_prime n m → lcm n m = n * m := by
  -- === TCCs for lcm_rel_prime ===
  -- TCC: lcm_rel_prime_TCC1
  -- Statement: FORALL (m, n: posnat): n = 0 => m /= 0
  have lcm_rel_prime_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: lcm.lcm_gcd_rel
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(n, m) = n * m / gcd(n, m)
theorem lcm_gcd_rel : lcm n m = n * m / gcd n m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_absorption
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: lcm(n, gcd(n, m)) = n
theorem lcm_absorption : lcm n (gcd n m) = n := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.lcm_divides
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: divides(n, d) AND divides(m, d) IMPLIES divides(lcm(n, m), d)
theorem lcm_divides : divides n d ∧ divides m d → divides (lcm n m) d := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: lcm.rel_primes_lcm_div
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rel_prime(n, m) AND divides(n, d) AND divides(m, d) IMPLIES
--  divides(n * m, d)
theorem rel_primes_lcm_div : rel_prime n m ∧ divides n d ∧ divides m d → divides (n * m) d := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.lcm