-- Auto-generated by pvs2lean/translator.py
-- PVS theory: rem
-- PVSLib library: ints
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: rem

Auto-generated stubs from PVSLib theory `rem`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.rem

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (div : pvs_τ1 → pvs_τ2 → pvs_τ3)
variable {pvs_τ4 : Type*} (integer_pred : pvs_τ4 → Prop)

-- pvs2lean: rem.ml1
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: n - m * div(n, m) < m
theorem ml1 : n - m * div n m < m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.ml3
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: abs(i - m * div(i, m)) < m
theorem ml3 : |i - m * div i m| < m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: i - j * div(i, j)
axiom rem {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: rem.rem_neg
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(-i, j) = -rem(i, j)
theorem rem_neg : rem -i j = -rem i j := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_neg_d
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(i, -j) = rem(i, j)
theorem rem_neg_d : rem i -j = rem i j := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_even
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: integer_pred(i / j) IMPLIES rem(i, j) = 0
theorem rem_even : integer_pred (i / j) → rem i j = 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: rem.rem_eq_arg
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(j, j) = 0
theorem rem_eq_arg : rem j j = 0 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_zero
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(0, j) = 0
theorem rem_zero : rem 0 j = 0 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_lt
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: abs(i) < abs(j) IMPLIES rem(i, j) = i
theorem rem_lt : |i| < |j| → rem i j = i := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_it_is
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: a = b + m * c AND b < m IMPLIES b = rem(a, m)
theorem rem_it_is : a = b + m * c ∧ b < m → b = rem a m := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: rem.rem_eq_0
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(i, j) = 0 IMPLIES integer_pred(i / j)
theorem rem_eq_0 : rem i j = 0 → integer_pred (i / j) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: rem.rem_one
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: rem(1, j) = IF abs(j) = 1 THEN 0 ELSE 1 ENDIF
theorem rem_one : rem 1 j = if |j| = 1 then 0 else 1 := by
  sorry  -- phase2_high: type translated, proof pending

end

end NavierStokesClean.PVSLib.rem