import Mathlib
import Bochner
import HilleYosida
import Cslib
import CATEPTMain.External.Registry
import CATEPTMain.Integration.MaxwellCurveSpacePphi2Bridge
import CATEPTMain.Integration.EntropicProperTimeCoreBridge
import CATEPTMain.Integration.Pphi2CATEPTEPTBridge
import CATEPTMain.Integration.ComplexDimensionalModularBridge
import CATEPTMain.Integration.AlphaDivergencePathIntegralBridge
import CATEPTMain.Integration.AlphaPathIntegralIntegration
import CATEPTMain.Integration.ComplexEinsteinPathIntegralBridge
import CATEPTMain.Integration.YoshidaFreeFisherBridge
import CATEPTMain.Integration.QuantumFisherBridge
import CATEPTMain.Integration.InformationDimensionalFrameworkBridge
import CATEPTMain.Integration.Pphi2NCATEPTBridge
import CATEPTMain.Integration.LGTCATEPTBridge
import CATEPTMain.Integration.LatticeQCDWilsonBridge
import CATEPTMain.Integration.NSCATEPTCoreBridge
import CATEPTMain.Integration.NSCATEPTExtendedBridge
import CATEPTMain.Integration.AdSCFTBridge
import CATEPTMain.Integration.BohmianQMBridge
import CATEPTMain.Integration.QuantumInfoFisherBridge
import CATEPTMain.Integration.GravitasBridge
import CATEPTMain.Integration.BCJBridge
import CATEPTMain.Integration.TheoryPluginArchitecture
import CATEPTMain.Integration.UnifiedTheorySpine
import CATEPTMain.Integration.QuantumCATEPTBridge
import CATEPTMain.Integration.ElectroweakCATEPTBridge
import CATEPTMain.Integration.VMLCATEPTBridge
import CATEPTMain.Integration.TheoryPluginAdapterSupport
import CATEPTMain.Integration.TheoryPluginAdapter
import CATEPTMain.Integration.TheoryPluginStressTests
import CATEPTMain.Integration.TheoryPluginDimSlot
import CATEPTMain.Integration.TheoryPluginDimCore
import CATEPTMain.AFPBridge
import CATEPTMain.Gravitas

/-!
CATEPTMain root module for clean Lean 4.29 migration work.
-/

def integratedRepoCount : Nat := CATEPTMain.External.repos.length
