import CATEPTMain.Certification.RelativityGR
import CATEPTMain.Certification.RelativityGRHodgeDual
import CATEPTMain.Certification.RelativityGRHodgeTensor
import CATEPTMain.Certification.RelativityGRCovariantDivergence
import CATEPTMain.Certification.RelativityGRStressConservation
import CATEPTMain.Certification.RelativityGRCurvedMaxwell
import CATEPTMain.Certification.RelativityGRResiduals
import CATEPTMain.Certification.RelativityGREinsteinEquation
import CATEPTMain.Certification.RelativityGRADM
import CATEPTMain.Certification.RelativityGRVMLMaxwell
import CATEPTMain.Certification.RelativityGRMaxwellPphi2
import CATEPTMain.Certification.RelativityGRCurvedDirect
import CATEPTMain.Certification.UniversalCertificate
import CATEPTMain.Certification.RelativityGRUnsafeFixes

/-!
# GR Certification Surface Tests

These tests record the currently implemented GR theorem surface.
They include the full direct curved-GR certificate interface.
-/

set_option autoImplicit false

namespace CATEPTMain.Certification.Tests.GRSurface

open CATEPTMain.Certification.RelativityGR

-- Flat and tensor GR certificates
#check canonical_gr_flat
#check canonical_gr_tensor

-- Full tensor Hodge API, scoped
#check hodgeStarEM
#check hodgeStarEM_involutive
#check hodgeStarEM_involutive_for_minkowski_family
#check hodgeStarEM_double_components_fixedAntisymmetric4D
#check hodgeStarEM_involutive_of_fixedAntisymmetric4D
#check hodgeStarEM_fixedAntisymmetric4D_closure_profile
#check gravitasFaradayMinkowski_fixedAntisymmetric4D
#check gravitasFaraday_hodgeStarEM_involutive

-- Bivector/canonical Hodge closure
#check gravitasFaraday_hodgeStar_involutive
#check gravitasFaraday_double_hodge_bivector

-- Covariant divergence
#check covariantDivergenceStressEnergy
#check gravitasCanonicalStress_covariantDivergence_zero

-- Stress conservation currently certified for flat/constant canonical models
#check canonical_radiation_stress_conserved
#check canonical_radiation_stress_nonzero_and_conserved
#check flat_constant_stress_conserved_for_all_constant_T
#check gravitasCanonicalStress_conserved_constant_model
#check MaxwellEquationsHold
#check electrovacuumElectromagneticStressEnergy
#check maxwell_implies_stress_conservation_of_contract
#check maxwell_implies_stress_conservation_derived
#check maxwell_implies_stress_conservation_minkowski
#check canonical_maxwell_implies_stress_conservation_derived
#check canonicalNamedFaradayComponents
#check canonical_electrovacuum_stress_bridge_of_faraday_components
#check canonical_maxwell_implies_stress_conservation_of_faraday_components
#check canonicalMinkowskiFaradayStressFamily
#check canonical_minkowski_faraday_family_implies_stress_conservation

-- Curved Maxwell bridge surface
#check canonical_gr_curved_maxwell
#check gr_curved_maxwell_faraday_antisymm
#check gr_curved_maxwell_homogeneous_of_potential
#check gr_curved_maxwell_flat_wave_eq

-- Residual objects
#check EinsteinResidual
#check ADMResidual
#check canonical_einstein_residual
#check canonical_adm_residual

-- Typed Einstein equation
#check EinsteinEquationCertificate
#check mk_einstein_equation_certificate
#check mk_einstein_equation_certificate_holds
#check EinsteinEquationCertificateFor
#check mk_einstein_equation_certificate_for
#check mk_einstein_equation_certificate_for_holds
#check EinsteinEquationCertificateForSource
#check mk_einstein_equation_certificate_for_source
#check mk_einstein_equation_certificate_for_source_holds
#check canonical_electrovac_einstein_certificate
#check canonical_electrovac_einstein_equation_holds
#check canonical_electrovac_einstein_certificate_for
#check canonical_electrovac_einstein_equation_holds_for
#check canonical_electrovac_einstein_certificate_for_source
#check canonical_electrovac_einstein_equation_holds_for_source
#check canonical_electrovac_einstein_certificate_for_family
#check canonical_electrovac_einstein_equation_holds_for_family
#check canonical_electrovac_einstein_certificate_for_source_family
#check canonical_electrovac_einstein_equation_holds_for_source_family

-- Typed ADM
#check ADMConstraintCertificate
#check mk_adm_constraint_certificate
#check mk_adm_constraint_certificate_holds
#check ADMConstraintCertificateFor
#check mk_adm_constraint_certificate_for
#check mk_adm_constraint_certificate_for_holds
#check IsMinkowskiVacuumADM
#check canonical_vacuum_adm_certificate
#check canonical_vacuum_adm_hamiltonian_constraint_holds
#check canonical_vacuum_adm_momentum_constraint_holds
#check canonical_vacuum_adm_certificate_for
#check canonical_vacuum_adm_certificate_for_family
#check canonical_vacuum_adm_certificate_for_family_holds
#check minkowski_vacuum_adm_constraints_for_family

-- VML Maxwell equilibrium
#check VMLMaxwellEquilibriumCertificate
#check canonical_vml_maxwell_equilibrium
#check vml_maxwell_rigidity_wrapped
#check vml_maxwell_content_available_wrapped
#check vml_equilibrium_implies_E_zero
#check vml_equilibrium_implies_B_constant
#check vml_equilibrium_implies_global_maxwellian
#check vml_equilibrium_projection_bundle

-- Universal certificate field checks (production surface)
#check universalConsistencyCertificate.curvedMaxwell
#check universalConsistencyCertificate.vmlMaxwell
#check universal_curved_maxwell_bridge_certified
#check universal_vml_maxwell_equilibrium_certified

-- Maxwell-CurveSpace/pphi2 bridge
#check MaxwellPphi2Certificate
#check mk_maxwell_pphi2_certificate
#check mk_maxwell_pphi2_certificate_contract_holds
#check canonical_maxwell_pphi2_certificate
#check canonical_maxwell_pphi2_bridge_contract_available

-- Full direct curved-GR claim surface
#check CurvedGRDirectCertificate
#check mk_curved_gr_direct_certificate
#check mk_curved_gr_direct_certificate_of_fixedAntisymmetric4D
#check curved_gr_direct_full_claim
#check mk_curved_gr_direct_certificate_claim
#check mk_curved_gr_direct_certificate_of_fixedAntisymmetric4D_claim
#check canonical_curved_gr_direct_certificate_of_fixedAntisymmetric4D
#check canonical_curved_gr_direct_certificate_of_fixedAntisymmetric4D_claim
#check curved_gr_direct_to_adm_certificate_for
#check curved_gr_direct_to_adm_certificate_for_holds
#check curved_gr_direct_to_einstein_certificate_for_source
#check curved_gr_direct_to_einstein_certificate_for_source_holds
#check curved_gr_direct_to_einstein_certificate_for
#check curved_gr_direct_to_einstein_certificate_for_holds

-- Unsafe-claim closure certificate
#check canonical_gr_unsafe_claims_closed
#check gravitasEinstein_residual_exact
#check einstein_residual_zero_for_vacuum_family
#check gravitasCanonicalVacuumADM_hamiltonian_residual_exact
#check gravitasCanonicalVacuumADM_momentum_residual_exact

end CATEPTMain.Certification.Tests.GRSurface
