-- Auto-generated by pvs2lean/translator.py
-- PVS theory: csequence_length_comp
-- PVSLib library: co_structures
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: csequence_length_comp

Auto-generated stubs from PVSLib theory `csequence_length_comp`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.csequence_length_comp

noncomputable section

variable {pvs_τ1 : Type*} (empty_p : pvs_τ1 → Prop)
variable {pvs_τ2 : Type*} (is_finite : pvs_τ2 → Prop)
variable {pvs_τ3 : Type*} (length : pvs_τ3 → Prop)
variable {pvs_τ14 : Type*} {pvs_τ15 : Type*} (rest : pvs_τ14 → pvs_τ15)

-- pvs2lean: csequence_length_comp.length_lt
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_finite(cseq1) AND
--  (is_finite(cseq2) IMPLIES length(cseq1) < length(cseq2))
axiom length_lt {pvs_τ12 : Type*} {pvs_τ13 : Type*} : pvs_τ12 → pvs_τ13 → Prop

-- pvs2lean: csequence_length_comp.length_le
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_finite(cseq2) IMPLIES is_finite(cseq1) AND length(cseq1) <= length(cseq2)
axiom length_le {pvs_τ10 : Type*} {pvs_τ11 : Type*} : pvs_τ10 → pvs_τ11 → Prop

-- pvs2lean: csequence_length_comp.length_eq
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (NOT is_finite(cseq1) AND NOT is_finite(cseq2)) OR
--  (is_finite(cseq1) AND is_finite(cseq2) AND length(cseq1) = length(cseq2))
axiom length_eq {pvs_τ4 : Type*} {pvs_τ5 : Type*} : pvs_τ4 → pvs_τ5 → Prop

-- pvs2lean: csequence_length_comp.length_ge
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_finite(cseq1) IMPLIES is_finite(cseq2) AND length(cseq1) >= length(cseq2)
axiom length_ge {pvs_τ6 : Type*} {pvs_τ7 : Type*} : pvs_τ6 → pvs_τ7 → Prop

-- pvs2lean: csequence_length_comp.length_gt
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_finite(cseq2) AND
--  (is_finite(cseq1) IMPLIES length(cseq1) > length(cseq2))
axiom length_gt {pvs_τ8 : Type*} {pvs_τ9 : Type*} : pvs_τ8 → pvs_τ9 → Prop

-- pvs2lean: csequence_length_comp.length_lt_le
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2: length_lt(cseq1, cseq2) IMPLIES length_le(cseq1, cseq2)
theorem length_lt_le : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_lt cseq1 cseq2 → length_le cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_gt_ge
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2: length_gt(cseq1, cseq2) IMPLIES length_ge(cseq1, cseq2)
theorem length_gt_ge : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_gt cseq1 cseq2 → length_ge cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_eq_le
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2: length_eq(cseq1, cseq2) IMPLIES length_le(cseq1, cseq2)
theorem length_eq_le : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_eq cseq1 cseq2 → length_le cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_eq_ge
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2: length_eq(cseq1, cseq2) IMPLIES length_ge(cseq1, cseq2)
theorem length_eq_ge : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_eq cseq1 cseq2 → length_ge cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_lt_neq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2:
--   length_lt(cseq1, cseq2) IMPLIES NOT length_eq(cseq1, cseq2)
theorem length_lt_neq : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_lt cseq1 cseq2 → ¬ length_eq cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_gt_neq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2:
--   length_gt(cseq1, cseq2) IMPLIES NOT length_eq(cseq1, cseq2)
theorem length_gt_neq : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_gt cseq1 cseq2 → ¬ length_eq cseq1 cseq2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_eq_empty
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL cseq1, cseq2:
--   length_eq(cseq1, cseq2) IMPLIES (empty?(cseq1) IFF empty?(cseq2))
theorem length_eq_empty : ∀ (cseq1 : csequence T1) (cseq2 : csequence T2), length_eq cseq1 cseq2 → (empty_p cseq1 ↔ empty_p cseq2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: csequence_length_comp.length_eq_rest
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL nseq1, nseq2:
--   length_eq(nseq1, nseq2) IFF length_eq(rest(nseq1), rest(nseq2))
theorem length_eq_rest : ∀ (nseq1 : csequence T1) (nseq2 : csequence T2), length_eq nseq1 nseq2 ↔ length_eq (rest nseq1) (rest nseq2) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.csequence_length_comp