-- Auto-generated by pvs2lean/translator.py
-- PVS theory: minmax
-- PVSLib library: Bernstein
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: minmax

Auto-generated stubs from PVSLib theory `minmax`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.minmax

noncomputable section

variable {pvs_τ10 : Type*} (cons_p : pvs_τ10 → Prop)
variable {pvs_τ13 : Type*} (globalexit : pvs_τ13 → Prop)
variable {pvs_τ15 : Type*} (length : pvs_τ15 → Prop)
variable {pvs_τ16 : Type*} (localexit : pvs_τ16 → Prop)
variable {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} (max : pvs_τ18 → pvs_τ19 → pvs_τ20)
variable {pvs_τ21 : Type*} {pvs_τ22 : Type*} {pvs_τ23 : Type*} (min : pvs_τ21 → pvs_τ22 → pvs_τ23)
variable {pvs_τ24 : Type*} (null_p : pvs_τ24 → Prop)
variable {pvs_τ29 : Type*} {pvs_τ30 : Type*} {pvs_τ31 : Type*} (rel : pvs_τ29 → pvs_τ30 → pvs_τ31)
variable {pvs_τ40 : Type*} {pvs_τ41 : Type*} {pvs_τ42 : Type*} {pvs_τ43 : Type*} (setnth : pvs_τ40 → pvs_τ41 → pvs_τ42 → pvs_τ43)

-- pvs2lean: minmax.lb_le_ub?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: omm`lb_min <= omm`ub_max
noncomputable def lb_le_ub_p : sorry := by
  sorry  -- pvs2lean: definition stub for omm`lb_min <= omm`ub_max

-- pvs2lean: minmax.single_outminmax
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (# lb_min := a,
--    lb_max := b,
--    lb_var := l,
--    ub_max := a,
--    ub_min := b,
--    ub_var := l,
--    max_depth := depth,
--    splits := 0 #)
axiom single_outminmax {pvs_τ44 : Type*} {pvs_τ45 : Type*} {pvs_τ46 : Type*} {pvs_τ47 : Type*} {pvs_τ48 : Type*} : pvs_τ44 → pvs_τ45 → pvs_τ46 → pvs_τ47 → pvs_τ48

-- pvs2lean: minmax.empty_minmax
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: single_outminmax(0, 0, null, 0)
noncomputable def empty_minmax : sorry := by
  sorry  -- pvs2lean: definition stub for single_outminmax(0, 0, null, 0)

-- pvs2lean: minmax.outminmax_translate
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF j < length(omm`lb_var) AND j < length(omm`ub_var)
--   THEN omm
--          WITH [lb_var := setnth(omm`lb_var, j, rf),
--                ub_var := setnth(omm`ub_var, j, rf)]
-- ELSE omm
-- ENDIF
axiom outminmax_translate {pvs_τ25 : Type*} {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} : pvs_τ25 → pvs_τ26 → pvs_τ27 → pvs_τ28

-- pvs2lean: minmax.length_eq?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (cons?(omm`lb_var) OR cons?(omm`ub_var)) IMPLIES
--  length(omm`lb_var) = nvars AND length(omm`ub_var) = nvars
noncomputable def length_eq_p : sorry := by
  sorry  -- pvs2lean: definition stub for (cons?(omm`lb_var) OR cons?(omm`ub_var)) IMPLIES  length(omm`lb_var) = nvars AND

-- pvs2lean: minmax.combine
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET lbmax =
--       IF null?(omm1`lb_var) THEN omm2
--       ELSIF null?(omm2`lb_var) OR omm1`lb_max <= omm2`lb_max THEN omm1
--       ELSE omm2
--       ENDIF,
--     ubmin =
--       IF null?(omm1`ub_var) THEN omm2
-- 
axiom combine {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} : pvs_τ3 → pvs_τ4 → pvs_τ5

-- pvs2lean: minmax.combine_lr
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: combine(outminmax_translate(v, LAMBDA (x: real): x / 2)(omm1),
--         outminmax_translate(v, LAMBDA (x: real): (x + 1) / 2)(omm2))
--   WITH [splits := omm1`splits + omm2`splits + 1]
axiom combine_lr {pvs_τ6 : Type*} {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} : pvs_τ6 → pvs_τ7 → pvs_τ8 → pvs_τ9

-- pvs2lean: minmax.combine_l
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: combine(outminmax_translate(v, LAMBDA (x: real): x / 2)(omm1), omm2)
--   WITH [splits := omm1`splits + 1]
noncomputable def combine_l : sorry := by
  sorry  -- pvs2lean: definition stub for combine(outminmax_translate(v, LAMBDA (x: real): x / 2)(omm1), omm2)   WITH [spl

-- pvs2lean: minmax.combine_r
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: combine(outminmax_translate(v, LAMBDA (x: real): (x + 1) / 2)(omm1), omm2)
--   WITH [splits := omm1`splits + 1]
noncomputable def combine_r : sorry := by
  sorry  -- pvs2lean: definition stub for combine(outminmax_translate(v, LAMBDA (x: real): (x + 1) / 2)(omm1), omm2)   WIT

-- pvs2lean: minmax.between?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: cons?(omm1`lb_var) AND
--  cons?(omm1`ub_var) AND
--   omm1`lb_max <= omm2`lb_min AND omm2`ub_max <= omm1`ub_min
axiom between_p {pvs_τ1 : Type*} {pvs_τ2 : Type*} : pvs_τ1 → pvs_τ2 → Prop

-- pvs2lean: minmax.between_combine_lr
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: between?(omm, combine(omm1, omm2)) IFF
--  between?(omm, combine_lr(v, omm1, omm2))
theorem between_combine_lr : between_p omm (combine omm1 omm2) ↔ between_p omm (combine_lr v omm1 omm2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: minmax.pre_sound?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: length(omm`lb_var) = length(omm`ub_var) AND
--  omm`lb_min <= omm`ub_max AND
--   (cons?(omm`lb_var) IMPLIES
--     omm`lb_min <= omm`lb_max AND
--      omm`ub_min <= omm`ub_max AND omm`lb_max <= omm`ub_min)
noncomputable def pre_sound_p : sorry := by
  sorry  -- pvs2lean: definition stub for length(omm`lb_var) = length(omm`ub_var) AND  omm`lb_min <= omm`ub_max AND   (con

-- pvs2lean: minmax.eps_localexit
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: cons?(omm`lb_var) AND
--  cons?(omm`ub_var) AND
--   omm`lb_max - omm`lb_min <= e AND omm`ub_max - omm`ub_min <= e
axiom eps_localexit {pvs_τ11 : Type*} {pvs_τ12 : Type*} : pvs_τ11 → pvs_τ12

-- pvs2lean: minmax.false_globalexit
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FALSE
noncomputable def false_globalexit : sorry := by
  sorry  -- pvs2lean: definition stub for FALSE

-- pvs2lean: minmax.single_max_outminmax
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (# lb_min := b,
--    lb_max := d,
--    lb_var := l,
--    ub_max := a,
--    ub_min := d,
--    ub_var := l,
--    max_depth := depth,
--    splits := 0 #)
noncomputable def single_max_outminmax : sorry := by
  sorry  -- pvs2lean: definition stub for (# lb_min := b,    lb_max := d,    lb_var := l,    ub_max := a,    ub_min := d, 

-- pvs2lean: minmax.combine_max
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF omm1`lb_min >= omm2`ub_max THEN omm1
-- ELSIF omm2`lb_min >= omm1`ub_max THEN omm2
-- ELSE (# lb_min := min(omm1`lb_min, omm2`lb_min),
--         lb_max := 0,
--         lb_var := null,
--         ub_max := max(o
noncomputable def combine_max : sorry := by
  sorry  -- pvs2lean: definition stub for IF omm1`lb_min >= omm2`ub_max THEN omm1 ELSIF omm2`lb_min >= omm1`ub_max THEN om

-- pvs2lean: minmax.rel_localexit
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF rel(0, 1) THEN rel(omm`ub_max, 0) ELSE rel(omm`lb_min, 0) ENDIF
axiom rel_localexit {pvs_τ38 : Type*} {pvs_τ39 : Type*} : pvs_τ38 → pvs_τ39

-- pvs2lean: minmax.rel_counterex
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF rel(0, 1) THEN cons?(omm`ub_var) AND NOT rel(omm`ub_min, 0)
-- ELSE cons?(omm`lb_var) AND NOT rel(omm`lb_max, 0)
-- ENDIF
axiom rel_counterex {pvs_τ32 : Type*} {pvs_τ33 : Type*} : pvs_τ32 → pvs_τ33 → Prop

-- pvs2lean: minmax.rel_globalexit
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (exitatdepth AND omm`max_depth = depth) OR rel_counterex(rel)(omm)
axiom rel_globalexit {pvs_τ34 : Type*} {pvs_τ35 : Type*} {pvs_τ36 : Type*} {pvs_τ37 : Type*} : pvs_τ34 → pvs_τ35 → pvs_τ36 → pvs_τ37

-- pvs2lean: minmax.globalexit_inv?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (omm1, omm2):
--    globalexit(omm1) IMPLIES globalexit(combine(omm1, omm2)))
--  AND
--  (FORALL (n: nat, omm):
--     globalexit(omm) IMPLIES globalexit(omm WITH [splits := n]))
--   AND
--   (FORALL (j: nat,
axiom globalexit_inv_p {pvs_τ14 : Type*} : pvs_τ14 → Prop

-- pvs2lean: minmax.rel_globalexit_inv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: globalexit_inv?(rel_globalexit(rel, depth, FALSE))
theorem rel_globalexit_inv : globalexit_inv_p (rel_globalexit rel depth False) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: minmax.localexit_inv?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (omm1, omm2):
--    localexit(omm1) AND localexit(omm2) IMPLIES
--     localexit(combine(omm1, omm2)))
--  AND
--  (FORALL (n: nat, omm):
--     localexit(omm) IMPLIES localexit(omm WITH [splits := n]))
--   AN
axiom localexit_inv_p {pvs_τ17 : Type*} : pvs_τ17 → Prop

end

end NavierStokesClean.PVSLib.minmax