-- Auto-generated by pvs2lean/translator.py
-- PVS theory: util
-- PVSLib library: Bernstein
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: util

Auto-generated stubs from PVSLib theory `util`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.util

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (pvs_3 : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} (pvs_4 : pvs_τ3 → pvs_τ4)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} (pvs_5 : pvs_τ5 → pvs_τ6)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} (Avars : pvs_τ7 → pvs_τ8)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (Bvars : pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} (array2list : pvs_τ11 → pvs_τ12 → pvs_τ13)
variable {pvs_τ14 : Type*} {pvs_τ15 : Type*} (below : pvs_τ14 → pvs_τ15)
variable {pvs_τ16 : Type*} (boundedpts : pvs_τ16 → Prop)
variable {pvs_τ23 : Type*} {pvs_τ24 : Type*} (cdr : pvs_τ23 → pvs_τ24)
variable {pvs_τ25 : Type*} (coeffmono : pvs_τ25 → Prop)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} (coeffmono1 : pvs_τ26 → pvs_τ27)
variable {pvs_τ28 : Type*} {pvs_τ29 : Type*} (coeffmono2 : pvs_τ28 → pvs_τ29)
variable {pvs_τ30 : Type*} {pvs_τ31 : Type*} (cons : pvs_τ30 → pvs_τ31 → Prop)
variable {pvs_τ32 : Type*} (degmono : pvs_τ32 → Prop)
variable {pvs_τ33 : Type*} {pvs_τ34 : Type*} (degmono1 : pvs_τ33 → pvs_τ34)
variable {pvs_τ35 : Type*} {pvs_τ36 : Type*} (degmono2 : pvs_τ35 → pvs_τ36)
variable {pvs_τ43 : Type*} {pvs_τ44 : Type*} (fbnd : pvs_τ43 → pvs_τ44)
variable {pvs_τ45 : Type*} (intendpts : pvs_τ45 → Prop)
variable {pvs_τ51 : Type*} (length : pvs_τ51 → Prop)
variable {pvs_τ52 : Type*} {pvs_τ53 : Type*} (list2array : pvs_τ52 → pvs_τ53)
variable {pvs_τ57 : Type*} {pvs_τ58 : Type*} {pvs_τ59 : Type*} (max : pvs_τ57 → pvs_τ58 → pvs_τ59)
variable {pvs_τ60 : Type*} {pvs_τ61 : Type*} {pvs_τ62 : Type*} {pvs_τ63 : Type*} (mpoly : pvs_τ60 → pvs_τ61 → pvs_τ62 → pvs_τ63)
variable {pvs_τ75 : Type*} {pvs_τ76 : Type*} (relA : pvs_τ75 → pvs_τ76 → Prop)
variable {pvs_τ77 : Type*} {pvs_τ78 : Type*} (relB : pvs_τ77 → pvs_τ78 → Prop)
variable {pvs_τ79 : Type*} {pvs_τ80 : Type*} (relreal : pvs_τ79 → pvs_τ80 → Prop)
variable {pvs_τ81 : Type*} {pvs_τ82 : Type*} {pvs_τ83 : Type*} (subrange : pvs_τ81 → pvs_τ82 → pvs_τ83)
variable {pvs_τ91 : Type*} {pvs_τ92 : Type*} (upfrom : pvs_τ91 → pvs_τ92)
variable {pvs_τ93 : Type*} {pvs_τ94 : Type*} (upto : pvs_τ93 → pvs_τ94)

-- pvs2lean: util.zeroes
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: 0
noncomputable def zeroes : sorry := by
  sorry  -- pvs2lean: definition stub for 0

-- pvs2lean: util.ones
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: 1
noncomputable def ones : sorry := by
  sorry  -- pvs2lean: definition stub for 1

-- pvs2lean: util.closed_box?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (iup: below(nvars)): intendpts(iup)`1 AND intendpts(iup)`2
noncomputable def closed_box_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (iup: below(nvars)): intendpts(iup)`1 AND intendpts(iup)`2

-- pvs2lean: util.intendpts_true
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (TRUE, TRUE)
noncomputable def intendpts_true : sorry := by
  sorry  -- pvs2lean: definition stub for (TRUE, TRUE)

-- pvs2lean: util.boundedpts_true
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (TRUE, TRUE)
noncomputable def boundedpts_true : sorry := by
  sorry  -- pvs2lean: definition stub for (TRUE, TRUE)

-- pvs2lean: util.bounded_points_true?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i: below(nvars)): LET bpt = boundedpts(i) IN bpt`1 AND bpt`2
noncomputable def bounded_points_true_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (i: below(nvars)): LET bpt = boundedpts(i) IN bpt`1 AND bpt`2

-- pvs2lean: util.relreal_scal
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x, y: real, pr: posreal): relreal(x, y) IFF relreal(pr * x, pr * y)
theorem relreal_scal : ∀ (x : ℝ) (y : ℝ) (pr : {x : {x : ℝ // x ≥ 0} // x > 0}), relreal x y ↔ relreal (pr * x) (pr * y) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: util.corner_point?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)): coeffmono(j) = 0 OR coeffmono(j) = degmono(j)
noncomputable def corner_point_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (j: below(nvars)): coeffmono(j) = 0 OR coeffmono(j) = degmono(j)

-- pvs2lean: util.edge_point?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: v <= nvars AND
--  (ep IMPLIES
--    FORALL (i: subrange(v, nvars - 1)):
--      f(i) = 0 AND intendpts(i)`1 OR
--       degmono(i) /= 0 AND f(i) = degmono(i) AND intendpts(i)`2)
noncomputable def edge_point_p : sorry := by
  sorry  -- pvs2lean: definition stub for v <= nvars AND  (ep IMPLIES    FORALL (i: subrange(v, nvars - 1)):      f(i) = 0

-- pvs2lean: util.unitbox?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)): 0 <= X(j) AND X(j) <= 1
axiom unitbox_p {pvs_τ89 : Type*} {pvs_τ90 : Type*} : pvs_τ89 → pvs_τ90 → Prop

-- pvs2lean: util.bounded_points_exclusive?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (ii: below(nvars)): boundedpts(ii)`1 OR boundedpts(ii)`2
noncomputable def bounded_points_exclusive_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (ii: below(nvars)): boundedpts(ii)`1 OR boundedpts(ii)`2

-- pvs2lean: util.lt_below?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)): Avars(j) < Bvars(j)
axiom lt_below_p {pvs_τ54 : Type*} {pvs_τ55 : Type*} {pvs_τ56 : Type*} : pvs_τ54 → pvs_τ55 → pvs_τ56 → Prop

-- pvs2lean: util.le_below_mono?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)): degmono1(j) <= degmono2(j)
noncomputable def le_below_mono_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (j: below(nvars)): degmono1(j) <= degmono2(j)

-- pvs2lean: util.eq_below_mono?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)): coeffmono1(j) = coeffmono2(j)
noncomputable def eq_below_mono_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (j: below(nvars)): coeffmono1(j) = coeffmono2(j)

-- pvs2lean: util.interval_between?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET relA: [[real, real] -> bool] = IF intpt`1 THEN <= ELSE < ENDIF,
--     relB: [[real, real] -> bool] = IF intpt`2 THEN <= ELSE < ENDIF
--   IN
--   (bdpt`1 AND bdpt`2 IMPLIES A < B) AND
--    (bdpt`1 OR bdpt`2
axiom interval_between_p {pvs_τ46 : Type*} {pvs_τ47 : Type*} {pvs_τ48 : Type*} {pvs_τ49 : Type*} {pvs_τ50 : Type*} : pvs_τ46 → pvs_τ47 → pvs_τ48 → pvs_τ49 → pvs_τ50 → Prop

-- pvs2lean: util.boxbetween?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: below(nvars)):
--   interval_between?(Avars(j), Bvars(j), intendpts(j), boundedpts(j))(X(j))
axiom boxbetween_p {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} : pvs_τ17 → pvs_τ18 → pvs_τ19 → pvs_τ20 → pvs_τ21 → pvs_τ22 → Prop

-- pvs2lean: util.boxbetween_eq_bnd
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (fbnd: [nat -> [bool, bool]]):
--   (FORALL (n: below(nvars)): fbnd(n) = boundedpts(n)) IMPLIES
--    boxbetween?(nvars)(Avars, Bvars, intendpts, fbnd)(X) =
--     boxbetween?(nvars)(Avars, Bvars, inten
theorem boxbetween_eq_bnd : ∀ (fbnd : {i : ℝ // i ≥ 0} → Bool × Bool), (∀ (n : Finset.range nvars), fbnd n = boundedpts n) → boxbetween_p nvars(Avars, Bvars, intendpts, fbnd) (X) =
 boxbetween_p nvars(Avars, Bvars, intendpts, boundedpts) (X) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: util.interval_endpoints_inf_trans
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF (boundedpts(i)`1 AND boundedpts(i)`2) THEN intendpts(i)
-- ELSIF boundedpts(i)`1 THEN (FALSE, intendpts(i)`1)
-- ELSE (FALSE, intendpts(i)`2)
-- ENDIF
noncomputable def interval_endpoints_inf_trans : sorry := by
  sorry  -- pvs2lean: definition stub for IF (boundedpts(i)`1 AND boundedpts(i)`2) THEN intendpts(i) ELSIF boundedpts(i)`1

-- pvs2lean: util.denormalize_lambda
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LAMBDA (i: nat):
--   IF i < nvars
--     THEN IF (boundedpts(i)`1 AND boundedpts(i)`2)
--            THEN Avars(i) + X(i) * (Bvars(i) - Avars(i))
--          ELSIF boundedpts(i)`1 AND X(i) /= 0
--            THEN (
noncomputable def denormalize_lambda : sorry := by
  sorry  -- pvs2lean: definition stub for LAMBDA (i: nat):   IF i < nvars     THEN IF (boundedpts(i)`1 AND boundedpts(i)`2

-- pvs2lean: util.normalize_lambda
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: LAMBDA (i: nat):
--   LET (Avars, Bvars) = ABvars IN
--     IF i < nvars AND
--         (boundedpts(i)`1 IMPLIES X(i) /= Avars(i) - 1) AND
--          (boundedpts(i)`2 IMPLIES X(i) /= Bvars(i) + 1)
--       THEN IF 
axiom normalize_lambda {pvs_τ64 : Type*} {pvs_τ65 : Type*} {pvs_τ66 : Type*} {pvs_τ67 : Type*} {pvs_τ68 : Type*} {pvs_τ69 : Type*} : pvs_τ64 → pvs_τ65 → pvs_τ66 → pvs_τ67 → pvs_τ68 → pvs_τ69

-- pvs2lean: util.normalize_lambda_unitbox
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: boxbetween?(nvars)(Avars, Bvars, intendpts, boundedpts)(X) AND
--  lt_below?(nvars)(Avars, Bvars)
--  IMPLIES
--  unitbox?(nvars)(normalize_lambda(nvars, X, boundedpts)(Avars, Bvars))
theorem normalize_lambda_unitbox : boxbetween_p nvars(Avars, Bvars, intendpts, boundedpts) (X) ∧
 lt_below_p nvars(Avars, Bvars) → unitbox_p nvars(normalize_lambda nvars X boundedpts(Avars, Bvars)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: util.denormalize_listreal_rec
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: CASES l
--   OF null: null,
--      cons(a, r):
--        cons(LET n = nnvars - length(l) IN
--               IF n < nnvars
--                 THEN IF (boundedpts(n)`1 AND boundedpts(n)`2)
--                        THE
axiom denormalize_listreal_rec {pvs_τ37 : Type*} {pvs_τ38 : Type*} {pvs_τ39 : Type*} {pvs_τ40 : Type*} {pvs_τ41 : Type*} {pvs_τ42 : Type*} : pvs_τ37 → pvs_τ38 → pvs_τ39 → pvs_τ40 → pvs_τ41 → pvs_τ42

-- pvs2lean: util.denormalize_listreal
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: denormalize_listreal_rec(l, length(l), Avars, Bvars, boundedpts)
noncomputable def denormalize_listreal : sorry := by
  sorry  -- pvs2lean: definition stub for denormalize_listreal_rec(l, length(l), Avars, Bvars, boundedpts)

-- pvs2lean: util.polylist
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: array2list[list[list[real]]]
--     (terms)
--     (LAMBDA (t: nat):
--        array2list[list[real]]
--            (nvars)
--            (LAMBDA (v: nat): array2list[real](degmono(v) + 1)(mpoly(t)(v))))
axiom polylist {pvs_τ70 : Type*} {pvs_τ71 : Type*} {pvs_τ72 : Type*} {pvs_τ73 : Type*} {pvs_τ74 : Type*} : pvs_τ70 → pvs_τ71 → pvs_τ72 → pvs_τ73 → pvs_τ74

-- pvs2lean: util.translist
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: list2array[real]
--     (0)
--     (list2array[list[real]]
--          (null)(list2array[list[list[real]]](null)(mpl)(t))(v))
--     (d)
axiom translist {pvs_τ84 : Type*} {pvs_τ85 : Type*} {pvs_τ86 : Type*} {pvs_τ87 : Type*} {pvs_τ88 : Type*} : pvs_τ84 → pvs_τ85 → pvs_τ86 → pvs_τ87 → pvs_τ88

-- pvs2lean: util.translist_polylist_id
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (t: below(terms), v: below(nvars), i: upto(degmono(v))):
--   translist(polylist(mpoly, degmono, nvars, terms))(t)(v)(i) =
--    mpoly(t)(v)(i)
theorem translist_polylist_id : ∀ (t : {s : {i : ℝ // i ≥ 0} // s < terms}) (v : {s : {i : ℝ // i ≥ 0} // s < nvars}) (i : {s : {i : ℝ // i ≥ 0} // s ≤ degmono v}), translist (polylist mpoly degmono nvars terms) (t) (v) (i) = mpoly t(v) (i) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: util.corner_to_point
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: array2list(nvars)(LAMBDA (v: nat): IF f(v) = 0 THEN 0 ELSE 1 ENDIF)
noncomputable def corner_to_point : sorry := by
  sorry  -- pvs2lean: definition stub for array2list(nvars)(LAMBDA (v: nat): IF f(v) = 0 THEN 0 ELSE 1 ENDIF)

-- pvs2lean: util.mono_le?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (ii: below(nvars)): degmono1(ii) <= degmono2(ii)
noncomputable def mono_le_p : sorry := by
  sorry  -- pvs2lean: definition stub for FORALL (ii: below(nvars)): degmono1(ii) <= degmono2(ii)

-- pvs2lean: util.zero_poly_prod
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: 0
noncomputable def zero_poly_prod : sorry := by
  sorry  -- pvs2lean: definition stub for 0

-- pvs2lean: util.mono_max
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: max(degmono1(i), degmono2(i))
noncomputable def mono_max : sorry := by
  sorry  -- pvs2lean: definition stub for max(degmono1(i), degmono2(i))

-- pvs2lean: util.mono_sum
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: degmono1(i) + degmono2(i)
noncomputable def mono_sum : sorry := by
  sorry  -- pvs2lean: definition stub for degmono1(i) + degmono2(i)

end

end NavierStokesClean.PVSLib.util