-- Auto-generated by pvs2lean/translator.py
-- PVS theory: hutch
-- PVSLib library: Tarski
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: hutch

Auto-generated stubs from PVSLib theory `hutch`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.hutch

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (pvs_4 : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} (pvs_5 : pvs_τ3 → pvs_τ4)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} (pvs_6 : pvs_τ5 → pvs_τ6)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} (pvs_7 : pvs_τ7 → pvs_τ8)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (pvs_8 : pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} (BoolExpr : pvs_τ11 → pvs_τ12)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} {pvs_τ15 : Type*} (Eq_computed_remainder_p : pvs_τ13 → pvs_τ14 → pvs_τ15 → Prop)
variable {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} (Knuth_poly_root_strict_bound : pvs_τ20 → pvs_τ21 → pvs_τ22)
variable {pvs_τ28 : Type*} {pvs_τ29 : Type*} (PolyTerms : pvs_τ28 → pvs_τ29)
variable {pvs_τ30 : Type*} {pvs_τ31 : Type*} (RelF6 : pvs_τ30 → pvs_τ31)
variable {pvs_τ47 : Type*} {pvs_τ48 : Type*} (ai : pvs_τ47 → pvs_τ48)
variable {pvs_τ49 : Type*} {pvs_τ50 : Type*} (array2list : pvs_τ49 → pvs_τ50)
variable {pvs_τ51 : Type*} (be : pvs_τ51 → Prop)
variable {pvs_τ52 : Type*} {pvs_τ53 : Type*} (below : pvs_τ52 → pvs_τ53)
variable {pvs_τ125 : Type*} (integer_pred : pvs_τ125 → Prop)
variable {pvs_τ126 : Type*} (known_signs : pvs_τ126 → Prop)
variable {pvs_τ127 : Type*} {pvs_τ128 : Type*} (length : pvs_τ127 → pvs_τ128)
variable {pvs_τ129 : Type*} {pvs_τ130 : Type*} {pvs_τ131 : Type*} (max : pvs_τ129 → pvs_τ130 → pvs_τ131)
variable {pvs_τ132 : Type*} {pvs_τ133 : Type*} (min : pvs_τ132 → pvs_τ133)
variable {pvs_τ134 : Type*} {pvs_τ135 : Type*} {pvs_τ136 : Type*} (nth : pvs_τ134 → pvs_τ135 → pvs_τ136)
variable {pvs_τ137 : Type*} {pvs_τ138 : Type*} {pvs_τ139 : Type*} {pvs_τ140 : Type*} {pvs_τ141 : Type*} (number_roots_interval : pvs_τ137 → pvs_τ138 → pvs_τ139 → pvs_τ140 → pvs_τ141)
variable {pvs_τ142 : Type*} {pvs_τ143 : Type*} (otherarray : pvs_τ142 → pvs_τ143)
variable {pvs_τ144 : Type*} {pvs_τ145 : Type*} {pvs_τ146 : Type*} (pi : pvs_τ144 → pvs_τ145 → pvs_τ146)
variable {pvs_τ147 : Type*} (poly : pvs_τ147 → Prop)
variable {pvs_τ148 : Type*} {pvs_τ149 : Type*} (poly_deriv : pvs_τ148 → pvs_τ149 → Prop)
variable {pvs_τ153 : Type*} {pvs_τ154 : Type*} {pvs_τ155 : Type*} (polynomial : pvs_τ153 → pvs_τ154 → pvs_τ155 → Prop)
variable {pvs_τ156 : Type*} {pvs_τ157 : Type*} {pvs_τ158 : Type*} {pvs_τ159 : Type*} {pvs_τ160 : Type*} (polynomial_prod : pvs_τ156 → pvs_τ157 → pvs_τ158 → pvs_τ159 → pvs_τ160)
variable {pvs_τ161 : Type*} {pvs_τ162 : Type*} {pvs_τ163 : Type*} (pq : pvs_τ161 → pvs_τ162 → pvs_τ163)
variable {pvs_τ164 : Type*} {pvs_τ165 : Type*} {pvs_τ166 : Type*} {pvs_τ167 : Type*} (prod_polynomials : pvs_τ164 → pvs_τ165 → pvs_τ166 → pvs_τ167 → Prop)
variable {pvs_τ168 : Type*} {pvs_τ169 : Type*} {pvs_τ170 : Type*} {pvs_τ171 : Type*} (prod_polynomials_list : pvs_τ168 → pvs_τ169 → pvs_τ170 → pvs_τ171 → Prop)
variable {pvs_τ172 : Type*} (psq : pvs_τ172 → Prop)
variable {pvs_τ173 : Type*} (psq1 : pvs_τ173 → Prop)
variable {pvs_τ174 : Type*} {pvs_τ175 : Type*} {pvs_τ176 : Type*} (rat_poly_to_int : pvs_τ174 → pvs_τ175 → pvs_τ176)
variable {pvs_τ177 : Type*} (rational_pred : pvs_τ177 → Prop)
variable {pvs_τ178 : Type*} (realpred : pvs_τ178 → Prop)
variable {pvs_τ179 : Type*} {pvs_τ180 : Type*} {pvs_τ181 : Type*} {pvs_τ182 : Type*} (rel5 : pvs_τ179 → pvs_τ180 → pvs_τ181 → pvs_τ182)
variable {pvs_τ183 : Type*} {pvs_τ184 : Type*} {pvs_τ185 : Type*} {pvs_τ186 : Type*} (remainder_seq : pvs_τ183 → pvs_τ184 → pvs_τ185 → pvs_τ186 → Prop)
variable {pvs_τ192 : Type*} {pvs_τ193 : Type*} (sign_ext : pvs_τ192 → pvs_τ193)
variable {pvs_τ208 : Type*} (spoly : pvs_τ208 → Prop)
variable {pvs_τ209 : Type*} {pvs_τ210 : Type*} (sq : pvs_τ209 → pvs_τ210)
variable {pvs_τ211 : Type*} {pvs_τ212 : Type*} {pvs_τ213 : Type*} (subrange : pvs_τ211 → pvs_τ212 → pvs_τ213)
variable {pvs_τ219 : Type*} {pvs_τ220 : Type*} (thissq : pvs_τ219 → pvs_τ220)
variable {pvs_τ221 : Type*} {pvs_τ222 : Type*} (totalarray : pvs_τ221 → pvs_τ222)
variable {pvs_τ223 : Type*} {pvs_τ224 : Type*} (upto : pvs_τ223 → pvs_τ224)

-- pvs2lean: hutch.SystemSat?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: EXISTS (x: real):
--   realpred(x) AND
--    be(LAMBDA (i: upto(NumTerms)):
--         rel5(RelF6(i))(polynomial(p(PolyTerms(i)), n(PolyTerms(i)))(x), 0))
axiom SystemSat_p {pvs_τ39 : Type*} {pvs_τ40 : Type*} {pvs_τ41 : Type*} {pvs_τ42 : Type*} {pvs_τ43 : Type*} {pvs_τ44 : Type*} {pvs_τ45 : Type*} {pvs_τ46 : Type*} : pvs_τ39 → pvs_τ40 → pvs_τ41 → pvs_τ42 → pvs_τ43 → pvs_τ44 → pvs_τ45 → pvs_τ46 → Prop

-- pvs2lean: hutch.Eq_computed_remainder_seq?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: slseq =
--  array2list[list[list[int]]]
--      (k + 1)
--      (LAMBDA (j: nat):
--         IF j <= k
--           THEN remainder_seq(LAMBDA (i: nat):
--                                IF i <= n(j) THEN p(j)(i) ELSE 0
axiom Eq_computed_remainder_seq_p {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} : pvs_τ16 → pvs_τ17 → pvs_τ18 → pvs_τ19 → Prop

-- pvs2lean: hutch.sturm_chain_list
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: array2list[list[list[int]]]
--     (k + 1)
--     (LAMBDA (j: nat):
--        IF j <= k
--          THEN remainder_seq(LAMBDA (i: nat):
--                               IF i <= n(j) THEN p(j)(i) ELSE 0 ENDIF,
--       
noncomputable def sturm_chain_list : sorry := by
  sorry  -- pvs2lean: definition stub for array2list[list[list[int]]]     (k + 1)     (LAMBDA (j: nat):        IF j <= k  

-- pvs2lean: hutch.roots_in_int
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET I: RealInt =
--       (# lb := low,
--          ub := high,
--          bounded_below := TRUE,
--          bounded_above := TRUE,
--          closed_below := TRUE,
--          closed_above := TRUE #)
--   IN number_ro
axiom roots_in_int {pvs_τ187 : Type*} {pvs_τ188 : Type*} {pvs_τ189 : Type*} {pvs_τ190 : Type*} {pvs_τ191 : Type*} : pvs_τ187 → pvs_τ188 → pvs_τ189 → pvs_τ190 → pvs_τ191 → Prop

-- pvs2lean: hutch.sound_signs?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i: upto(k)):
--   (known_signs(i) = 0 IFF
--     EXISTS (x: real):
--       low <= x AND x <= high AND polynomial(p(i), n(i))(x) = 0)
--    AND
--    (known_signs(i) < 0 IFF
--      FORALL (x: real):
--        low
axiom sound_signs_p {pvs_τ202 : Type*} {pvs_τ203 : Type*} {pvs_τ204 : Type*} {pvs_τ205 : Type*} {pvs_τ206 : Type*} {pvs_τ207 : Type*} : pvs_τ202 → pvs_τ203 → pvs_τ204 → pvs_τ205 → pvs_τ206 → pvs_τ207 → Prop

-- pvs2lean: hutch.decidable_interval
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (i: upto(k)):
--    known_signs(i) = 0 IMPLIES
--     roots_in_int(p(i), n(i), low, high, nth(slseq, i)) = 1)
--  AND
--  ((EXISTS (i: upto(k)): known_signs(i) = 0) IMPLIES
--    roots_in_int(psq, nsq, low, 
axiom decidable_interval {pvs_τ54 : Type*} {pvs_τ55 : Type*} {pvs_τ56 : Type*} {pvs_τ57 : Type*} {pvs_τ58 : Type*} {pvs_τ59 : Type*} {pvs_τ60 : Type*} {pvs_τ61 : Type*} {pvs_τ62 : Type*} {pvs_τ63 : Type*} : pvs_τ54 → pvs_τ55 → pvs_τ56 → pvs_τ57 → pvs_τ58 → pvs_τ59 → pvs_τ60 → pvs_τ61 → pvs_τ62 → pvs_τ63 → Prop

-- pvs2lean: hutch.sum_square_zero_havers
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET nz = (known_signs(i) /= 0),
--     thissq =
--       (IF nz THEN (LAMBDA (d: nat): 0)
--        ELSE polynomial_prod(p(i), n(i), p(i), n(i))
--        ENDIF),
--     thisdeg = (IF nz THEN 0 ELSE 2 * n(i) ENDIF),
axiom sum_square_zero_havers {pvs_τ214 : Type*} {pvs_τ215 : Type*} {pvs_τ216 : Type*} {pvs_τ217 : Type*} {pvs_τ218 : Type*} : pvs_τ214 → pvs_τ215 → pvs_τ216 → pvs_τ217 → pvs_τ218 → Prop

-- pvs2lean: hutch.sum_square_zero_havers_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (k, p,
--         (n: [nat -> nat]
--              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0),
--         (i: nat)):
--   i <= k IMPLIES
--    LET sszh = sum_square_zero_havers(k, p, n, known_signs,
theorem sum_square_zero_havers_def : ∀ (k : {i : ℝ // i ≥ 0}) (p : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}) (i : {i : ℝ // i ≥ 0}), i ≤ k → (let sszh := sum_square_zero_havers k p n known_signs i; let poly := list2array 0(sszh.sqlist); ((∃ (z : {k : ℕ // k ≤ i}), known_signs z = 0) →
    (sszh.sqdeg > 0 ∧
      sszh.sqdeg = List.length sszh.sqlist - 1 ∧ poly sszh.sqdeg > 0))
   ∧
   ((¬ ∃ (z : {k : ℕ // k ≤ i}), known_signs z = 0) →
     (sszh.sqdeg = 0 ∧
       sszh.sqlist = cons 0 null[int] ∧
        (poly = (fun (jj : ℕ)=> 0))))
    ∧
    ∀ (x : ℝ), polynomial poly sszh.sqdeg(x) =
       Finset.sum (Finset.Icc 0 i) (fun (j : ℕ)=> if j > i ∨ known_signs j ≠ 0 then 0
               else (polynomial (p j^2) (n j) (x))
               )) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.decidable_interval_sq
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (i: upto(k)):
--    known_signs(i) = 0 IMPLIES
--     roots_in_int(p(i), n(i), low, high, nth(slseq, i)) = 1)
--  AND
--  ((EXISTS (i: upto(k)): known_signs(i) = 0) IMPLIES
--    (LET sszh = sum_square_zero_
axiom decidable_interval_sq {pvs_τ64 : Type*} {pvs_τ65 : Type*} {pvs_τ66 : Type*} {pvs_τ67 : Type*} {pvs_τ68 : Type*} {pvs_τ69 : Type*} {pvs_τ70 : Type*} : pvs_τ64 → pvs_τ65 → pvs_τ66 → pvs_τ67 → pvs_τ68 → pvs_τ69 → pvs_τ70 → Prop

-- pvs2lean: hutch.decidable_interval_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (sumsquares: bool,
--         n: [nat -> nat]
--             | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0):
--   sound_signs?(k, p, n, low, high)(known_signs) IMPLIES
--    LET psql = prod_polynomia
theorem decidable_interval_def : ∀ (sumsquares : Bool) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}), sound_signs_p k p n low high(known_signs) → (let psql := prod_polynomials_list p n (fun i=>  1) k; let nsq := List.length psql - 1; let psq := list2array 0(psql); ∀ ((slseq: (Eq_computed_remainder_seq_p (k : list[list[int]]
               | (¬ sumsquares) →
                  Eq_computed_remainder_p psq nsq(sqsl))) (p : list[list[int]]
               | (¬ sumsquares) →
                  Eq_computed_remainder_p psq nsq(sqsl))) (n))) : list[list[int]]
               | (¬ sumsquares) →
                  Eq_computed_remainder_p psq nsq(sqsl))) ((sqsl : list[list[int]]
               | (¬ sumsquares) →
                  Eq_computed_remainder_p psq nsq(sqsl))), (((¬ sumsquares) ∧
       decidable_interval k p n psq nsq low high known_signs slseq sqsl)
      ∨
      (sumsquares ∧
        decidable_interval_sq k p n low high known_signs slseq))
     →
     ((∀ (i : _) (j : {k : ℕ // k ≤ k}) (zz : _) (ww : ℝ), (low ≤ zz) ∧ (zz ≤ high) ∧ (low ≤ ww) ∧ (ww ≤ high)
          ∧ (polynomial (p i) (n i) (zz) = 0)
          ∧ (polynomial (p j) (n j) (ww) = 0)
          → zz = ww)
       ∧
       (∀ (x : ℝ), low ≤ x ∧ x ≤ high →
           ((∀ (i : {k : ℕ // k ≤ k}), sign_ext (polynomial (p i) (n i) (x)) =
                sign_ext (polynomial (p i) (n i) (low)))
             ∨
             (∀ (i : {k : ℕ // k ≤ k}), sign_ext (polynomial (p i) (n i) (x)) =
                 sign_ext (polynomial (p i) (n i) (high)))
              ∨
              (∀ (i : {k : ℕ // k ≤ k}), sign_ext (polynomial (p i) (n i) (x)) =
                  sign_ext (known_signs i)))))) := by
  -- === TCCs for decidable_interval_def ===
  -- TCC: decidable_interval_def_TCC1
  -- Statement: FORALL (high: real, k: nat, known_signs: [nat -> int], low: real,
  --         p: [nat -> [nat -> int]], sumsquares: bool,
  --         n: [nat -> nat]
  --             | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND ...
  have decidable_interval_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: decidable_interval_def_TCC2
  -- Statement: FORALL (high: real, k: nat, known_signs: [nat -> int], low: real,
  --         p: [nat -> [nat -> int]], sumsquares: bool,
  --         n: [nat -> nat]
  --             | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND ...
  have decidable_interval_def_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.decide_interval
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: ((NOT unsatl?) AND
--   be(LAMBDA (i: upto(NumTerms)):
--        rel5(RelF6(i))
--            (polynomial(p(PolyTerms(i)), n(PolyTerms(i)))(low), 0)))
--  OR
--  be(LAMBDA (i: upto(NumTerms)):
--       rel5(RelF6(i))
--  
axiom decide_interval {pvs_τ71 : Type*} {pvs_τ72 : Type*} {pvs_τ73 : Type*} {pvs_τ74 : Type*} {pvs_τ75 : Type*} {pvs_τ76 : Type*} {pvs_τ77 : Type*} {pvs_τ78 : Type*} {pvs_τ79 : Type*} {pvs_τ80 : Type*} {pvs_τ81 : Type*} {pvs_τ82 : Type*} : pvs_τ71 → pvs_τ72 → pvs_τ73 → pvs_τ74 → pvs_τ75 → pvs_τ76 → pvs_τ77 → pvs_τ78 → pvs_τ79 → pvs_τ80 → pvs_τ81 → pvs_τ82 → Prop

-- pvs2lean: hutch.decide_interval_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (sumsquares: bool, NumTerms: nat, k: nat, be: BoolExpr(NumTerms),
--         RelF6: [nat -> subrange(0, 5)],
--         PolyTerms: [upto(NumTerms) -> upto(k)], p,
--         (n: [nat -> nat]
--            
theorem decide_interval_def : ∀ (sumsquares : Bool) (NumTerms : {i : ℝ // i ≥ 0}) (k : {i : ℝ // i ≥ 0}) (be : ({s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → Bool) → Bool) (RelF6 : {i : ℝ // i ≥ 0} → {k : ℝ // 0 ≤ k ∧ k ≤ 5}) (PolyTerms : {s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → {s : {i : ℝ // i ≥ 0} // s ≤ k}) (p : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}) (low : ℝ) (high : ℝ) (known_signs : {i : ℝ // i ≥ 0} → ℝ), fun (psql : {ll : List ℝ // List.length ll - 1 = Finset.sum (Finset.Icc 0 k) (n * fun i=>  1) ∧
 prod_polynomials p n (fun i=>  1) k =
  fun (i : ℕ)=> if i < List.length ll then nth ll i else 0}) => ∀ (slseq : {x : List (List (List ℝ)) // every (fun (x : list (List ℝ))=> every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧
                         real_pred x ∧
                          rational_pred x ∧ integer_pred x)
                     (x))
             (x))
     (x)}) (sqsl : {sqsl : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧
                 real_pred x ∧ rational_pred x ∧ integer_pred x)
             (x))
     (x)} // (¬ sumsquares) →
 (let nsq := List.length psql - 1; let psq := list2array 0(psql); Eq_computed_remainder_p psq nsq(sqsl))}), (((¬ sumsquares) ∧
   (let nsq := List.length psql - 1; let psq := list2array 0(psql); decidable_interval k p n psq nsq low high known_signs slseq sqsl)
  ∨
  (sumsquares ∧
    decidable_interval_sq k p n low high known_signs slseq))
 ∧
 low ≤ high ∧
  (unsatl_p →
    (¬ be (fun (i : {k : ℕ // k ≤ NumTerms})=> rel5 (RelF6 i)
                  (polynomial (p (PolyTerms i)) (n (PolyTerms i)) (low), 0))))) → (decide_interval NumTerms k be RelF6 PolyTerms p n low high known_signs unsatl_p slseq
  ↔
  SystemSat_p NumTerms k be RelF6 PolyTerms p n (fun (qz : ℝ)=> low ≤ qz ∧ qz ≤ high)) (prod_polynomials_list p n (fun i=>  1) k) := by
  -- === TCCs for decide_interval_def ===
  -- TCC: decide_interval_def_TCC1
  -- Statement: FORALL (sumsquares: bool, NumTerms: nat, k: nat,
  --         RelF6: [nat -> subrange(0, 5)], p: [nat -> [nat -> int]],
  --         (n: [nat -> nat]
  --              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n...
  have decide_interval_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: decide_interval_def_TCC2
  -- Statement: FORALL (sumsquares: bool, NumTerms: nat, k: nat,
  --         RelF6: [nat -> subrange(0, 5)], p: [nat -> [nat -> int]],
  --         (n: [nat -> nat]
  --              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n...
  have decide_interval_def_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.decidable_intervals_exist
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (k, p,
--         (n: [nat -> nat]
--              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0),
--         (slseq: (Eq_computed_remainder_seq?(k, p, n)))):
--   EXISTS (eps: posreal):
--     FORALL (
theorem decidable_intervals_exist : ∀ (k : {i : ℝ // i ≥ 0}) (p : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}) (slseq : {x : List (List (List ℝ)) // every (fun (x : list (List ℝ))=> every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧
                         real_pred x ∧
                          rational_pred x ∧ integer_pred x)
                     (x))
             (x))
     (x)}), ∃ (eps : {x : {x : ℝ // x ≥ 0} // x > 0}), ∀ (low : ℝ) (high : ℝ), low < high ∧ high - low ≤ eps → (let psql := prod_polynomials_list p n (fun i=>  1) k; let nsq := List.length psql - 1; let psq := list2array 0(psql); ∀ (known_signs : (sound_signs_p k p n low high),
          (sqsl: (Eq_computed_remainder_p psq nsq))), decidable_interval k p n psq nsq low high known_signs slseq sqsl) := by
  -- === TCCs for decidable_intervals_exist ===
  -- TCC: decidable_intervals_exist_TCC1
  -- Statement: FORALL (k: nat, p: [nat -> [nat -> int]],
  --         (n: [nat -> nat]
  --              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0),
  --         (slseq: (Eq_computed_remainder_seq?(k, p, n))), eps: po...
  have decidable_intervals_exist_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.decidable_intervals_sq_exist
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (k, p,
--         (n: [nat -> nat]
--              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0),
--         (slseq: (Eq_computed_remainder_seq?(k, p, n)))):
--   EXISTS (eps: posreal):
--     FORALL (
theorem decidable_intervals_sq_exist : ∀ (k : {i : ℝ // i ≥ 0}) (p : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}) (slseq : {x : List (List (List ℝ)) // every (fun (x : list (List ℝ))=> every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧
                         real_pred x ∧
                          rational_pred x ∧ integer_pred x)
                     (x))
             (x))
     (x)}), ∃ (eps : {x : {x : ℝ // x ≥ 0} // x > 0}), ∀ (low : ℝ) (high : ℝ), low < high ∧ high - low ≤ eps → ∀ (known_signs : (sound_signs_p k p n low high)), decidable_interval_sq k p n low high known_signs slseq := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.hutch_int_meas
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET psql =
--       IF sumsquares THEN null[int]
--       ELSE prod_polynomials_list(p, n, LAMBDA i: 1, k)
--       ENDIF,
--     nsq = length(psql) - 1,
--     psq = list2array[int](0)(psql),
--     Aset =
--       (LAMB
axiom hutch_int_meas {pvs_τ115 : Type*} {pvs_τ116 : Type*} {pvs_τ117 : Type*} {pvs_τ118 : Type*} {pvs_τ119 : Type*} {pvs_τ120 : Type*} {pvs_τ121 : Type*} {pvs_τ122 : Type*} {pvs_τ123 : Type*} {pvs_τ124 : Type*} : pvs_τ115 → pvs_τ116 → pvs_τ117 → pvs_τ118 → pvs_τ119 → pvs_τ120 → pvs_τ121 → pvs_τ122 → pvs_τ123 → pvs_τ124 → Prop

-- pvs2lean: hutch.signs_upd
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET ksl =
--       array2list[int]
--           (k + 1)
--           (LAMBDA (i: nat):
--              IF i > k THEN 0
--              ELSIF known_signs(i) /= 0 THEN known_signs(i)
--              ELSIF roots_in_int(p(
axiom signs_upd {pvs_τ194 : Type*} {pvs_τ195 : Type*} {pvs_τ196 : Type*} {pvs_τ197 : Type*} {pvs_τ198 : Type*} {pvs_τ199 : Type*} {pvs_τ200 : Type*} {pvs_τ201 : Type*} : pvs_τ194 → pvs_τ195 → pvs_τ196 → pvs_τ197 → pvs_τ198 → pvs_τ199 → pvs_τ200 → pvs_τ201

-- pvs2lean: hutch.signs_upd_sound
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL ((n: [nat -> nat]
--              | FORALL (j: upto(k)): p(j)(n(j)) /= 0 AND n(j) > 0),
--         slseq: (Eq_computed_remainder_seq?(k, p, n))):
--   sound_signs?(k, p, n, low, high)(known_signs) IMPLI
theorem signs_upd_sound : ∀ (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}) (slseq : {x : List (List (List ℝ)) // every (fun (x : list (List ℝ))=> every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧
                         real_pred x ∧
                          rational_pred x ∧ integer_pred x)
                     (x))
             (x))
     (x)}), sound_signs_p k p n low high(known_signs) → ∀ (low1 : _) (high1 : ℝ), low ≤ low1 ∧ low1 < high1 ∧ high1 ≤ high →
   sound_signs_p k p n low1 high1
               (signs_upd k p n low1 high1 known_signs slseq) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.hutch_int_basic
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF ((NOT sumsquares) AND
--      decidable_interval(k, p, n, psq, nsq, low, high, known_signs, slseq,
--                         sqsl))
--     OR
--     (sumsquares AND
--       decidable_interval_sq(k, p, n, low, h
axiom hutch_int_basic {pvs_τ99 : Type*} {pvs_τ100 : Type*} {pvs_τ101 : Type*} {pvs_τ102 : Type*} {pvs_τ103 : Type*} {pvs_τ104 : Type*} {pvs_τ105 : Type*} {pvs_τ106 : Type*} {pvs_τ107 : Type*} {pvs_τ108 : Type*} {pvs_τ109 : Type*} {pvs_τ110 : Type*} {pvs_τ111 : Type*} {pvs_τ112 : Type*} {pvs_τ113 : Type*} {pvs_τ114 : Type*} : pvs_τ99 → pvs_τ100 → pvs_τ101 → pvs_τ102 → pvs_τ103 → pvs_τ104 → pvs_τ105 → pvs_τ106 → pvs_τ107 → pvs_τ108 → pvs_τ109 → pvs_τ110 → pvs_τ111 → pvs_τ112 → pvs_τ113 → pvs_τ114 → Prop

-- pvs2lean: hutch.Knuth_total
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i > k THEN Knuth_total(k, p, n, k)
-- ELSIF i = 0 THEN Knuth_poly_root_strict_bound(p(0), n(0))
-- ELSE max(Knuth_poly_root_strict_bound(p(i), n(i)),
--          Knuth_total(k, p, n, i - 1))
-- ENDIF
axiom Knuth_total {pvs_τ23 : Type*} {pvs_τ24 : Type*} {pvs_τ25 : Type*} {pvs_τ26 : Type*} {pvs_τ27 : Type*} : pvs_τ23 → pvs_τ24 → pvs_τ25 → pvs_τ26 → pvs_τ27

-- pvs2lean: hutch.hutch_int
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET ppl =
--       IF sumsquares THEN null[int]
--       ELSE prod_polynomials_list(p, n, LAMBDA i: 1, k)
--       ENDIF,
--     psq = list2array[int](0)(ppl),
--     nsq = IF sumsquares THEN 1 ELSE length(ppl) - 1 
axiom hutch_int {pvs_τ91 : Type*} {pvs_τ92 : Type*} {pvs_τ93 : Type*} {pvs_τ94 : Type*} {pvs_τ95 : Type*} {pvs_τ96 : Type*} {pvs_τ97 : Type*} {pvs_τ98 : Type*} : pvs_τ91 → pvs_τ92 → pvs_τ93 → pvs_τ94 → pvs_τ95 → pvs_τ96 → pvs_τ97 → pvs_τ98 → Prop

-- pvs2lean: hutch.hutch_int_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (sumsquares: bool, NumTerms: nat, k: nat, be: BoolExpr(NumTerms),
--         RelF6: [nat -> subrange(0, 5)],
--         PolyTerms: [upto(NumTerms) -> upto(k)], p,
--         (n: [nat -> nat]
--            
theorem hutch_int_def : ∀ (sumsquares : Bool) (NumTerms : {i : ℝ // i ≥ 0}) (k : {i : ℝ // i ≥ 0}) (be : ({s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → Bool) → Bool) (RelF6 : {i : ℝ // i ≥ 0} → {k : ℝ // 0 ≤ k ∧ k ≤ 5}) (PolyTerms : {s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → {s : {i : ℝ // i ≥ 0} // s ≤ k}) (p : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), p j(n j) ≠ 0 ∧ n j > 0}), hutch_int sumsquares NumTerms k be RelF6 PolyTerms p n ↔ SystemSat_p NumTerms k be RelF6 PolyTerms p n (fun (qz : ℝ)=> True) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.poly_system_list
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom poly_system_list {pvs_τ150 : Type*} {pvs_τ151 : Type*} {pvs_τ152 : Type*} : pvs_τ150 → pvs_τ151 → pvs_τ152 → Prop

-- pvs2lean: hutch.hutch
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET pi = (LAMBDA (j): rat_poly_to_int(pq(j), n(j))),
--     pl = poly_system_list(k, pi, n),
--     p =
--       (LAMBDA (i):
--          LAMBDA (j):
--            IF i <= k AND j <= n(i) THEN nth[int](nth[list[int]
axiom hutch {pvs_τ83 : Type*} {pvs_τ84 : Type*} {pvs_τ85 : Type*} {pvs_τ86 : Type*} {pvs_τ87 : Type*} {pvs_τ88 : Type*} {pvs_τ89 : Type*} {pvs_τ90 : Type*} : pvs_τ83 → pvs_τ84 → pvs_τ85 → pvs_τ86 → pvs_τ87 → pvs_τ88 → pvs_τ89 → pvs_τ90 → Prop

-- pvs2lean: hutch.SystemSatRat?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: EXISTS (x: real):
--   be(LAMBDA (i: upto(NumTerms)):
--        rel5(RelF6(i))(polynomial(pq(PolyTerms(i)), n(PolyTerms(i)))(x), 0))
axiom SystemSatRat_p {pvs_τ32 : Type*} {pvs_τ33 : Type*} {pvs_τ34 : Type*} {pvs_τ35 : Type*} {pvs_τ36 : Type*} {pvs_τ37 : Type*} {pvs_τ38 : Type*} : pvs_τ32 → pvs_τ33 → pvs_τ34 → pvs_τ35 → pvs_τ36 → pvs_τ37 → pvs_τ38 → Prop

-- pvs2lean: hutch.hutch_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (sumsquares: bool, NumTerms: nat, k: nat, be: BoolExpr(NumTerms),
--         RelF6: [nat -> subrange(0, 5)],
--         PolyTerms: [upto(NumTerms) -> upto(k)], pq,
--         (n: [nat -> nat]
--           
theorem hutch_def : ∀ (sumsquares : Bool) (NumTerms : {i : ℝ // i ≥ 0}) (k : {i : ℝ // i ≥ 0}) (be : ({s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → Bool) → Bool) (RelF6 : {i : ℝ // i ≥ 0} → {k : ℝ // 0 ≤ k ∧ k ≤ 5}) (PolyTerms : {s : {i : ℝ // i ≥ 0} // s ≤ NumTerms} → {s : {i : ℝ // i ≥ 0} // s ≤ k}) (pq : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} → ℝ) (n : {n : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} // ∀ (j : {k : ℕ // k ≤ k}), pq j(n j) ≠ 0 ∧ n j > 0}), hutch sumsquares NumTerms k be RelF6 PolyTerms pq n ↔ SystemSatRat_p NumTerms k be RelF6 PolyTerms pq n := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: hutch.test
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET N = 10, ddeg = 10 IN
--   FORALL (x: real):
--     x > 0 AND x ^ ddeg < N IMPLIES
--      EXISTS (k: nat): k <= N AND (x ^ ddeg - k) * (x ^ ddeg - (k + 1)) <= 0
theorem test : fun (N : ℝ) => fun (ddeg : ℝ) => ∀ (x : ℝ), x > 0 ∧ x ^ ddeg < N → ∃ (k : ℕ), k ≤ N ∧ (x ^ ddeg - k) * (x ^ ddeg - (k + 1)) ≤ 0 10 10 := by
  -- === TCCs for test ===
  -- TCC: test_TCC1
  -- Statement: FORALL (N: real, ddeg: real):
  --   N = 10 AND ddeg = 10 IMPLIES
  --    FORALL (x: real):
  --      x > 0 IMPLIES
  --       rational_pred(ddeg) AND integer_pred(ddeg) AND (x /= 0 OR ddeg >= 0)
  have test_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_high: type translated, proof pending

end

end NavierStokesClean.PVSLib.hutch