-- Auto-generated by pvs2lean/translator.py
-- PVS theory: power_series_conv
-- PVSLib library: series
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: power_series_conv

Auto-generated stubs from PVSLib theory `power_series_conv`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.power_series_conv

noncomputable section

variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (conv_series_p : pvs_τ6 → pvs_τ7 → Prop)
variable {pvs_τ8 : Type*} (convergent_p : pvs_τ8 → Prop)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (factorial : pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} (inf_sum : pvs_τ11 → pvs_τ12 → pvs_τ13)
variable {pvs_τ14 : Type*} {pvs_τ15 : Type*} (limit : pvs_τ14 → pvs_τ15)
variable {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} (powerseq : pvs_τ16 → pvs_τ17 → pvs_τ18)
variable {pvs_τ19 : Type*} {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} (powerseries : pvs_τ19 → pvs_τ20 → pvs_τ21 → pvs_τ22)
variable {pvs_τ23 : Type*} {pvs_τ24 : Type*} (series : pvs_τ23 → pvs_τ24)

-- pvs2lean: power_series_conv.T_pred
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
axiom T_pred {pvs_τ3 : Type*} : pvs_τ3 → Prop

-- pvs2lean: power_series_conv.not_one_element
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: not_one_element?[T]
theorem not_one_element : not_one_element_p := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.deriv_domain
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: deriv_domain?[T]
theorem deriv_domain : deriv_domain_p := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.open
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x: T):
--   EXISTS (delta: posreal):
--     FORALL (y: real): abs(x - y) < delta IMPLIES T_pred(y)
theorem pvs_open : ∀ (x : ℝ), ∃ (delta : {x : {x : ℝ // x ≥ 0} // x > 0}), ∀ (y : ℝ), |x - y| < delta → T_pred y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.conv_powerseries?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: convergent?(powerseries(a)(x)))
axiom conv_powerseries_p {pvs_τ4 : Type*} {pvs_τ5 : Type*} : pvs_τ4 → pvs_τ5 → Prop

-- pvs2lean: power_series_conv.Inf_sum
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: limit(powerseries(a)(x))
axiom Inf_sum {pvs_τ1 : Type*} {pvs_τ2 : Type*} : pvs_τ1 → pvs_τ2 → Prop

-- pvs2lean: power_series_conv.end_powerseries_conv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: conv_powerseries?(a) IFF conv_powerseries?(a, m)
theorem end_powerseries_conv : conv_powerseries_p a ↔ conv_powerseries_p a m := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.Inf_inf
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: conv_powerseries?(a) IMPLIES
--  Inf_sum(a) = (LAMBDA x: inf_sum(powerseq(a, x)))
theorem Inf_inf : conv_powerseries_p a → Inf_sum a = (fun x=>  inf_sum (powerseq a x)) := by
  -- === TCCs for Inf_inf ===
  -- TCC: Inf_inf_TCC1
  -- Statement: FORALL (a: sequence[real]):
  --   conv_powerseries?(a) IMPLIES FORALL (x: T): conv_series?(powerseq(a, x))
  have inf_inf_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.Inf_inf_m
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: conv_powerseries?(a, m) IMPLIES
--  Inf_sum(m, a) = (LAMBDA x: inf_sum(m, powerseq(a, x)))
theorem Inf_inf_m : conv_powerseries_p a m → Inf_sum m a = (fun x=>  inf_sum m (powerseq a x)) := by
  -- === TCCs for Inf_inf_m ===
  -- TCC: Inf_inf_m_TCC1
  -- Statement: FORALL (a: sequence[real], m: nat):
  --   conv_powerseries?(a, m) IMPLIES
  --    FORALL (x: T): conv_series?(powerseq(a, x), m)
  have inf_inf_m_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.powerseries_abs_conv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (x: T): convergent?(powerseries(a)(x))) IMPLIES
--  (FORALL (x: T): convergent?(series(abs(powerseq(a, x)))))
theorem powerseries_abs_conv : (∀ (x : T), convergent_p (powerseries a(x))) → (∀ (x : T), convergent_p (series (|powerseq a x|))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.simple
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA n: x ^ n / factorial(n))
axiom simple {pvs_τ25 : Type*} {pvs_τ26 : Type*} : pvs_τ25 → pvs_τ26

-- pvs2lean: power_series_conv.simple_0_conv
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: T_pred(0) IMPLIES convergent?(series(simple(0)))
theorem simple_0_conv : T_pred 0 → convergent_p (series (simple 0)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.simple_conv
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(series(simple(x)))
theorem simple_conv : convergent_p (series (simple x)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series_conv.m1_conv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: abs(x) < 1 IMPLIES convergent?(powerseries((LAMBDA (n: nat): (-1) ^ n))(x))
theorem m1_conv : |x| < 1 → convergent_p (powerseries ((fun (n : ℕ)=> (-1) ^ n)) (x)) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.power_series_conv