-- Auto-generated by pvs2lean/translator.py
-- PVS theory: power_series
-- PVSLib library: series
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: power_series

Auto-generated stubs from PVSLib theory `power_series`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.power_series

noncomputable section

variable {pvs_τ5 : Type*} (bounded_p : pvs_τ5 → Prop)
variable {pvs_τ6 : Type*} (conv_series_p : pvs_τ6 → Prop)
variable {pvs_τ7 : Type*} (convergent_p : pvs_τ7 → Prop)
variable {pvs_τ9 : Type*} (inf_sum : pvs_τ9 → Prop)
variable {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} (series : pvs_τ17 → pvs_τ18 → pvs_τ19)

-- pvs2lean: power_series.hat_02n
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: 0 ^ pn = 0
theorem hat_02n : 0 ^ pn = 0 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: power_series.powerseq
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA (k: nat): a(k) * x ^ k)
axiom powerseq {pvs_τ12 : Type*} {pvs_τ13 : Type*} : pvs_τ12 → pvs_τ13 → Prop

-- pvs2lean: power_series.powerseries
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: series(powerseq(a, x))
axiom powerseries {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} : pvs_τ14 → pvs_τ15 → pvs_τ16

-- pvs2lean: power_series.absolutely_convergent_series?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(series(abs(a)))
axiom absolutely_convergent_series_p {pvs_τ1 : Type*} : pvs_τ1 → Prop

-- pvs2lean: power_series.divergent_series?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: NOT convergent?(series(a))
axiom divergent_series_p {pvs_τ8 : Type*} : pvs_τ8 → Prop

-- pvs2lean: power_series.powerseries_bounded
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(powerseries(a)(x)) IMPLIES bounded?(powerseq(a, x))
theorem powerseries_bounded : convergent_p (powerseries a(x)) → bounded_p (powerseq a x) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.powerseries_conv_neg
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: conv_series?(powerseq(a, x)) AND powerseq(a, -x) = -powerseq(a, x) IMPLIES
--  conv_series?(powerseq(a, -x))
theorem powerseries_conv_neg : conv_series_p (powerseq a x) ∧ powerseq a -x = -powerseq a x → conv_series_p (powerseq a -x) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.inf_sum_neg
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: powerseq(a, -x) = -powerseq(a, x) AND conv_series?(powerseq(a, x)) IMPLIES
--  inf_sum(powerseq(a, -x)) = -inf_sum(powerseq(a, x))
theorem inf_sum_neg : powerseq a -x = -powerseq a x ∧ conv_series_p (powerseq a x) → inf_sum (powerseq a -x) = -inf_sum (powerseq a x) := by
  -- === TCCs for inf_sum_neg ===
  -- TCC: inf_sum_neg_TCC1
  -- Statement: FORALL (a: sequence[real], x: real):
  --   conv_series?(powerseq(a, x)) AND powerseq(a, -x) = -powerseq(a, x)
  --    IMPLIES conv_series?(powerseq(a, -x))
  have inf_sum_neg_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.powerseries_conv_point
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(powerseries(a)(x1)) AND abs(x) < abs(x1) IMPLIES
--  absolutely_convergent_series?(powerseq(a, x))
theorem powerseries_conv_point : convergent_p (powerseries a(x1)) ∧ |x| < |x1| → absolutely_convergent_series_p (powerseq a x) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.powerseries_conv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(powerseries(a)(x)) AND abs(y) < abs(x) IMPLIES
--  convergent?(powerseries(a)(y))
theorem powerseries_conv : convergent_p (powerseries a(x)) ∧ |y| < |x| → convergent_p (powerseries a(y)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.powerseries_diverg
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: divergent_series?(powerseq(a, x1)) AND abs(x) > abs(x1) IMPLIES
--  divergent_series?(powerseq(a, x))
theorem powerseries_diverg : divergent_series_p (powerseq a x1) ∧ |x| > |x1| → divergent_series_p (powerseq a x) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.series_convergent_within
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: abs(x) < c IMPLIES convergent?(series(powerseq(a, x))))
axiom series_convergent_within {pvs_τ22 : Type*} {pvs_τ23 : Type*} : pvs_τ22 → pvs_τ23 → Prop

-- pvs2lean: power_series.series_divergent_outside
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: abs(x) > c IMPLIES divergent_series?(powerseq(a, x)))
axiom series_divergent_outside {pvs_τ24 : Type*} {pvs_τ25 : Type*} : pvs_τ24 → pvs_τ25 → Prop

-- pvs2lean: power_series.series_convergent_only_at_0
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(series(powerseq(a, 0))) AND
--  (FORALL x: x /= 0 IMPLIES divergent_series?(powerseq(a, x)))
axiom series_convergent_only_at_0 {pvs_τ20 : Type*} {pvs_τ21 : Type*} : pvs_τ20 → pvs_τ21

-- pvs2lean: power_series.zero_powerseries_conv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: convergent?(powerseries(a)(0))
theorem zero_powerseries_conv : convergent_p (powerseries a 0) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.powerseries_three_cases
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (x: real): convergent?(powerseries(a)(x))) OR
--  (series_convergent_only_at_0(a)) OR
--   (EXISTS (r: posreal):
--      series_convergent_within(a, r) AND series_divergent_outside(a, r))
theorem powerseries_three_cases : (∀ (x : ℝ), convergent_p (powerseries a(x))) ∨ (series_convergent_only_at_0 a) ∨
 (∃ (r : {x : ℝ // 0 < x}), series_convergent_within a r ∧ series_divergent_outside a r) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.interval
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: {x: real | -c < x AND x < c}
axiom interval {pvs_τ10 : Type*} {pvs_τ11 : Type*} : pvs_τ10 → pvs_τ11

-- pvs2lean: power_series.powerseries_conv_abs_intv
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (x: (interval(c))): convergent?(series(powerseq(a, x)))) IMPLIES
--  (FORALL (x: (interval(c))): convergent?(series(abs(powerseq(a, x)))))
theorem powerseries_conv_abs_intv : (∀ (x : (interval c)), convergent_p (series (powerseq a x))) → (∀ (x : (interval c)), convergent_p (series (|powerseq a x|))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: power_series.apowerseq
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA (k: nat): IF k = 0 THEN a(0) ELSE a(k) * x ^ k ENDIF)
axiom apowerseq {pvs_τ2 : Type*} {pvs_τ3 : Type*} {pvs_τ4 : Type*} : pvs_τ2 → pvs_τ3 → pvs_τ4

-- pvs2lean: power_series.apow_rew
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: powerseq(a, x) = apowerseq(a, x)
theorem apow_rew : powerseq a x = apowerseq a x := by
  sorry  -- phase2_high: type translated, proof pending

end

end NavierStokesClean.PVSLib.power_series