-- Auto-generated by pvs2lean/translator.py
-- PVS theory: real_intervals
-- PVSLib library: lebesgue
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: real_intervals

Auto-generated stubs from PVSLib theory `real_intervals`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.real_intervals

noncomputable section

variable {pvs_τ1 : Type*} (borel_p : pvs_τ1 → Prop)
variable {pvs_τ2 : Type*} {pvs_τ3 : Type*} (rational_pred : pvs_τ2 → pvs_τ3)

-- pvs2lean: real_intervals.rationals
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: {x | rational_pred(x)}
noncomputable def rationals : sorry := by
  sorry  -- pvs2lean: definition stub for {x | rational_pred(x)}

end

end NavierStokesClean.PVSLib.real_intervals