-- Auto-generated by pvs2lean/translator.py
-- PVS theory: def_symmetric_matrix
-- PVSLib library: matrices
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: def_symmetric_matrix

Auto-generated stubs from PVSLib theory `def_symmetric_matrix`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.def_symmetric_matrix

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (below : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} (col : pvs_τ3 → pvs_τ4 → pvs_τ5)
variable {pvs_τ6 : Type*} (columns : pvs_τ6 → Prop)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} (cons : pvs_τ7 → pvs_τ8 → pvs_τ9)
variable {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} (entry : pvs_τ10 → pvs_τ11 → pvs_τ12 → pvs_τ13)
variable {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} (row : pvs_τ16 → pvs_τ17 → pvs_τ18)
variable {pvs_τ19 : Type*} (rows : pvs_τ19 → Prop)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} (upto : pvs_τ26 → pvs_τ27)

-- pvs2lean: def_symmetric_matrix.sym_row_col?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (row(A)(i) = col(A)(i))
axiom sym_row_col_p {pvs_τ22 : Type*} {pvs_τ23 : Type*} : pvs_τ22 → pvs_τ23 → Prop

-- pvs2lean: def_symmetric_matrix.sym_row_col_upto?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (j: upto(i)): sym_row_col?(A, j)
axiom sym_row_col_upto_p {pvs_τ24 : Type*} {pvs_τ25 : Type*} : pvs_τ24 → pvs_τ25 → Prop

-- pvs2lean: def_symmetric_matrix.sym_forall?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: sym_row_col_upto?(A, rows(A) - 1)
axiom sym_forall_p {pvs_τ20 : Type*} : pvs_τ20 → Prop

-- pvs2lean: def_symmetric_matrix.init_sym?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i = rows(A) - 1 THEN sym_row_col?(A, i)
-- ELSE sym_row_col?(A, i) AND init_sym?(A, i + 1)
-- ENDIF
axiom init_sym_p {pvs_τ14 : Type*} {pvs_τ15 : Type*} : pvs_τ14 → pvs_τ15 → Prop

-- pvs2lean: def_symmetric_matrix.sym?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: init_sym?(A, 0)
axiom sym_p {pvs_τ21 : Type*} : pvs_τ21 → Prop

-- pvs2lean: def_symmetric_matrix.sym_ex
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET A = (: (: 1, 2, 3 :), (: 2, 4, 5 :), (: 3, 5, 6 :) :),
--     B = (: (: 1, 2, 3 :), (: 4, 5, 6 :), (: 7, 8, 9 :) :)
--   IN sym?(A) AND NOT sym?(B)
theorem sym_ex : fun (A : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)}) => fun (B : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)}) => sym_p A ∧ ¬ sym_p B (cons ((: 1, 2, 3 :)) ((: (: 4, 5, 6 :), (: 7, 8, 9 :) :))) (cons ((: 1, 2, 3 :)) ((: (: 2, 4, 5 :), (: 3, 5, 6 :) :))) := by
  -- === TCCs for sym_ex ===
  -- TCC: sym_ex_TCC1
  -- Statement: FORALL (A: (cons?[list[real]]), B: (cons?[list[real]])):
  --   A = (: (: 1, 2, 3 :), (: 2, 4, 5 :), (: 3, 5, 6 :) :) AND
  --    B = (: (: 1, 2, 3 :), (: 4, 5, 6 :), (: 7, 8, 9 :) :)
  --    IMPLIES
  --    (null?[li...
  have sym_ex_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sym_ex_TCC2
  -- Statement: FORALL (A: (cons?[list[real]]), B: (cons?[list[real]])):
  --   A = (: (: 1, 2, 3 :), (: 2, 4, 5 :), (: 3, 5, 6 :) :) AND
  --    B = (: (: 1, 2, 3 :), (: 4, 5, 6 :), (: 7, 8, 9 :) :) AND sym?(A)
  --    IMPLIES
  -- ...
  have sym_ex_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: def_symmetric_matrix.sym_entry_def_forward
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A: Square):
--   sym?(A) IMPLIES FORALL (i, j: nat): entry(A)(i, j) = entry(A)(j, i)
theorem sym_entry_def_forward : ∀ (A : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}), sym_p A → ∀ (i : _) (j : ℕ), entry A(i, j) = entry A(j, i) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: def_symmetric_matrix.sym_entry_def_backward
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A: Square):
--   (FORALL (i, j: nat): entry(A)(i, j) = entry(A)(j, i)) IMPLIES sym?(A)
theorem sym_entry_def_backward : ∀ (A : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}), (∀ (i : _) (j : ℕ), entry A(i, j) = entry A(j, i)) → sym_p A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: def_symmetric_matrix.sym_entry_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A: Square):
--   (FORALL (i, j: nat): entry(A)(i, j) = entry(A)(j, i)) IFF sym?(A)
theorem sym_entry_def : ∀ (A : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}), (∀ (i : _) (j : ℕ), entry A(i, j) = entry A(j, i)) ↔ sym_p A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: def_symmetric_matrix.sym_add
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A, B: Square):
--   ((sym?(A) AND sym?(B)) AND rows(A) = rows(B)) IMPLIES sym?(A + B)
theorem sym_add : ∀ (A : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}) (B : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}), ((sym_p A ∧ sym_p B) ∧ rows A = rows B) → sym_p (A + B) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: def_symmetric_matrix.sym_scal
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A: Square, c: real): sym?(A) IMPLIES sym?(c * A)
theorem sym_scal : ∀ (A : {D : {SM : {M : {x : List (List ℝ) // every (fun (x : List ℝ)=> every (fun (x : ℝ)=> number_field_pred x ∧ real_pred x) (x))
     (x)} // null_p M ∨
 ∀ (i : _) (j : Finset.range List.length M), List.length (nth M i) = List.length (nth M j)} // rows SM > 0 ∧ columns SM > 0} // rows D = columns D}) (c : ℝ), sym_p A → sym_p (c * A) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.def_symmetric_matrix