-- Auto-generated by pvs2lean/translator.py
-- PVS theory: integral_def
-- PVSLib library: analysis
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: integral_def

Auto-generated stubs from PVSLib theory `integral_def`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.integral_def

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (Integrable_funs : pvs_τ1 → pvs_τ2 → pvs_τ3)
variable {pvs_τ35 : Type*} {pvs_τ36 : Type*} (above : pvs_τ35 → pvs_τ36)
variable {pvs_τ37 : Type*} {pvs_τ38 : Type*} (below : pvs_τ37 → pvs_τ38)
variable {pvs_τ39 : Type*} {pvs_τ40 : Type*} {pvs_τ41 : Type*} (closed_interval : pvs_τ39 → pvs_τ40 → pvs_τ41)
variable {pvs_τ46 : Type*} (floor : pvs_τ46 → Prop)
variable {pvs_τ47 : Type*} (fs : pvs_τ47 → Prop)
variable {pvs_τ58 : Type*} (length : pvs_τ58 → Prop)
variable {pvs_τ59 : Type*} {pvs_τ60 : Type*} (max : pvs_τ59 → pvs_τ60)
variable {pvs_τ61 : Type*} {pvs_τ62 : Type*} {pvs_τ63 : Type*} (partition : pvs_τ61 → pvs_τ62 → pvs_τ63)
variable {pvs_τ68 : Type*} {pvs_τ69 : Type*} (seq : pvs_τ68 → pvs_τ69 → Prop)
variable {pvs_τ70 : Type*} {pvs_τ71 : Type*} (upto : pvs_τ70 → pvs_τ71)
variable {pvs_τ78 : Type*} (xis : pvs_τ78 → Prop)
variable {pvs_τ82 : Type*} (xx : pvs_τ82 → Prop)

-- pvs2lean: integral_def.T_pred
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom T_pred {pvs_τ34 : Type*} : pvs_τ34 → Prop

-- pvs2lean: integral_def.connected_domain
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem connected_domain : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.not_one_element
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem not_one_element : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.width
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom width {pvs_τ72 : Type*} {pvs_τ73 : Type*} {pvs_τ74 : Type*} : pvs_τ72 → pvs_τ73 → pvs_τ74 → Prop

-- pvs2lean: integral_def.width_lem
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem width_lem : True := by
  -- === TCCs for width_lem ===
  -- TCC: width_lem_TCC1
  -- Statement: FORALL (a: T, b: {x: T | a < x}, P: partition(a, b),
  --         ii: below(length(P) - 1)):
  --   ii + 1 < length(P)
  have width_lem_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: width_lem_TCC2
  -- Statement: FORALL (a: T, b: {x: T | a < x}, P: partition(a, b),
  --         ii: below(length(P) - 1)):
  --   ii < length(P)
  have width_lem_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.parts_order
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem parts_order : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.parts_order_le
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem parts_order_le : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.parts_disjoint
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem parts_disjoint : True := by
  -- === TCCs for parts_disjoint ===
  -- TCC: parts_disjoint_TCC1
  -- Statement: FORALL (a, b: T, P: partition(a, b), ii, jj: below(length(P) - 1)):
  --   ii < P`length
  have parts_disjoint_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: parts_disjoint_TCC2
  -- Statement: FORALL (a, b, x: T, P: partition(a, b), ii, jj: below(length(P) - 1)):
  --   seq(P)(ii) < x IMPLIES 1 + ii < P`length
  have parts_disjoint_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: parts_disjoint_TCC3
  -- Statement: FORALL (a, b, x: T, P: partition(a, b), ii, jj: below(length(P) - 1)):
  --   seq(P)(ii) < x AND x < seq(P)(1 + ii) IMPLIES jj < P`length
  have parts_disjoint_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: parts_disjoint_TCC4
  -- Statement: FORALL (a, b, x: T, P: partition(a, b), ii, jj: below(length(P) - 1)):
  --   seq(P)(ii) < x AND x < seq(P)(1 + ii) AND seq(P)(jj) < x IMPLIES
  --    1 + jj < P`length
  have parts_disjoint_tcc4 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.in_part?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def in_part_p : sorry := by
  sorry  -- pvs2lean: definition stub for EXISTS (ii: below(length(P) - 1)): xx = seq(P)(ii)

-- pvs2lean: integral_def.in_sect?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def in_sect_p : sorry := by
  sorry  -- pvs2lean: definition stub for seq(P)(ii) < xx AND xx < seq(P)(ii + 1)

-- pvs2lean: integral_def.part_in
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem part_in : True := by
  -- === TCCs for part_in ===
  -- TCC: part_in_TCC1
  -- Statement: FORALL (a, b, x: T, P: partition(a, b)):
  --   a < b AND a <= x AND x <= b IMPLIES
  --    FORALL (ii: below(length(P) - 1)): ii < P`length
  have part_in_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: part_in_TCC2
  -- Statement: FORALL (a, b, x: T, P: partition(a, b)):
  --   a < b AND a <= x AND x <= b IMPLIES
  --    FORALL (ii: below(length(P) - 1)):
  --      seq(P)(ii) <= x IMPLIES ii + 1 < P`length
  have part_in_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.part_not_in
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem part_not_in : True := by
  -- === TCCs for part_not_in ===
  -- TCC: part_not_in_TCC1
  -- Statement: FORALL (a, b, x: T):
  --   a < b IMPLIES
  --    FORALL (P: partition(a, b), ii, jj: below(length(P) - 1)):
  --      seq(P)(ii) < x IMPLIES ii + 1 < P`length
  have part_not_in_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: part_not_in_TCC2
  -- Statement: FORALL (a, b, x: T):
  --   a < b IMPLIES
  --    FORALL (P: partition(a, b), ii, jj: below(length(P) - 1)):
  --      seq(P)(ii) < x AND x < seq(P)(ii + 1) IMPLIES jj < P`length
  have part_not_in_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.part_induction
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem part_induction : True := by
  -- === TCCs for part_induction ===
  -- TCC: part_induction_TCC1
  -- Statement: FORALL (a, b: T, P: partition(a, b), x: closed_interval[T](a, b),
  --         xx: [below[P`length] -> closed_interval[T](a, b)], N: nat):
  --   xx = seq(P) AND N = length(P) IMPLIES
  --    FORALL (ii: below(N ...
  have part_induction_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: part_induction_TCC2
  -- Statement: FORALL (a, b: T, P: partition(a, b), x: closed_interval[T](a, b),
  --         xx: [below[P`length] -> closed_interval[T](a, b)], N: nat):
  --   xx = seq(P) AND N = length(P) IMPLIES
  --    FORALL (ii: below(N ...
  have part_induction_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.eq_partition
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom eq_partition {pvs_τ42 : Type*} {pvs_τ43 : Type*} {pvs_τ44 : Type*} {pvs_τ45 : Type*} : pvs_τ42 → pvs_τ43 → pvs_τ44 → pvs_τ45

-- pvs2lean: integral_def.xis?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom xis_p {pvs_τ79 : Type*} {pvs_τ80 : Type*} {pvs_τ81 : Type*} : pvs_τ79 → pvs_τ80 → pvs_τ81 → Prop

-- pvs2lean: integral_def.xis_lem
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem xis_lem : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.Rie_sum
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Rie_sum {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} : pvs_τ17 → pvs_τ18 → pvs_τ19 → pvs_τ20 → pvs_τ21 → pvs_τ22

-- pvs2lean: integral_def.Rie_sec
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Rie_sec {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} : pvs_τ10 → pvs_τ11 → pvs_τ12 → pvs_τ13 → pvs_τ14 → pvs_τ15 → pvs_τ16

-- pvs2lean: integral_def.Rie_sum_alt
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Rie_sum_alt {pvs_τ23 : Type*} {pvs_τ24 : Type*} {pvs_τ25 : Type*} {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} : pvs_τ23 → pvs_τ24 → pvs_τ25 → pvs_τ26 → pvs_τ27 → pvs_τ28

-- pvs2lean: integral_def.Rie_sum_alt_lem
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem Rie_sum_alt_lem : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.Riemann_sum?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Riemann_sum_p {pvs_τ29 : Type*} {pvs_τ30 : Type*} {pvs_τ31 : Type*} {pvs_τ32 : Type*} {pvs_τ33 : Type*} : pvs_τ29 → pvs_τ30 → pvs_τ31 → pvs_τ32 → pvs_τ33 → Prop

-- pvs2lean: integral_def.integral?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom integral_p {pvs_τ54 : Type*} {pvs_τ55 : Type*} {pvs_τ56 : Type*} {pvs_τ57 : Type*} : pvs_τ54 → pvs_τ55 → pvs_τ56 → pvs_τ57 → Prop

-- pvs2lean: integral_def.x_in
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom x_in {pvs_τ75 : Type*} {pvs_τ76 : Type*} {pvs_τ77 : Type*} : pvs_τ75 → pvs_τ76 → pvs_τ77

-- pvs2lean: integral_def.pick_one
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom pick_one {pvs_τ64 : Type*} {pvs_τ65 : Type*} {pvs_τ66 : Type*} {pvs_τ67 : Type*} : pvs_τ64 → pvs_τ65 → pvs_τ66 → pvs_τ67

-- pvs2lean: integral_def.gen_xis
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def gen_xis : sorry := by
  sorry  -- pvs2lean: definition stub for finseq_appl[real]((# length := length(P) - 1, seq := pick_one(a, b, P) #))

-- pvs2lean: integral_def.len_eq_part
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem len_eq_part : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.eq_part_lem_a
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem eq_part_lem_a : True := by
  -- === TCCs for eq_part_lem_a ===
  -- TCC: eq_part_lem_a_TCC1
  -- Statement: FORALL (N: above(1), a, b: T):
  --   a < b IMPLIES 0 < eq_partition(a, b, N)`length
  have eq_part_lem_a_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.eq_part_lem_b
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem eq_part_lem_b : True := by
  -- === TCCs for eq_part_lem_b ===
  -- TCC: eq_part_lem_b_TCC1
  -- Statement: FORALL (N: above(1), a, b: T):
  --   a < b IMPLIES N - 1 >= 0 AND N - 1 < eq_partition(a, b, N)`length
  have eq_part_lem_b_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.width_eq_part
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem width_eq_part : True := by
  -- === TCCs for width_eq_part ===
  -- TCC: width_eq_part_TCC1
  -- Statement: FORALL (N: above(1), a, b: T): a < b IMPLIES (N - 1) /= 0
  have width_eq_part_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.N_from_delta
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem N_from_delta : True := by
  -- === TCCs for N_from_delta ===
  -- TCC: N_from_delta_TCC1
  -- Statement: FORALL (a, b: T, delta: posreal):
  --   a < b IMPLIES
  --    FORALL (N: int): N = 2 + floor((b - a) / delta) IMPLIES N > 1
  have n_from_delta_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.Riemann?_Rie
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem Riemann_p_Rie : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.integral_unique
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem integral_unique : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.integrable?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom integrable_p {pvs_τ48 : Type*} {pvs_τ49 : Type*} {pvs_τ50 : Type*} : pvs_τ48 → pvs_τ49 → pvs_τ50 → Prop

-- pvs2lean: integral_def.integral
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom integral {pvs_τ51 : Type*} {pvs_τ52 : Type*} {pvs_τ53 : Type*} : pvs_τ51 → pvs_τ52 → pvs_τ53 → Prop

-- pvs2lean: integral_def.integral_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem integral_def : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.integral_restrict_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem integral_restrict_eq : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.Integrable?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Integrable_p {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ4 → pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: integral_def.Integral?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def Integral_p : sorry := by
  sorry  -- pvs2lean: definition stub for (a = b AND S = 0) OR (a < b AND integral?(a, b, f, S))

-- pvs2lean: integral_def.Integral
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom Integral {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} : pvs_τ7 → pvs_τ8 → pvs_τ9 → Prop

-- pvs2lean: integral_def.Integrable?_rew
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem Integrable_p_rew : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: integral_def.Integral_rew
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem Integral_rew : True := by
  -- === TCCs for Integral_rew ===
  -- TCC: Integral_rew_TCC1
  -- Statement: FORALL (a, b: T, f: [T -> real]):
  --   Integrable?(a, b, f) AND a < b IMPLIES integrable?(a, b, f)
  have integral_rew_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

end

end NavierStokesClean.PVSLib.integral_def