-- Auto-generated by pvs2lean/translator.py
-- PVS theory: monotone_subsequence
-- PVSLib library: analysis
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: monotone_subsequence

Auto-generated stubs from PVSLib theory `monotone_subsequence`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.monotone_subsequence

noncomputable section

variable {pvs_τ1 : Type*} (decreasing_p : pvs_τ1 → Prop)
variable {pvs_τ8 : Type*} (increasing_p : pvs_τ8 → Prop)
variable {pvs_τ13 : Type*} (strict_decreasing_p : pvs_τ13 → Prop)
variable {pvs_τ14 : Type*} (strict_increasing_p : pvs_τ14 → Prop)
variable {pvs_τ15 : Type*} {pvs_τ16 : Type*} (subseq : pvs_τ15 → pvs_τ16 → Prop)

-- pvs2lean: monotone_subsequence.has_minimum
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom has_minimum {pvs_τ4 : Type*} {pvs_τ5 : Type*} : pvs_τ4 → pvs_τ5 → Prop

-- pvs2lean: monotone_subsequence.minimum_prefix
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem minimum_prefix : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.minimum_suffix
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem minimum_suffix : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.mini
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom mini {pvs_τ9 : Type*} {pvs_τ10 : Type*} : pvs_τ9 → pvs_τ10 → Prop

-- pvs2lean: monotone_subsequence.min_prop
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem min_prop : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.min_prop1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem min_prop1 : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.min_prop2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem min_prop2 : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.h
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def h : sorry := by
  sorry  -- pvs2lean: definition stub for IF i = 0 THEN mini(v, 0) ELSE mini(v, h(v)(i - 1) + 1) ENDIF

-- pvs2lean: monotone_subsequence.hseq
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom hseq {pvs_τ6 : Type*} {pvs_τ7 : Type*} : pvs_τ6 → pvs_τ7

-- pvs2lean: monotone_subsequence.h_increasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem h_increasing : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.hseq_extraction
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem hseq_extraction : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.hseq_increasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem hseq_increasing : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.no_minimum
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem no_minimum : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.pick
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom pick {pvs_τ11 : Type*} {pvs_τ12 : Type*} : pvs_τ11 → pvs_τ12 → Prop

-- pvs2lean: monotone_subsequence.pick_prop
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem pick_prop : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.pick_prop1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem pick_prop1 : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.pick_prop2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem pick_prop2 : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.g
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def g : sorry := by
  sorry  -- pvs2lean: definition stub for IF i = 0 THEN pick(w, 0) ELSE pick(w, g(w)(i - 1)) ENDIF

-- pvs2lean: monotone_subsequence.gseq
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom gseq {pvs_τ2 : Type*} {pvs_τ3 : Type*} : pvs_τ2 → pvs_τ3

-- pvs2lean: monotone_subsequence.g_increasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem g_increasing : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.gseq_extraction
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem gseq_extraction : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.gseq_decreasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem gseq_decreasing : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.suffix
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom suffix {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} : pvs_τ17 → pvs_τ18 → pvs_τ19

-- pvs2lean: monotone_subsequence.suffix_subseq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem suffix_subseq : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.suffix_hasmin
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem suffix_hasmin : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: monotone_subsequence.monotone_subsequence
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem monotone_subsequence : True := by
  sorry  -- needs_human: automated tactics exhausted

end

end NavierStokesClean.PVSLib.monotone_subsequence