-- Auto-generated by pvs2lean/translator.py
-- PVS theory: radix_sort_nat
-- PVSLib library: sorting
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: radix_sort_nat

Auto-generated stubs from PVSLib theory `radix_sort_nat`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.radix_sort_nat

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (car : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} (cdr : pvs_τ3 → pvs_τ4)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} (div : pvs_τ7 → pvs_τ8 → Prop)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (length : pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} (lex : pvs_τ11 → pvs_τ12 → pvs_τ13 → Prop)
variable {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} (max : pvs_τ14 → pvs_τ15 → pvs_τ16)
variable {pvs_τ21 : Type*} {pvs_τ22 : Type*} {pvs_τ23 : Type*} (nmod : pvs_τ21 → pvs_τ22 → pvs_τ23)
variable {pvs_τ24 : Type*} {pvs_τ25 : Type*} {pvs_τ26 : Type*} (nth : pvs_τ24 → pvs_τ25 → pvs_τ26)
variable {pvs_τ27 : Type*} (null_p : pvs_τ27 → Prop)
variable {pvs_τ28 : Type*} {pvs_τ29 : Type*} (permutations : pvs_τ28 → pvs_τ29 → Prop)
variable {pvs_τ30 : Type*} {pvs_τ31 : Type*} (radixsort : pvs_τ30 → pvs_τ31)
variable {pvs_τ32 : Type*} (total_preorder_p : pvs_τ32 → Prop)

-- pvs2lean: radix_sort_nat.d_nth
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF d = 0 THEN nmod(n, 10) ELSE d_nth(div(n, 10), d - 1) ENDIF
axiom d_nth {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: radix_sort_nat.n_digits
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF n < 10 THEN 1 ELSE 1 + n_digits(div(n, 10)) ENDIF
axiom n_digits {pvs_τ19 : Type*} {pvs_τ20 : Type*} : pvs_τ19 → pvs_τ20

-- pvs2lean: radix_sort_nat.max_digits
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF length(l) = 1 THEN n_digits(car(l))
-- ELSE max(n_digits(car(l)), max_digits(cdr(l)))
-- ENDIF
axiom max_digits {pvs_τ17 : Type*} {pvs_τ18 : Type*} : pvs_τ17 → pvs_τ18

-- pvs2lean: radix_sort_nat.max_digits_works
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (l: (cons?[nat]), i: below[length(l)]):
--   n_digits(nth(l, i)) <= max_digits(l)
theorem max_digits_works : ∀ (l : List ℝ) (i : {s : {i : ℝ // i ≥ 0} // s < List.length l}), n_digits (nth l i) ≤ max_digits l := by
  -- === TCCs for max_digits_works ===
  -- TCC: max_digits_works_TCC1
  -- Statement: FORALL (l: (cons?[nat]), i: below[length[nat](l)]): length[nat](l) >= 1
  have max_digits_works_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.d_nth_zero
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i: nat): d_nth(0, i) = 0
theorem d_nth_zero : ∀ (i : {i : ℝ // i ≥ 0}), d_nth 0 i = 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.d_nth_digits
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (m, n: nat, i: nat | i > 0):
--   (max(n_digits(m), n_digits(n)) <= i AND
--     d_nth(m, i - 1) < d_nth(n, i - 1))
--    => m < n
theorem d_nth_digits : ∀ (m : {i : ℝ // i ≥ 0}) (n : {i : ℝ // i ≥ 0}) (i : {i : {i : ℝ // i ≥ 0} // i > 0}), (max (n_digits m) (n_digits n) ≤ i ∧ d_nth m (i - 1) < d_nth n (i - 1)) → m < n := by
  -- === TCCs for d_nth_digits ===
  -- TCC: d_nth_digits_TCC1
  -- Statement: FORALL (m, n: nat, i: nat | i > 0):
  --   max(n_digits(m), n_digits(n)) <= i IMPLIES i - 1 >= 0
  have d_nth_digits_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.d_exp_dec
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (n, d: nat):
--   d_nth(n, d) * 10 ^ d + nmod(n, 10 ^ d) = nmod(n, 10 ^ (1 + d))
theorem d_exp_dec : ∀ (n : {i : ℝ // i ≥ 0}) (d : {i : ℝ // i ≥ 0}), d_nth n d * 10 ^ d + nmod n (10 ^ d) = nmod n (10 ^ (1 + d)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.d_nth_rem
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x, m, k: nat):
--   d_nth(nmod(m, 10 ^ (x + 1)), x) = d_nth(nmod(m, 10 ^ (x + 1 + k)), x)
theorem d_nth_rem : ∀ (x : {i : ℝ // i ≥ 0}) (m : {i : ℝ // i ≥ 0}) (k : {i : ℝ // i ≥ 0}), d_nth (nmod m (10 ^ (x + 1))) x = d_nth (nmod m (10 ^ (x + 1 + k))) x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.n_digits_power
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (m, x: nat): m < 10 ^ (n_digits(m) + x)
theorem n_digits_power : ∀ (m : {i : ℝ // i ≥ 0}) (x : {i : ℝ // i ≥ 0}), m < 10 ^ (n_digits m + x) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.d_nth_nmod
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x: posnat, m: nat, (j: nat | x <= j)):
--   d_nth(m, x - 1) = d_nth(nmod(m, 10 ^ j), x - 1)
theorem d_nth_nmod : ∀ (x : {i : {i : ℝ // i ≥ 0} // i > 0}) (m : {i : ℝ // i ≥ 0}) (j : {j : {i : ℝ // i ≥ 0} // x ≤ j}), d_nth m (x - 1) = d_nth (nmod m (10 ^ j)) (x - 1) := by
  -- === TCCs for d_nth_nmod ===
  -- TCC: d_nth_nmod_TCC1
  -- Statement: FORALL (x: posnat, (j: nat | x <= j)): x - 1 >= 0
  have d_nth_nmod_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.n_digits_monotone
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a, b: nat): a <= b => n_digits(a) <= n_digits(b)
theorem n_digits_monotone : ∀ (a : {i : ℝ // i ≥ 0}) (b : {i : ℝ // i ≥ 0}), a ≤ b → n_digits a ≤ n_digits b := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.n_digits_ten_power
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (x: posnat): n_digits(10 ^ x - 1) = x
theorem n_digits_ten_power : ∀ (x : {i : {i : ℝ // i ≥ 0} // i > 0}), n_digits (10 ^ x - 1) = x := by
  -- === TCCs for n_digits_ten_power ===
  -- TCC: n_digits_ten_power_TCC1
  -- Statement: FORALL (x: posnat): 10 ^ x - 1 >= 0
  have n_digits_ten_power_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.n_digits_nmod_leq
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (n: nat, x: posnat): n_digits(nmod(n, 10 ^ x)) <= x
theorem n_digits_nmod_leq : ∀ (n : {i : ℝ // i ≥ 0}) (x : {i : {i : ℝ // i ≥ 0} // i > 0}), n_digits (nmod n (10 ^ x)) ≤ x := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.N
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def N : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: radix_sort_nat.leq_N
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: LAMBDA (i: below[N]): (LAMBDA (m, n: nat): d_nth(m, i) <= d_nth(n, i))
noncomputable def leq_N : sorry := by
  sorry  -- pvs2lean: definition stub for LAMBDA (i: below[N]): (LAMBDA (m, n: nat): d_nth(m, i) <= d_nth(n, i))

-- pvs2lean: radix_sort_nat.lex_preserves
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (m, n: nat, i: below[N], j: nat | i <= j):
--   lex(i)(m, n) <=> lex(i)(nmod(m, 10 ^ j), nmod(n, 10 ^ j))
theorem lex_preserves : ∀ (m : {i : ℝ // i ≥ 0}) (n : {i : ℝ // i ≥ 0}) (i : {s : {i : ℝ // i ≥ 0} // s < N}) (j : {j : {i : ℝ // i ≥ 0} // i ≤ j}), lex i(m, n) <=> lex i(nmod m (10 ^ j), nmod n (10 ^ j)) := by
  -- === TCCs for lex_preserves ===
  -- TCC: lex_preserves_TCC1
  -- Statement: FORALL (i: below[N], j: nat | i <= j): i <= N
  have lex_preserves_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.lex_nat_works_aux
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (m, n: nat, i: nat, j: below[N + 1] | i <= j):
--   (max(n_digits(m), n_digits(n)) <= i AND lex(j)(m, n)) => m <= n
theorem lex_nat_works_aux : ∀ (m : {i : ℝ // i ≥ 0}) (n : {i : ℝ // i ≥ 0}) (i : {i : ℝ // i ≥ 0}) (j : {j : {s : {i : ℝ // i ≥ 0} // s < 1 + N} // i ≤ j}), (max (n_digits m) (n_digits n) ≤ i ∧ lex j(m, n)) → m ≤ n := by
  -- === TCCs for lex_nat_works_aux ===
  -- TCC: lex_nat_works_aux_TCC1
  -- Statement: FORALL (m, n: nat, i: nat, j: below[N + 1] | i <= j):
  --   max(n_digits(m), n_digits(n)) <= i IMPLIES j <= N
  have lex_nat_works_aux_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.lex_nat_works
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (m, n: nat):
--   (max(n_digits(m), n_digits(n)) <= N AND lex(N)(m, n)) => m <= n
theorem lex_nat_works : ∀ (m : {i : ℝ // i ≥ 0}) (n : {i : ℝ // i ≥ 0}), (max (n_digits m) (n_digits n) ≤ N ∧ lex N(m, n)) → m ≤ n := by
  -- === TCCs for lex_nat_works ===
  -- TCC: lex_nat_works_TCC1
  -- Statement: FORALL (m, n: nat): max(n_digits(m), n_digits(n)) <= N IMPLIES N <= N
  have lex_nat_works_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: radix_sort_nat.radixsort_nat_works
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (l: list[nat]):
--   permutations(radixsort(l), l) AND
--    IF null?(l)
--      THEN is_sorted?[nat, restrict[[real, real], [nat, nat], bool](<=)]
--               (radixsort(l))
--    ELSE max_digits(l) <= 
theorem radixsort_nat_works : ∀ (l : List ℝ), permutations (radixsort l) l ∧ if null_p l
  then is_sorted_p[nat, restrict[[real, real], [nat, nat], bool](≤)]
           (radixsort l)
else max_digits l ≤ N →
      is_sorted_p[nat, restrict[[real, real], [nat, nat], bool](≤)]
          (radixsort l) := by
  -- === TCCs for radixsort_nat_works ===
  -- TCC: radixsort_nat_works_TCC1
  -- Statement: FORALL (l: list[nat]):
  --   permutations(radixsort(l), l) AND NOT null?(l) IMPLIES length[nat](l) >= 1
  have radixsort_nat_works_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.radix_sort_nat