-- Auto-generated by pvs2lean/translator.py
-- PVS theory: cantor_bernstein_schroeder
-- PVSLib library: sets_aux
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: cantor_bernstein_schroeder

Auto-generated stubs from PVSLib theory `cantor_bernstein_schroeder`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.cantor_bernstein_schroeder

noncomputable section

variable {pvs_τ33 : Type*} (bijective_p : pvs_τ33 → Prop)
variable {pvs_τ34 : Type*} {pvs_τ35 : Type*} (choose : pvs_τ34 → pvs_τ35)
variable {pvs_τ36 : Type*} (injective_p : pvs_τ36 → Prop)

-- pvs2lean: cantor_bernstein_schroeder.preim_B?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: EXISTS (a: A): f(a) = b
axiom preim_B_p {pvs_τ37 : Type*} {pvs_τ38 : Type*} : pvs_τ37 → pvs_τ38 → Prop

-- pvs2lean: cantor_bernstein_schroeder.preim_A?
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: EXISTS (b: B): g(b) = a
noncomputable def preim_A_p : sorry := by
  sorry  -- pvs2lean: definition stub for EXISTS (b: B): g(b) = a

-- pvs2lean: cantor_bernstein_schroeder.Afun
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i = 0 THEN (a, f(a))
-- ELSE LET bo = Afun(f, g)(a)(i - 1)`2 IN (g(bo), f(g(bo)))
-- ENDIF
axiom Afun {pvs_τ5 : Type*} {pvs_τ6 : Type*} {pvs_τ7 : Type*} {pvs_τ8 : Type*} : pvs_τ5 → pvs_τ6 → pvs_τ7 → pvs_τ8 → Prop

-- pvs2lean: cantor_bernstein_schroeder.Afundef
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i: nat, aa: A): LET (a, b) = Afun(f, g)(aa)(i) IN f(a) = b
theorem Afundef : ∀ (i : {i : ℝ // i ≥ 0}) (aa : A), fun (a : A) (b : B) => f a = b (Afun f g aa i) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Afundef2
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i: nat, a: A): g(Afun(f, g)(a)(i)`2) = Afun(f, g)(a)(i + 1)`1
theorem Afundef2 : ∀ (i : {i : ℝ // i ≥ 0}) (a : A), g (Afun f g(a) (i).2) = Afun f g(a) (i + 1).1 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Afuncomp
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i, j: nat, a: A):
--   Afun(f, g)(Afun(f, g)(a)(i)`1)(j) = Afun(f, g)(a)(i + j)
theorem Afuncomp : ∀ (i : {i : ℝ // i ≥ 0}) (j : {i : ℝ // i ≥ 0}) (a : A), Afun f g(Afun f g(a) (i).1) (j) = Afun f g(a) (i + j) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Afuneq
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i, j: nat, a1, a2: A):
--   injective?(f) AND
--    injective?(g) AND
--     (Afun(f, g)(a1)(i)`1 = Afun(f, g)(a2)(j)`1 OR
--       Afun(f, g)(a1)(i)`2 = Afun(f, g)(a2)(j)`2)
--    IMPLIES
--    FORALL (k: nat)
theorem Afuneq : ∀ (i : {i : ℝ // i ≥ 0}) (j : {i : ℝ // i ≥ 0}) (a1 : A) (a2 : A), injective_p f ∧
 injective_p g ∧
  (Afun f g(a1) (i).1 = Afun f g(a2) (j).1 ∨
    Afun f g(a1) (i).2 = Afun f g(a2) (j).2) → ∀ (k : ℕ), k ≤ i ∧ k ≤ j → Afun f g(a1) (i - k) = Afun f g(a2) (j - k) := by
  -- === TCCs for Afuneq ===
  -- TCC: Afuneq_TCC1
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, a1, a2: A):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Afun(f, g)(a1)(i)`1 = Afun(f, g)(a2)(j)`1 OR
  --       Afun(f, g)(a1)(i)`2 = Afun(f, g)(a2)(j)`2)
  -- ...
  have afuneq_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: Afuneq_TCC2
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, a1, a2: A):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Afun(f, g)(a1)(i)`1 = Afun(f, g)(a2)(j)`1 OR
  --       Afun(f, g)(a1)(i)`2 = Afun(f, g)(a2)(j)`2)
  -- ...
  have afuneq_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Bfun
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i = 0
--   THEN IF (EXISTS (a: A): f(a) = b)
--          THEN LET a = choose({aa: A | f(aa) = b}) IN (a, b)
--        ELSE (g(b), b)
--        ENDIF
-- ELSE LET bo = Bfun(f, g)(b)(i - 1)`2 IN (g(bo), f(g(bo)))
-- EN
axiom Bfun {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} : pvs_τ17 → pvs_τ18 → pvs_τ19 → pvs_τ20 → Prop

-- pvs2lean: cantor_bernstein_schroeder.Bfundef
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B, i: nat): g(Bfun(f, g)(b)(i)`2) = Bfun(f, g)(b)(i + 1)`1
theorem Bfundef : ∀ (b : B) (i : {i : ℝ // i ≥ 0}), g (Bfun f g(b) (i).2) = Bfun f g(b) (i + 1).1 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Bfundef2
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B, i: posnat): f(Bfun(f, g)(b)(i)`1) = Bfun(f, g)(b)(i)`2
theorem Bfundef2 : ∀ (b : B) (i : {i : {i : ℝ // i ≥ 0} // i > 0}), f (Bfun f g(b) (i).1) = Bfun f g(b) (i).2 := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Bfuneq
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i, j: nat, b: B):
--   injective?(f) AND
--    injective?(g) AND
--     (Bfun(f, g)(b)(i)`1 = Bfun(f, g)(b)(j)`1 OR
--       Bfun(f, g)(b)(i)`2 = Bfun(f, g)(b)(j)`2)
--    IMPLIES
--    FORALL (k: nat):
--      k 
theorem Bfuneq : ∀ (i : {i : ℝ // i ≥ 0}) (j : {i : ℝ // i ≥ 0}) (b : B), injective_p f ∧
 injective_p g ∧
  (Bfun f g(b) (i).1 = Bfun f g(b) (j).1 ∨
    Bfun f g(b) (i).2 = Bfun f g(b) (j).2) → ∀ (k : ℕ), k < i ∧ k < j → Bfun f g(b) (i - k) = Bfun f g(b) (j - k) := by
  -- === TCCs for Bfuneq ===
  -- TCC: Bfuneq_TCC1
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, b: B):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Bfun(f, g)(b)(i)`1 = Bfun(f, g)(b)(j)`1 OR
  --       Bfun(f, g)(b)(i)`2 = Bfun(f, g)(b)(j)`2)
  --    IMPLIE...
  have bfuneq_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: Bfuneq_TCC2
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, b: B):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Bfun(f, g)(b)(i)`1 = Bfun(f, g)(b)(j)`1 OR
  --       Bfun(f, g)(b)(i)`2 = Bfun(f, g)(b)(j)`2)
  --    IMPLIE...
  have bfuneq_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABfun
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a: A, i: posnat): Afun(f, g)(a)(i) = Bfun(f, g)(f(a))(i)
theorem ABfun : ∀ (a : A) (i : {i : {i : ℝ // i ≥ 0} // i > 0}), Afun f g(a) (i) = Bfun f g(f a) (i) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.BAfun
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B, i: nat): Bfun(f, g)(b)(i + 1) = Afun(f, g)(g(b))(i)
theorem BAfun : ∀ (b : B) (i : {i : ℝ // i ≥ 0}), Bfun f g(b) (i + 1) = Afun f g(g b) (i) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABfuneq
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i, j: nat, b: B, a: A):
--   injective?(f) AND
--    injective?(g) AND
--     (Bfun(f, g)(b)(i)`1 = Afun(f, g)(a)(j)`1 OR
--       Bfun(f, g)(b)(i)`2 = Afun(f, g)(a)(j)`2)
--    IMPLIES
--    FORALL (k: nat):
--  
theorem ABfuneq : ∀ (i : {i : ℝ // i ≥ 0}) (j : {i : ℝ // i ≥ 0}) (b : B) (a : A), injective_p f ∧
 injective_p g ∧
  (Bfun f g(b) (i).1 = Afun f g(a) (j).1 ∨
    Bfun f g(b) (i).2 = Afun f g(a) (j).2) → ∀ (k : ℕ), k < i ∧ k ≤ j → Bfun f g(b) (i - k) = Afun f g(a) (j - k) := by
  -- === TCCs for ABfuneq ===
  -- TCC: ABfuneq_TCC1
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, b: B, a: A):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Bfun(f, g)(b)(i)`1 = Afun(f, g)(a)(j)`1 OR
  --       Bfun(f, g)(b)(i)`2 = Afun(f, g)(a)(j)`2)
  --    ...
  have abfuneq_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: ABfuneq_TCC2
  -- Statement: FORALL (f: [A -> B], g: [B -> A], i, j: nat, b: B, a: A):
  --   injective?(f) AND
  --    injective?(g) AND
  --     (Bfun(f, g)(b)(i)`1 = Afun(f, g)(a)(j)`1 OR
  --       Bfun(f, g)(b)(i)`2 = Afun(f, g)(a)(j)`2)
  --    ...
  have abfuneq_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABrel
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (EXISTS (i: nat): b = Afun(f, g)(a)(i)`2) OR
--  (EXISTS (i: nat): a = Bfun(f, g)(b)(i)`1)
axiom ABrel {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} {pvs_τ4 : Type*} : pvs_τ1 → pvs_τ2 → pvs_τ3 → pvs_τ4 → Prop

-- pvs2lean: cantor_bernstein_schroeder.BArel
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: ABrel(f, g)(a)(b)
axiom BArel {pvs_τ13 : Type*} {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} : pvs_τ13 → pvs_τ14 → pvs_τ15 → pvs_τ16 → Prop

-- pvs2lean: cantor_bernstein_schroeder.Arel
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (EXISTS (i: nat): a1 = Afun(f, g)(a2)(i)`1) OR
--  (EXISTS (i: nat): a2 = Afun(f, g)(a1)(i)`1)
axiom Arel {pvs_τ9 : Type*} {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} : pvs_τ9 → pvs_τ10 → pvs_τ11 → pvs_τ12 → Prop

-- pvs2lean: cantor_bernstein_schroeder.Brel
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (EXISTS (i: nat): b1 = Bfun(f, g)(b2)(i)`2) OR
--  (EXISTS (i: nat): b2 = Bfun(f, g)(b1)(i)`2)
axiom Brel {pvs_τ21 : Type*} {pvs_τ22 : Type*} {pvs_τ23 : Type*} {pvs_τ24 : Type*} : pvs_τ21 → pvs_τ22 → pvs_τ23 → pvs_τ24 → Prop

-- pvs2lean: cantor_bernstein_schroeder.ABrel_Arel_equiv
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B, a, aa: A):
--        (NOT preim_B?(f)(b)) AND ABrel(f, g)(a)(b) AND Arel(f, g)(a)(aa)
--    AND injective?(f) AND injective?(g)
--    IMPLIES ABrel(f, g)(aa)(b)
theorem ABrel_Arel_equiv : ∀ (b : B) (a : A) (aa : A), (¬ preim_B_p f(b)) ∧ ABrel f g(a) (b) ∧ Arel f g(a) (aa)
 ∧ injective_p f ∧ injective_p g → ABrel f g(aa) (b) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABrel_Brel_equiv
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b, bb: B, a: A):
--        (NOT preim_B?(f)(b)) AND ABrel(f, g)(a)(b) AND Brel(f, g)(b)(bb)
--    AND injective?(f) AND injective?(g)
--    IMPLIES BArel(f, g)(bb)(a)
theorem ABrel_Brel_equiv : ∀ (b : B) (bb : B) (a : A), (¬ preim_B_p f(b)) ∧ ABrel f g(a) (b) ∧ Brel f g(b) (bb)
 ∧ injective_p f ∧ injective_p g → BArel f g(bb) (a) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Brel_Arel
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b, bb: B):
--   injective?(g) IMPLIES (Brel(f, g)(b)(bb) IFF Arel(f, g)(g(b))(g(bb)))
theorem Brel_Arel : ∀ (b : B) (bb : B), injective_p g → (Brel f g(b) (bb) ↔ Arel f g(g b) (g bb)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Arel_Brel
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a, aa: A):
--   injective?(f) IMPLIES (Arel(f, g)(a)(aa) = Brel(f, g)(f(a))(f(aa)))
theorem Arel_Brel : ∀ (a : A) (aa : A), injective_p f → (Arel f g(a) (aa) = Brel f g(f a) (f aa)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABrel_Brel
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B, a: A):
--   injective?(f) AND injective?(g) IMPLIES
--    (ABrel(f, g)(a)(b) IFF Brel(f, g)(f(a))(b))
theorem ABrel_Brel : ∀ (b : B) (a : A), injective_p f ∧ injective_p g → (ABrel f g(a) (b) ↔ Brel f g(f a) (b)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Afununique
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a1, a2: A, i, j: nat):
--   injective?(f) AND injective?(g) AND Afun(f, g)(a1)(i) = Afun(f, g)(a2)(j)
--    IMPLIES Arel(f, g)(a1)(a2)
theorem Afununique : ∀ (a1 : A) (a2 : A) (i : {i : ℝ // i ≥ 0}) (j : {i : ℝ // i ≥ 0}), injective_p f ∧ injective_p g ∧ Afun f g(a1) (i) = Afun f g(a2) (j) → Arel f g(a1) (a2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.af_fun
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA (an: (Arel(f, g)(a))): f(an))
axiom af_fun {pvs_τ25 : Type*} {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} : pvs_τ25 → pvs_τ26 → pvs_τ27 → pvs_τ28

-- pvs2lean: cantor_bernstein_schroeder.ag_fun
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA (bn: (ABrel(f, g)(a))): g(bn))
axiom ag_fun {pvs_τ29 : Type*} {pvs_τ30 : Type*} {pvs_τ31 : Type*} {pvs_τ32 : Type*} : pvs_τ29 → pvs_τ30 → pvs_τ31 → pvs_τ32

-- pvs2lean: cantor_bernstein_schroeder.aginj
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a: A):
--   injective?(g) AND injective?(f) IMPLIES
--    bijective?(ag_fun(f, g)(a)) OR bijective?(af_fun(f, g)(a))
theorem aginj : ∀ (a : A), injective_p g ∧ injective_p f → bijective_p (ag_fun f g(a)) ∨ bijective_p (af_fun f g(a)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Arel_union
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a: A): EXISTS (aa: A): Arel(f, g)(aa)(a)
theorem Arel_union : ∀ (a : A), ∃ (aa : A), Arel f g aa a := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Arel_disjoint
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a1, a2, a: A):
--   Arel(f, g)(a1)(a) AND
--    Arel(f, g)(a2)(a) AND injective?(g) AND injective?(f)
--    IMPLIES Arel(f, g)(a1) = Arel(f, g)(a2)
theorem Arel_disjoint : ∀ (a1 : A) (a2 : A) (a : A), Arel f g(a1) (a) ∧ Arel f g(a2) (a) ∧ injective_p g ∧ injective_p f → Arel f g(a1) = Arel f g(a2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Brel_disjoint
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b1, b2, b: B):
--   Brel(f, g)(b1)(b) AND
--    Brel(f, g)(b2)(b) AND injective?(g) AND injective?(f)
--    IMPLIES Brel(f, g)(b1) = Brel(f, g)(b2)
theorem Brel_disjoint : ∀ (b1 : B) (b2 : B) (b : B), Brel f g(b1) (b) ∧ Brel f g(b2) (b) ∧ injective_p g ∧ injective_p f → Brel f g(b1) = Brel f g(b2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABrel_union
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (b: B): EXISTS (a: A): ABrel(f, g)(a)(b)
theorem ABrel_union : ∀ (b : B), ∃ (a : A), ABrel f g a b := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.ABrel_disjoint
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (a1, a2: A, b: B):
--   ABrel(f, g)(a1)(b) AND
--    ABrel(f, g)(a2)(b) AND injective?(g) AND injective?(f)
--    IMPLIES ABrel(f, g)(a1) = ABrel(f, g)(a2)
theorem ABrel_disjoint : ∀ (a1 : A) (a2 : A) (b : B), ABrel f g(a1) (b) ∧
 ABrel f g(a2) (b) ∧ injective_p g ∧ injective_p f → ABrel f g(a1) = ABrel f g(a2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cantor_bernstein_schroeder.Cantor_Bernstein_Schroeder
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: injective?(f) AND injective?(g) IMPLIES EXISTS (hab): bijective?(hab)
theorem Cantor_Bernstein_Schroeder : injective_p f ∧ injective_p g → ∃ (hab : _), bijective_p hab := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.cantor_bernstein_schroeder