-- Auto-generated by pvs2lean/translator.py
-- PVS theory: infinite_card
-- PVSLib library: sets_aux
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: infinite_card

Auto-generated stubs from PVSLib theory `infinite_card`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.infinite_card

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (card_eq : pvs_τ1 → pvs_τ2 → pvs_τ3)
variable {pvs_τ4 : Type*} {pvs_τ5 : Type*} (card_ge : pvs_τ4 → pvs_τ5 → Prop)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (card_le : pvs_τ6 → pvs_τ7 → Prop)
variable {pvs_τ8 : Type*} (is_finite : pvs_τ8 → Prop)

-- pvs2lean: infinite_card.finite_card_eq
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_eq(S1, S2) => (is_finite(S1) IFF is_finite(S2))
theorem finite_card_eq : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_eq S1 S2 → (is_finite S1 ↔ is_finite S2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: infinite_card.infinite_card_eq
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_eq(S1, S2) => (NOT is_finite(S1) IFF NOT is_finite(S2))
theorem infinite_card_eq : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_eq S1 S2 → (¬ is_finite S1 ↔ ¬ is_finite S2) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: infinite_card.infinite_card_le
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_le(S1, S2) AND NOT is_finite(S1) => NOT is_finite(S2)
theorem infinite_card_le : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_le S1 S2 ∧ ¬ is_finite S1 → ¬ is_finite S2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: infinite_card.infinite_card_ge
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_ge(S1, S2) AND NOT is_finite(S2) => NOT is_finite(S1)
theorem infinite_card_ge : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_ge S1 S2 ∧ ¬ is_finite S2 → ¬ is_finite S1 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: infinite_card.finite_card_le
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_le(S1, S2) AND is_finite(S2) => is_finite(S1)
theorem finite_card_le : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_le S1 S2 ∧ is_finite S2 → is_finite S1 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: infinite_card.finite_card_ge
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S1, S2: card_ge(S1, S2) AND is_finite(S1) => is_finite(S2)
theorem finite_card_ge : ∀ (S1 : T1 → Bool) (S2 : T2 → Bool), card_ge S1 S2 ∧ is_finite S1 → is_finite S2 := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.infinite_card