-- Auto-generated by pvs2lean/translator.py
-- PVS theory: finite_below
-- PVSLib library: orders
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: finite_below

Auto-generated stubs from PVSLib theory `finite_below`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.finite_below

noncomputable section

variable {pvs_τ1 : Type*} (bijective_p : pvs_τ1 → Prop)
variable {pvs_τ2 : Type*} (card : pvs_τ2 → Prop)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} (least : pvs_τ7 → pvs_τ8 → pvs_τ9)
variable {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} (least_p : pvs_τ10 → pvs_τ11 → pvs_τ12 → Prop)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} (left_inverse_p : pvs_τ13 → pvs_τ14 → Prop)
variable {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} {pvs_τ21 : Type*} (preserves : pvs_τ18 → pvs_τ19 → pvs_τ20 → pvs_τ21)
variable {pvs_τ22 : Type*} {pvs_τ23 : Type*} (reflexive_closure : pvs_τ22 → pvs_τ23)
variable {pvs_τ24 : Type*} {pvs_τ25 : Type*} {pvs_τ26 : Type*} (remove : pvs_τ24 → pvs_τ25 → pvs_τ26)
variable {pvs_τ27 : Type*} {pvs_τ28 : Type*} (right_inverse_p : pvs_τ27 → pvs_τ28 → Prop)
variable {pvs_τ29 : Type*} (surjective_p : pvs_τ29 → Prop)

-- pvs2lean: finite_below.nth
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF n = 0 THEN least(reflexive_closure(<))(S)
-- ELSE nth(remove(least(reflexive_closure(<))(S), S), <)(n - 1)
-- ENDIF
axiom nth {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} : pvs_τ15 → pvs_τ16 → pvs_τ17 → Prop

-- pvs2lean: finite_below.nth_one_step
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <, (n: below[card(S)]):
--   n + 1 < card(S) IMPLIES nth(S, <)(n) < nth(S, <)(n + 1)
theorem nth_one_step : ∀ (S : T → Bool) (< : T × T → Bool) (n : {s : {i : ℝ // i ≥ 0} // s < card S}), n + 1 < card S → nth S <(n) < nth S <(n + 1) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: finite_below.nth_monotonic
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <:
--   preserves(nth(S, <),
--             restrict
--                 [[real, real], [below[card[T](S)], below[card[T](S)]], bool]
--                 (reals.<),
--             <)
theorem nth_monotonic : ∀ (S : T → Bool) (< : T × T → Bool), preserves (nth S <) (restrict
     (reals.<)) < := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: finite_below.nth_surjective
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <: surjective?(nth(S, <))
theorem nth_surjective : ∀ (S : T → Bool) (< : T × T → Bool), surjective_p (nth S <) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: finite_below.index
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF least?(t, S, reflexive_closure(<)) THEN 0
-- ELSE 1 + index(remove(least(reflexive_closure(<))(S), S), <)(t)
-- ENDIF
axiom index {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ3 → pvs_τ4 → pvs_τ5 → pvs_τ6

-- pvs2lean: finite_below.index_monotonic
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <:
--   preserves(index(S, <), restrict[[T, T], [(S), (S)], bool](<), reals.<)
theorem index_monotonic : ∀ (S : T → Bool) (< : T × T → Bool), preserves (index S <) (restrict <) reals.< := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: finite_below.index_nth_left_inverse
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <: left_inverse?(nth(S, <), index(S, <))
theorem index_nth_left_inverse : ∀ (S : T → Bool) (< : T × T → Bool), left_inverse_p (nth S <) (index S <) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: finite_below.index_nth_right_inverse
-- pvs_status: unproved  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL S, <: right_inverse?(nth(S, <), index(S, <))
theorem index_nth_right_inverse : ∀ (S : T → Bool) (< : T × T → Bool), right_inverse_p (nth S <) (index S <) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.finite_below