-- Auto-generated by pvs2lean/translator.py
-- PVS theory: sigma_3D
-- PVSLib library: vectors
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: sigma_3D

Auto-generated stubs from PVSLib theory `sigma_3D`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.sigma_3D

noncomputable section

variable {pvs_τ2 : Type*} {pvs_τ3 : Type*} (const_vec : pvs_τ2 → pvs_τ3)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} (subrange : pvs_τ7 → pvs_τ8 → pvs_τ9)

-- pvs2lean: sigma_3D.T_pred
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom T_pred {pvs_τ1 : Type*} : pvs_τ1 → Prop

-- pvs2lean: sigma_3D.connected_domain
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem connected_domain : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.T_low?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def T_low_p : sorry := by
  sorry  -- pvs2lean: definition stub for {i: int | EXISTS (j: T): j <= i}

-- pvs2lean: sigma_3D.T_high?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def T_high_p : sorry := by
  sorry  -- pvs2lean: definition stub for {i: int | EXISTS (j: T): i <= j}

-- pvs2lean: sigma_3D.T_pred_lem
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem T_pred_lem : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.high_low_rewrite
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem high_low_rewrite : True := by
  -- === TCCs for high_low_rewrite ===
  -- TCC: high_low_rewrite_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   NOT high < low IMPLIES
  --    FORALL (n: subrange(low, high)): T_pred(n) OR EXISTS (j: T): n <= j
  have high_low_rewrite_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: high_low_rewrite_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   NOT high < low IMPLIES
  --    FORALL (n: subrange(low, high)): T_pred(n) OR EXISTS (j: T): n <= j
  have high_low_rewrite_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
noncomputable def sigma : sorry := by
  sorry  -- pvs2lean: definition stub for IF low > high THEN zero ELSE F(high) + sigma(low, high - 1, F) ENDIF

-- pvs2lean: sigma_3D.sigma_rew
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_rew : True := by
  -- === TCCs for sigma_rew ===
  -- TCC: sigma_rew_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high = low AND NOT low > high IMPLIES T_pred(low)
  have sigma_rew_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_rew_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high = low AND NOT low > high IMPLIES T_pred(low)
  have sigma_rew_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_spl
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_spl : True := by
  -- === TCCs for sigma_spl ===
  -- TCC: sigma_spl_TCC1
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn + rng) OR EXISTS (j: T): low + nn + rng <= j
  have sigma_spl_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_spl_TCC2
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn) OR EXISTS (j: T): low + nn <= j
  have sigma_spl_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_spl_TCC3
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn + 1) OR EXISTS (j: T): j <= low + nn + 1
  have sigma_spl_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_spl_TCC1
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn + rng) OR EXISTS (j: T): low + nn + rng <= j
  have sigma_spl_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_spl_TCC2
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn) OR EXISTS (j: T): low + nn <= j
  have sigma_spl_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_spl_TCC3
  -- Statement: FORALL (low: T_low, nn, rng: nat):
  --   T_pred(low + nn + rng) IMPLIES
  --    T_pred(low + nn + 1) OR EXISTS (j: T): j <= low + nn + 1
  have sigma_spl_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_split
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_split : True := by
  -- === TCCs for sigma_split ===
  -- TCC: sigma_split_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   z <= high AND low - 1 <= z IMPLIES T_pred(z) OR EXISTS (j: T): z <= j
  have sigma_split_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_split_TCC2
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   z <= high AND low - 1 <= z IMPLIES
  --    T_pred(z + 1) OR EXISTS (j: T): j <= z + 1
  have sigma_split_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_split_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   z <= high AND low - 1 <= z IMPLIES T_pred(z) OR EXISTS (j: T): z <= j
  have sigma_split_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_split_TCC2
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   z <= high AND low - 1 <= z IMPLIES
  --    T_pred(z + 1) OR EXISTS (j: T): j <= z + 1
  have sigma_split_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_diff
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_diff : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_diff_neg
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_diff_neg : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_eq_arg
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_eq_arg : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_first
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_first : True := by
  -- === TCCs for sigma_first ===
  -- TCC: sigma_first_TCC1
  -- Statement: FORALL (high: T_high, low: T_low): high >= low IMPLIES T_pred(low)
  have sigma_first_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_first_TCC2
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high >= low IMPLIES T_pred(low + 1) OR EXISTS (j: T): j <= low + 1
  have sigma_first_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_first_TCC1
  -- Statement: FORALL (high: T_high, low: T_low): high >= low IMPLIES T_pred(low)
  have sigma_first_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_first_TCC2
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high >= low IMPLIES T_pred(low + 1) OR EXISTS (j: T): j <= low + 1
  have sigma_first_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_last
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_last : True := by
  -- === TCCs for sigma_last ===
  -- TCC: sigma_last_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high >= low IMPLIES T_pred(high - 1) OR EXISTS (j: T): high - 1 <= j
  have sigma_last_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_last_TCC2
  -- Statement: FORALL (high: T_high, low: T_low): high >= low IMPLIES T_pred(high)
  have sigma_last_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_last_TCC1
  -- Statement: FORALL (high: T_high, low: T_low):
  --   high >= low IMPLIES T_pred(high - 1) OR EXISTS (j: T): high - 1 <= j
  have sigma_last_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_last_TCC2
  -- Statement: FORALL (high: T_high, low: T_low): high >= low IMPLIES T_pred(high)
  have sigma_last_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_middle
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_middle : True := by
  -- === TCCs for sigma_middle ===
  -- TCC: sigma_middle_TCC1
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i >= low AND high >= i IMPLIES T_pred(i - 1) OR EXISTS (j: T): i - 1 <= j
  have sigma_middle_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_middle_TCC2
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i >= low AND high >= i IMPLIES T_pred(i + 1) OR EXISTS (j: T): j <= i + 1
  have sigma_middle_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_middle_TCC1
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i >= low AND high >= i IMPLIES T_pred(i - 1) OR EXISTS (j: T): i - 1 <= j
  have sigma_middle_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_middle_TCC2
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i >= low AND high >= i IMPLIES T_pred(i + 1) OR EXISTS (j: T): j <= i + 1
  have sigma_middle_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_const
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_const : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_zero
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_zero : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_scal
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_scal : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_shift_T
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_shift_T : True := by
  -- === TCCs for sigma_shift_T ===
  -- TCC: sigma_shift_T_TCC1
  -- Statement: FORALL (low: T_low, z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES
  --    T_pred(low + z) OR EXISTS (j: T): j <= low + z
  have sigma_shift_t_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T_TCC2
  -- Statement: FORALL (high: T_high, z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES
  --    T_pred(high + z) OR EXISTS (j: T): high + z <= j
  have sigma_shift_t_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T_TCC3
  -- Statement: FORALL (z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES FORALL (i: T): T_pred(i + z)
  have sigma_shift_t_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T_TCC1
  -- Statement: FORALL (low: T_low, z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES
  --    T_pred(low + z) OR EXISTS (j: T): j <= low + z
  have sigma_shift_t_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T_TCC2
  -- Statement: FORALL (high: T_high, z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES
  --    T_pred(high + z) OR EXISTS (j: T): high + z <= j
  have sigma_shift_t_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T_TCC3
  -- Statement: FORALL (z: int):
  --   (FORALL (i: T): T_pred(i + z)) IMPLIES FORALL (i: T): T_pred(i + z)
  have sigma_shift_t_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_shift_T2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_shift_T2 : True := by
  -- === TCCs for sigma_shift_T2 ===
  -- TCC: sigma_shift_T2_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   T_pred(high + z) AND T_pred(low + z) IMPLIES
  --    T_pred(low + z) OR EXISTS (j: T): j <= low + z
  have sigma_shift_t2_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T2_TCC2
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   T_pred(high + z) AND T_pred(low + z) IMPLIES
  --    T_pred(high + z) OR EXISTS (j: T): high + z <= j
  have sigma_shift_t2_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T2_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   T_pred(high + z) AND T_pred(low + z) IMPLIES
  --    T_pred(low + z) OR EXISTS (j: T): j <= low + z
  have sigma_shift_t2_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_shift_T2_TCC2
  -- Statement: FORALL (high: T_high, low: T_low, z: int):
  --   T_pred(high + z) AND T_pred(low + z) IMPLIES
  --    T_pred(high + z) OR EXISTS (j: T): high + z <= j
  have sigma_shift_t2_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_sum
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_sum : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_minus
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_minus : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.restrict
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom restrict {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ4 → pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: sigma_3D.sigma_restrict
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_restrict : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_restrict_to
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_restrict_to : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_restrict_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_restrict_eq : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_eq : True := by
  -- === TCCs for sigma_eq ===
  -- TCC: sigma_eq_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, n: subrange(low, high)): T_pred(n)
  have sigma_eq_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sigma_eq_TCC1
  -- Statement: FORALL (high: T_high, low: T_low, n: subrange(low, high)): T_pred(n)
  have sigma_eq_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sigma_with
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sigma_with : True := by
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sum_it_def
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom sum_it_def {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} : pvs_τ14 → pvs_τ15 → pvs_τ16 → pvs_τ17 → pvs_τ18

-- pvs2lean: sigma_3D.sum_it
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
axiom sum_it {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} : pvs_τ10 → pvs_τ11 → pvs_τ12 → pvs_τ13

-- pvs2lean: sigma_3D.sum_it_prop
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sum_it_prop : True := by
  -- === TCCs for sum_it_prop ===
  -- TCC: sum_it_prop_TCC1
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i <= high AND low - 1 <= i IMPLIES
  --    T_pred(i + 1) OR EXISTS (j: T): j <= i + 1
  have sum_it_prop_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: sum_it_prop_TCC1
  -- Statement: FORALL (high: T_high, i: T, low: T_low):
  --   i <= high AND low - 1 <= i IMPLIES
  --    T_pred(i + 1) OR EXISTS (j: T): j <= i + 1
  have sum_it_prop_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: sigma_3D.sum_it_sigma
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem sum_it_sigma : True := by
  sorry  -- needs_human: automated tactics exhausted

end

end NavierStokesClean.PVSLib.sigma_3D