-- Auto-generated by pvs2lean/translator.py
-- PVS theory: sigma_fseq_3D
-- PVSLib library: vectors
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: sigma_fseq_3D

Auto-generated stubs from PVSLib theory `sigma_fseq_3D`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.sigma_fseq_3D

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (seq : pvs_τ1 → pvs_τ2)

-- pvs2lean: sigma_fseq_3D.sigma
-- pvs_status: definition  lean_tactic_class: mathlib_exact
-- stmt_confidence: high  [ast]
-- pvs_stmt: sigma(0, fs`length - 1, (LAMBDA (n: nat): fs`seq(n)))
noncomputable def sigma : sorry := by
  sorry  -- pvs2lean: definition stub for sigma(0, fs`length - 1, (LAMBDA (n: nat): fs`seq(n)))

end

end NavierStokesClean.PVSLib.sigma_fseq_3D