import CATEPTMain.Integration.AdSCFTHeadrick1907Bridge
import Mathlib
/-!
# Replica Trick Bridge (Headrick 1907.08126)

Bridge for Eq. (2.40) and the replica-limit route to von Neumann entropy
used throughout sections 4–5 of arXiv:1907.08126v1.

This module does **not** claim the analytic continuation proof; it provides
typed obligations so later phases can attach field-theoretic / geometric
arguments without changing theorem signatures.
-/

set_option autoImplicit false

namespace CATEPTMain.Integration.AdSCFT.Headrick1907

/-- Input data for a replica-trick entropy derivation. -/
structure ReplicaTraceData where
  /-- The moment function `α ↦ Tr(ρ^α)` (real-valued proxy). -/
  trRhoPow : ℝ → ℝ
  /-- Positivity needed for `log`. -/
  trRhoPow_pos : ∀ α : ℝ, 0 < trRhoPow α
  /-- Normalization at `α=1`: `Tr(ρ)=1`. -/
  trRhoPow_one : trRhoPow 1 = 1
  /-- Regularity requirement near `α=1` used by the continuation lane. -/
  analyticNearOne : ContinuousAt trRhoPow 1

/-- Rényi entropy generated by replica moments (Eq. 2.40 proxy). -/
noncomputable def renyiFromReplica (R : ReplicaTraceData) (α : ℝ) : ℝ :=
  renyiEntropyFormula α (R.trRhoPow α)

/-- Target von Neumann entropy extracted via `α→1` continuation. -/
noncomputable def vonNeumannFromReplica (R : ReplicaTraceData) : ℝ :=
  sInf {s : ℝ | ∃ α : ℝ, α ≠ 1 ∧ s = renyiFromReplica R α}

/-- Phase-2 obligation: replica-limit exists and matches von Neumann entropy. -/
def ReplicaLimitContract (R : ReplicaTraceData) (S_vN : ℝ) : Prop :=
  ContinuousAt R.trRhoPow 1 ∧
  Filter.Tendsto (fun α : ℝ => renyiFromReplica R α)
    (nhdsWithin (1 : ℝ) {x : ℝ | x ≠ 1}) (nhds S_vN)

/-- Convenience theorem: if the contract is provided, the limit statement is
available in Lean form immediately. -/
theorem replica_limit_from_contract
    (R : ReplicaTraceData) (S_vN : ℝ) (h : ReplicaLimitContract R S_vN) :
    Filter.Tendsto (fun α : ℝ => renyiFromReplica R α)
      (nhdsWithin (1 : ℝ) {x : ℝ | x ≠ 1}) (nhds S_vN) :=
  h.2

/-- Hermitian/normalized sanity check at α=1 for the trace proxy. -/
theorem renyi_trace_normalized_at_one (R : ReplicaTraceData) :
    R.trRhoPow 1 = 1 :=
  R.trRhoPow_one

/-- Positivity ensures the Rényi expression is well-typed away from `α=1`. -/
theorem renyiFromReplica_welltyped
    (R : ReplicaTraceData) (α : ℝ) :
    0 < R.trRhoPow α :=
  R.trRhoPow_pos α

end CATEPTMain.Integration.AdSCFT.Headrick1907
