import CATEPTMain.CATEPT.CATEPT.CATEPTPrelude
import CATEPTMain.CATEPT.CATEPT.AQFTFoundations
import CATEPTMain.Integration.ComplexTimePathIntegralCarrier
import CATEPTMain.Integration.OpenSystemMasterEquationCarrier
import CATEPTMain.Integration.TensorNetworkPathIntegralCarrier

import CATEPTMain.Analysis.BanachSteinhaus
import CATEPTMain.Analysis.ODE.MatricesForODEsBridge
import CATEPTMain.CATEPT.CATEPT.AdvancedFoundations
import CATEPTMain.CATEPT.CATEPT.Basic
import CATEPTMain.CATEPT.CATEPT.BellCHSHBohmCoreAbstractions
import CATEPTMain.CATEPT.CATEPT.CATEPTPredictions
import CATEPTMain.CATEPT.CATEPT.CAT_EPT_ETH_VariationalRateBridge
import CATEPTMain.CATEPT.CATEPT.CatsimCFLBridge
import CATEPTMain.CATEPT.CATEPT.CatsimEntropicTimeBridge
import CATEPTMain.CATEPT.CATEPT.ClassicalETHIntegration
import CATEPTMain.CATEPT.CATEPT.DecoherencePredictions
import CATEPTMain.CATEPT.CATEPT.FeynmanDiagramAlgebra
import CATEPTMain.CATEPT.CATEPT.FoundationalSwapArchitecture
import CATEPTMain.CATEPT.CATEPT.FundamentalInteractionsCoreBridge
import CATEPTMain.CATEPT.CATEPT.GammaSandwichBridge
import CATEPTMain.CATEPT.CATEPT.KolmogorovCoreAbstractions
import CATEPTMain.CATEPT.CATEPT.LoopIntegralBridge
import CATEPTMain.CATEPT.CATEPT.LoopIntegrationReduction
import CATEPTMain.CATEPT.CATEPT.MeasurementCommunicationCoreAbstractions
import CATEPTMain.CATEPT.CATEPT.OriginCoreBridge
import CATEPTMain.CATEPT.CATEPT.PathIntegralMeasureContracts
import CATEPTMain.CATEPT.CATEPT.PerturbativeExpansionBridge
import CATEPTMain.CATEPT.CATEPT.QFTGRClosures
import CATEPTMain.CATEPT.CATEPT.ScatteringAmplitudeBridge
import CATEPTMain.CATEPT.CATEPT.TemporalOrderAndReduction
import CATEPTMain.CATEPT.CATEPT.TheoryPluginAdapterFacade
import CATEPTMain.CATEPT.CATEPT.TheoryPluginAdapterFacadeExamples
import CATEPTMain.CATEPT.CATEPT.TheoryPluginDimCategoryCore
import CATEPTMain.CATEPT.CATEPT.TheoryPluginExamples
import CATEPTMain.CATEPT.CATEPT.TrefoilTopologyBridge
import CATEPTMain.CATEPT.CATEPT.UniversalScalingLaw
import CATEPTMain.Core.CATEPTAbstract
import CATEPTMain.Core.CATEPTAbstractInstances
import CATEPTMain.Domains.Adapters.Herglotz
import CATEPTMain.Domains.Adapters.Higgs
import CATEPTMain.Domains.Adapters.Kinetic
import CATEPTMain.Domains.CoherenceShowcase
import CATEPTMain.Domains.SubstrateProjections
import CATEPTMain.Domains.SuperiorMethodAssumptionTags
import CATEPTMain.Domains.TemporalSynchronization
import CATEPTMain.Domains.UnifiedConstraints
import CATEPTMain.Domains.UnifiedConstraintsCoupling
import CATEPTMain.Domains.UnifiedConstraintsEMDuality
import CATEPTMain.Domains.UnifiedConstraintsSubstrate
import CATEPTMain.Geometry.NoFTL.WORKLOG
import CATEPTMain.Hammer.HammerDemo
import CATEPTMain.Integration.BPHZForestLadder
import CATEPTMain.Integration.BochnerMinlosCylinderBridge
import CATEPTMain.Integration.BounceStationarity
import CATEPTMain.Integration.CATEPTMeasureTheorem
import CATEPTMain.Integration.CATEPTNSDivCurl
import CATEPTMain.Integration.CATEPTNSGNEmbedding
import CATEPTMain.Integration.CATEPTSTAdapter
import CATEPTMain.Integration.CATEPTSelfConsistency
import CATEPTMain.Integration.CATEPTSheafCoarseGrainingBridge
import CATEPTMain.Integration.CATEPTSheafGluingPhase2
import CATEPTMain.Integration.CKBirkhoffLadder
import CATEPTMain.Integration.CanonicalEntropicModel
import CATEPTMain.Integration.CarlesonHarmonicAnalysisBridge
import CATEPTMain.Integration.ColemanCallanDiluteGas
import CATEPTMain.Integration.ComplexWeightNormEntropicDamping
import CATEPTMain.Integration.ConcreteSubstrateExample
import CATEPTMain.Integration.ConnesKreimerAntipode
import CATEPTMain.Integration.ConnesKreimerLadder
import CATEPTMain.Integration.ConstructorInformationSubstrate
import CATEPTMain.Integration.ContactDynamicsCAT
import CATEPTMain.Integration.ContinuousEntropicUncertaintyCarrier
import CATEPTMain.Integration.CountertermFreeAbsoluteConvergence
import CATEPTMain.Integration.CslibComputabilityBridge
import CATEPTMain.Integration.CutkoskyBranchCut
import CATEPTMain.Integration.CutkoskyDiscontinuity
import CATEPTMain.Integration.DeGiorgiHarnackHolderRegularityBridge
import CATEPTMain.Integration.EntropicActionPositivity
import CATEPTMain.Integration.EntropicCoercivityFromFisherInformation
import CATEPTMain.Integration.EntropicCoercivityFromModularHamiltonian
import CATEPTMain.Integration.EntropicGreenFunctionBridge
import CATEPTMain.Integration.FeynmanDiagrams
import CATEPTMain.Integration.FisherRaoLawvereAssumptionTags
import CATEPTMain.Integration.FivePaperUnifiedHierarchy
import CATEPTMain.Integration.FoundationsAssumptionTags
import CATEPTMain.Integration.FreeParticleAction
import CATEPTMain.Integration.FreeParticlePropagator
import CATEPTMain.Integration.FreeParticlePropagatorNFold
import CATEPTMain.Integration.FreeParticleSaddle
import CATEPTMain.Integration.FujikawaCATEPTBridge
import CATEPTMain.Integration.GelfandYaglomAsymptotics
import CATEPTMain.Integration.GelfandYaglomDeriv
import CATEPTMain.Integration.GelfandYaglomDetRatio
import CATEPTMain.Integration.GelfandYaglomInversionAPI
import CATEPTMain.Integration.GelfandYaglomJacobi
import CATEPTMain.Integration.GeneratingFunctionalCalculus
import CATEPTMain.Integration.GoalsABPhase3Closures
import CATEPTMain.Integration.GreenDampingUVChainMultimode
import CATEPTMain.Integration.HeatIntegralEntropicTime
import CATEPTMain.Integration.HeatSemigroupLaw
import CATEPTMain.Integration.HigherDegreeLatticeAction
import CATEPTMain.Integration.HigherDegreeT3Tail
import CATEPTMain.Integration.HigherDegreeT3TailSharp
import CATEPTMain.Integration.HopfYangBaxterBridge
import CATEPTMain.Integration.InstantonTunneling
import CATEPTMain.Integration.KolmogorovChaitinIncompressibilityBridge
import CATEPTMain.Integration.LogSobolevEntropicProperTimeBridge
import CATEPTMain.Integration.MixedBracketCompatibilityPhase2
import CATEPTMain.Integration.MultiModeGaussianCompletion
import CATEPTMain.Integration.OneLoopBPHZCubic
import CATEPTMain.Integration.OneLoopBPHZOnShell
import CATEPTMain.Integration.OscillatorKernel
import CATEPTMain.Integration.PathIntegralBenchmarksBridge
import CATEPTMain.Integration.PerturbativeApproximationCarrier
import CATEPTMain.Integration.PhyslibCrossDomainBridge
import CATEPTMain.Integration.PhyslibTemporalAdapterBridge
import CATEPTMain.Integration.PowerHierarchyCarrier
import CATEPTMain.Integration.RelativisticEntropicGeometryFoundationsAudit
import CATEPTMain.Integration.RenormalizationGroup
import CATEPTMain.Integration.RigorousComplexFeynmanKac
import CATEPTMain.Integration.SchwingerSourceShift
import CATEPTMain.Integration.ShiftedHeatIntegral
import CATEPTMain.Integration.SimplexPathIntegralNoRenormBridgeMulti
import CATEPTMain.Integration.SourcedHeatIntegral
import CATEPTMain.Integration.SpectralPhysicsAssumptionTags
import CATEPTMain.Integration.SpectralTermHeatModeBridge
import CATEPTMain.Integration.StokesEntropicModel
import CATEPTMain.Integration.StringWorldsheetTemporalBridge
import CATEPTMain.Integration.SubstrateAssumptionTags
import CATEPTMain.Integration.SubstrateBellBridge
import CATEPTMain.Integration.T3PhysicalEntropicModel
import CATEPTMain.Integration.TopologicalChargeCohomology
import CATEPTMain.Integration.TopologicalChargeIntegrality
import CATEPTMain.Integration.UVCertificateFailureModes
import CATEPTMain.Integration.VMLEntropicEquilibriumBridge
import CATEPTMain.Integration.YamasakiInternalClockBridge
import CATEPTMain.Probability.ConcentrationInequalitiesBridge
import CATEPTMain.Transforms.LaplaceTransformBridge
import CATEPTMain.Units.PhysicalQuantitiesBridge
/-!
# FoundationsOrphanBundle — Option B spine-recovery bundle for CAT/EPT
foundations / generic carriers

Wires the substantive previously-orphan CAT/EPT-foundation modules
(prelude, AQFT axioms, temporal-order machinery, generic path-
integral carriers) onto the root-reachable spine.

## Modules wired (5)

* `CATEPTPrelude` — central CAT/EPT prelude (14 thm, 4 struct).
* `AQFTFoundations` — Haag–Kastler/Wightman-style AQFT foundations (5 thm, 6 struct).
* `ComplexTimePathIntegralCarrier` — Wick-rotation complex-time contour (10 thm, 7 struct).
* `OpenSystemMasterEquationCarrier` — Lindbladian / open-system master eq (11 thm, 6 struct).
* `TensorNetworkPathIntegralCarrier` — tensor-network compressed path integral (11 thm, 5 struct).

`TemporalOrderAndReduction` was deferred — it ships its own
`PhysicalConstants` structure that collides with the canonical
`PhysicalConstantsCommon` (T101). Wiring it requires a refactor to
re-use the canonical definition; tracked separately.

Tracked by worklog task `catept_spine_orphan_triage_audit_20260503`.
-/
namespace CATEPTMain.Integration.FoundationsOrphanBundle
end CATEPTMain.Integration.FoundationsOrphanBundle
