import CATEPTMain.Integration.KMSModularParameterBridge
import CATEPTMain.Integration.KMSVacuumInvarianceBridge

/-!
# KMSStripVacuumBridge — KMS strip width ↔ Logos vacuum-state invariance

Wires `KMSModularParameterBridge.IdentifyKMSStripWithEntropicProperTime`
to `KMSVacuumInvarianceBridge` (and through it to Logos's proven theorem
`Tomita.vacuumState_modular_invariant`), replacing the abstract
"KMS strip width = entropic proper time" hypothesis with one grounded
in the operator-algebraic stationarity of the vacuum state under the
modular flow.

## What gets identified

* `IdentifyKMSStripWithEntropicProperTime.tauEnt` (the "catept-model
  entropic proper time") = `KMSVacuumInvarianceBridge.channel.tauEnt`
  (the reduced modular channel's `τ_ent`), at every `t`.
* The vacuum-state invariance `ω(σ_t a) = ω(a)` justifies that the
  identification is well-posed: the modular flow generated by `K_O`
  (whose imaginary-time period is the KMS strip width) leaves the
  reference state stationary.

## What this module ships

* `KMSStripVacuumBridge` — pairs the two carriers with a pointwise
  equality field on `τ_ent`.
* `tauEnt_strip_vacuum_consistent` — the channel's `τ_ent` equals the
  KMS-bridge's `τ_ent` at every `t`.
* `kms_strip_vacuum_bundle` — capstone existence theorem.
-/

set_option autoImplicit false

noncomputable section

namespace CATEPTMain.Integration.KMSStripVacuumBridge

open CATEPTMain.Integration.KMSVacuumInvarianceBridge
open CATEPTMain.Integration.KMSModularParameterBridge

variable (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- **KMS strip ↔ vacuum-invariance bridge.**

Identifies the `τ_ent` exposed by `IdentifyKMSStripWithEntropicProperTime`
with the channel's `τ_ent` from the `KMSVacuumInvarianceBridge`. The
operator-algebraic backing is Logos's `vacuumState_modular_invariant`.

The bridge documents the consistency between two CAT/EPT layers:

* the **dissipation-rate / strip-width** layer
  (`KMSModularParameterBridge`),
* the **modular-flow / vacuum-state** layer
  (`KMSVacuumInvarianceBridge`, sourced from Logos). -/
structure KMSStripVacuumBridge where
  /-- The KMS-strip / entropic-proper-time identification carrier
  (catept-main, `KMSModularParameterBridge`). -/
  stripBridge      : IdentifyKMSStripWithEntropicProperTime
  /-- The vacuum-state invariance bridge (this folder). -/
  vacuumBridge     : KMSVacuumInvarianceBridge H
  /-- **Pointwise consistency** of the two `τ_ent` exposures. -/
  tauEnt_consistent :
      ∀ t : ℝ, stripBridge.tauEnt t = vacuumBridge.channel.tauEnt t

namespace KMSStripVacuumBridge

variable {H} (B : KMSStripVacuumBridge H)

/-- **Extraction.** The `τ_ent` exposed by the KMS-strip bridge equals
the reduced modular channel's `τ_ent` at every `t`. -/
theorem tauEnt_strip_vacuum_consistent (t : ℝ) :
    B.stripBridge.tauEnt t = B.vacuumBridge.channel.tauEnt t :=
  B.tauEnt_consistent t

/-- **Composition with strip-bridge identity:** the channel's `τ_ent` at
`t` equals the KMS strip width `kmsStripWidth gammaI t`. -/
theorem channel_tauEnt_eq_stripWidth (t : ℝ) :
    B.vacuumBridge.channel.tauEnt t
    = kmsStripWidth B.stripBridge.gammaI t := by
  rw [← B.tauEnt_consistent t, B.stripBridge.tauEnt_eq_kmsStripWidth]

/-- **State invariance under the flow** (re-exposed through the bridge,
sourced from Logos's `vacuumState_modular_invariant`). -/
theorem state_invariant (t : ℝ) (a : H →L[ℂ] H) :
    B.vacuumBridge.ω (B.vacuumBridge.modularGroup.σ t a)
    = B.vacuumBridge.ω a :=
  B.vacuumBridge.ω_invariant t a

/-- Trivial existence: `gammaI ≡ 0` (so `kmsStripWidth ≡ 0` since
`(1 : ℝ) / 0 = 0`), `tauEnt ≡ 0` on both sides. -/
theorem exists_trivial : ∃ _ : KMSStripVacuumBridge H, True := by
  refine ⟨{ stripBridge      :=
             { gammaI := fun _ => 0
             , tauEnt := fun _ => 0
             , tauEnt_eq_kmsStripWidth := fun _ => by
                 rw [kmsStripWidth_eq]; simp }
           , vacuumBridge     :=
             { modularGroup     := { σ         := fun _ a => a
                                     , group_law := fun _ _ _ => rfl
                                     , zero_eq   := fun _ => rfl
                                     , mul_eq    := fun _ _ _ => rfl }
             , channel          := { tauEnt        := fun _ => 0
                                     , tauEnt_nonneg := fun _ => le_refl 0 }
             , ω                := fun _ => 0
             , ω_invariant      := fun _ _ => rfl
             , zero_consistency := rfl }
           , tauEnt_consistent := fun _ => rfl }, trivial⟩

end KMSStripVacuumBridge

/-- **KMS strip ↔ vacuum invariance bundle.** -/
theorem kms_strip_vacuum_bundle :
    ∃ _ : KMSStripVacuumBridge H, True :=
  KMSStripVacuumBridge.exists_trivial

end CATEPTMain.Integration.KMSStripVacuumBridge

end
