-- Auto-generated by pvs2lean/translator.py
-- PVS theory: inn_dp_termination
-- PVSLib library: TRS
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: inn_dp_termination

Auto-generated stubs from PVSLib theory `inn_dp_termination`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.inn_dp_termination

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (RTC : pvs_τ1 → pvs_τ2 → pvs_τ3 → Prop)
variable {pvs_τ4 : Type*} (app_p : pvs_τ4 → Prop)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} {pvs_τ10 : Type*} (arg_rest_p : pvs_τ5 → pvs_τ6 → pvs_τ7 → pvs_τ8 → pvs_τ9 → pvs_τ10 → Prop)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} (args : pvs_τ11 → pvs_τ12)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} {pvs_τ15 : Type*} (args_of_pos_seq : pvs_τ13 → pvs_τ14 → pvs_τ15)
variable {pvs_τ16 : Type*} (card : pvs_τ16 → Prop)
variable {pvs_τ17 : Type*} (choose : pvs_τ17 → Prop)
variable {pvs_τ18 : Type*} {pvs_τ19 : Type*} (dep_pair_alt : pvs_τ18 → pvs_τ19)
variable {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} (dep_pair_alt_p : pvs_τ20 → pvs_τ21 → pvs_τ22 → Prop)
variable {pvs_τ23 : Type*} (dep_pair_p : pvs_τ23 → Prop)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} (dps : pvs_τ26 → pvs_τ27)
variable {pvs_τ28 : Type*} {pvs_τ29 : Type*} (ext : pvs_τ28 → pvs_τ29 → Prop)
variable {pvs_τ30 : Type*} {pvs_τ31 : Type*} {pvs_τ32 : Type*} (finseq_appl : pvs_τ30 → pvs_τ31 → pvs_τ32)
variable {pvs_τ33 : Type*} {pvs_τ34 : Type*} (inf_red_arg_in_inf_nr_im_red : pvs_τ33 → pvs_τ34 → Prop)
variable {pvs_τ47 : Type*} {pvs_τ48 : Type*} {pvs_τ49 : Type*} {pvs_τ50 : Type*} (innermost_reduction_fix_p : pvs_τ47 → pvs_τ48 → pvs_τ49 → pvs_τ50 → Prop)
variable {pvs_τ51 : Type*} {pvs_τ52 : Type*} {pvs_τ53 : Type*} (innermost_reduction_p : pvs_τ51 → pvs_τ52 → pvs_τ53 → Prop)
variable {pvs_τ54 : Type*} {pvs_τ55 : Type*} (is_countably_infinite : pvs_τ54 → pvs_τ55)
variable {pvs_τ56 : Type*} {pvs_τ57 : Type*} (is_finite : pvs_τ56 → pvs_τ57)
variable {pvs_τ58 : Type*} {pvs_τ59 : Type*} (is_normal_form_p : pvs_τ58 → pvs_τ59 → Prop)
variable {pvs_τ60 : Type*} {pvs_τ61 : Type*} {pvs_τ62 : Type*} {pvs_τ63 : Type*} {pvs_τ64 : Type*} (iterate : pvs_τ60 → pvs_τ61 → pvs_τ62 → pvs_τ63 → pvs_τ64)
variable {pvs_τ65 : Type*} (length : pvs_τ65 → Prop)
variable {pvs_τ66 : Type*} {pvs_τ67 : Type*} (lhs : pvs_τ66 → pvs_τ67)
variable {pvs_τ68 : Type*} {pvs_τ69 : Type*} (member : pvs_τ68 → pvs_τ69 → Prop)
variable {pvs_τ70 : Type*} {pvs_τ71 : Type*} (min : pvs_τ70 → pvs_τ71)
variable {pvs_τ76 : Type*} (noetherian_p : pvs_τ76 → Prop)
variable {pvs_τ77 : Type*} {pvs_τ78 : Type*} {pvs_τ79 : Type*} (non_root_innermost_reduction_p : pvs_τ77 → pvs_τ78 → pvs_τ79 → Prop)
variable {pvs_τ80 : Type*} (non_root_reduction_p : pvs_τ80 → Prop)
variable {pvs_τ81 : Type*} (nonempty_p : pvs_τ81 → Prop)
variable {pvs_τ82 : Type*} (normal_sub_p : pvs_τ82 → Prop)
variable {pvs_τ89 : Type*} {pvs_τ90 : Type*} (positionsOF : pvs_τ89 → pvs_τ90 → Prop)
variable {pvs_τ91 : Type*} (positions_p : pvs_τ91 → Prop)
variable {pvs_τ92 : Type*} {pvs_τ93 : Type*} (reducible_p : pvs_τ92 → pvs_τ93 → Prop)
variable {pvs_τ94 : Type*} (reduction_p : pvs_τ94 → Prop)
variable {pvs_τ95 : Type*} {pvs_τ96 : Type*} (rest_p : pvs_τ95 → pvs_τ96 → Prop)
variable {pvs_τ97 : Type*} {pvs_τ98 : Type*} (rhs : pvs_τ97 → pvs_τ98)
variable {pvs_τ99 : Type*} {pvs_τ100 : Type*} (seq : pvs_τ99 → pvs_τ100)
variable {pvs_τ101 : Type*} (seqp : pvs_τ101 → Prop)
variable {pvs_τ102 : Type*} {pvs_τ103 : Type*} (seqt : pvs_τ102 → pvs_τ103)
variable {pvs_τ104 : Type*} {pvs_τ105 : Type*} (sigmas : pvs_τ104 → pvs_τ105)
variable {pvs_τ106 : Type*} {pvs_τ107 : Type*} {pvs_τ108 : Type*} (subtermOF : pvs_τ106 → pvs_τ107 → pvs_τ108)
variable {pvs_τ109 : Type*} {pvs_τ110 : Type*} (terminating_p : pvs_τ109 → pvs_τ110 → Prop)

-- pvs2lean: inn_dp_termination.var_countable
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_countably_infinite(V)
theorem var_countable : is_countably_infinite V := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inn_chained_dp?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_normal_form?(non_root_reduction?(E))(ext(sigma1)(dp1`1)) AND
--  is_normal_form?(non_root_reduction?(E))(ext(sigma2)(dp2`1)) AND
--   RTC(non_root_innermost_reduction?(E))
--      (ext(sigma1)(dp1`2), ext(s
axiom inn_chained_dp_p {pvs_τ37 : Type*} {pvs_τ38 : Type*} {pvs_τ39 : Type*} {pvs_τ40 : Type*} {pvs_τ41 : Type*} : pvs_τ37 → pvs_τ38 → pvs_τ39 → pvs_τ40 → pvs_τ41 → Prop

-- pvs2lean: inn_dp_termination.inn_infinite_dep_chain?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (i, j: nat):
--   NOT =(i, j) IMPLIES
--    inn_chained_dp?(E)(dps(i), dps(i + 1))(sigmas(i), sigmas(i + 1))
axiom inn_infinite_dep_chain_p {pvs_τ44 : Type*} {pvs_τ45 : Type*} {pvs_τ46 : Type*} : pvs_τ44 → pvs_τ45 → pvs_τ46 → Prop

-- pvs2lean: inn_dp_termination.inn_dp_termination?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (seq: sequence[dep_pair[variable, symbol, arity](E)],
--         sigmas: sequence[Sub[variable, symbol, arity]]):
--   NOT inn_infinite_dep_chain?(E)(seq, sigmas)
axiom inn_dp_termination_p {pvs_τ43 : Type*} : pvs_τ43 → Prop

-- pvs2lean: inn_dp_termination.inn_dp_termination_alt?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (dps: sequence[dep_pair_alt[variable, symbol, arity](E)],
--         sigmas: sequence[Sub[variable, symbol, arity]]):
--   LET seq =
--         LAMBDA (i: nat):
--           (lhs(dps(i)`1), subtermOF(rhs(d
axiom inn_dp_termination_alt_p {pvs_τ42 : Type*} : pvs_τ42 → Prop

-- pvs2lean: inn_dp_termination.inn_dp_termination_and_inn_alt_eq
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E): inn_dp_termination_alt?(E) IFF inn_dp_termination?(E)
theorem inn_dp_termination_and_inn_alt_eq : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), inn_dp_termination_alt_p E ↔ inn_dp_termination_p E := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inn_noetherian_implies_inn_dp_termination
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E):
--   noetherian?(innermost_reduction?(E)) IMPLIES inn_dp_termination?(E)
theorem inn_noetherian_implies_inn_dp_termination : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), noetherian_p (innermost_reduction_p E) → inn_dp_termination_p E := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.minimal_innermost_non_terminating?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: NOT terminating?(innermost_reduction?(E))(t) AND
--  FORALL (p: positions?(t) | NOT p = empty_seq):
--    terminating?(innermost_reduction?(E))(subtermOF(t, p))
axiom minimal_innermost_non_terminating_p {pvs_τ72 : Type*} {pvs_τ73 : Type*} : pvs_τ72 → pvs_τ73 → Prop

-- pvs2lean: inn_dp_termination.mint_is_app
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E, t): minimal_innermost_non_terminating?(E)(t) IMPLIES app?(t)
theorem mint_is_app : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool) (t : term pvs_variable symbol NIL), minimal_innermost_non_terminating_p E(t) → app_p t := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.args_innermost_minimal
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (t: term
--             | app?(t) AND
--                length(args(t)) > 0 AND
--                 NOT terminating?(innermost_reduction?(E))(t)):
--   minimal_innermost_non_terminating?(E)(t) IFF
--    FORALL
theorem args_innermost_minimal : ∀ (t : {t : term pvs_variable symbol NIL // app_p t ∧
 List.length (args t) > 0 ∧ ¬ terminating_p (innermost_reduction_p E) (t)}), minimal_innermost_non_terminating_p E(t) ↔ ∀ (i : Fin List.length (args t)), terminating_p (innermost_reduction_p E) (finseq_appl (args t) (i)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inn_non_terminating_has_mint
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E: set[rewrite_rule[variable, symbol, arity]]):
--   FORALL (t: term | NOT terminating?(innermost_reduction?(E))(t)):
--     EXISTS (p: positions?(t)):
--       minimal_innermost_non_terminating?(E)(su
theorem inn_non_terminating_has_mint : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (t : {t : term pvs_variable symbol NIL // ¬ terminating_p (innermost_reduction_p E) (t)}), ∃ (p : {p : {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // positionsOF t(p)}), minimal_innermost_non_terminating_p E (subtermOF t p) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.positions_of_inf_nr_reduction
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (seqt: sequence[term[variable, symbol, arity]]):
--   (FORALL (i: nat): non_root_innermost_reduction?(E)(seqt(i), seqt(i + 1)))
--    IMPLIES
--    (EXISTS (seqp: sequence[position[variable, symbol, ari
theorem positions_of_inf_nr_reduction : ∀ (seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL), (∀ (i : ℕ), non_root_innermost_reduction_p E(seqt i, seqt (i + 1))) → (∃ (seqp : ℕ → position variable symbol arity), ∀ (j : ℕ), ¬ seqp j = empty_seq ∧
      positionsOF (seqt j) (seqp j) ∧
       innermost_reduction_fix_p E(seqt j, seqt (j + 1), seqp j)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.exists_inf_red_arg_in_inf_nr_im_red
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E) (s: term | app?(s))
--        (seqt: sequence[term[variable, symbol, arity]]
--             | FORALL (n: nat):
--                 RTC(non_root_innermost_reduction?(E))(s, seqt(n)))
--        (seqp: seq
theorem exists_inf_red_arg_in_inf_nr_im_red : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (s : {s : term pvs_variable symbol NIL // app_p s}), ∀ (seqt : {seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∀ (n : ℕ), RTC (non_root_innermost_reduction_p E) (s, seqt n)}), ∀ (seqp : {seqp : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // ∀ (n : ℕ), positionsOF (seqt n) (seqp n) ∧
   ¬ empty_seq = seqp n ∧
    innermost_reduction_fix_p E(seqt n, seqt (n + 1), seqp n)}), ∃ (l : {l : {i : {i : ℝ // i ≥ 0} // i > 0} // l ≤ List.length (args s)}), inf_red_arg_in_inf_nr_im_red seqp l := by
  -- === TCCs for exists_inf_red_arg_in_inf_nr_im_red ===
  -- TCC: exists_inf_red_arg_in_inf_nr_im_red_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have exists_inf_red_arg_in_inf_nr_im_red_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.exists_nth_in_inf_nr_im_red
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E)
--        ((s: term | app?(s)),
--         (seqt: sequence[term[variable, symbol, arity]]
--              | FORALL (n: nat):
--                  RTC(non_root_innermost_reduction?(E))(s, seqt(n))),
--     
theorem exists_nth_in_inf_nr_im_red : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (s : {s : term pvs_variable symbol NIL // app_p s}) (seqt : {seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∀ (n : ℕ), RTC (non_root_innermost_reduction_p E) (s, seqt n)}) (seqp : {seqp : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // ∀ (n : ℕ), positionsOF (seqt n) (seqp n) ∧
   ¬ empty_seq = seqp n ∧
    innermost_reduction_fix_p E(seqt n, seqt (n + 1), seqp n)}) (l : {l : {i : {i : ℝ // i ≥ 0} // i > 0} // l ≤ List.length (args s) ∧ inf_red_arg_in_inf_nr_im_red seqp(l)}), ∀ (n : {i : ℝ // i ≥ 0}), ∃ (m : {i : ℝ // i ≥ 0}), args_of_pos_seq seqp(m) = l ∧ card ({k: nat | args_of_pos_seq seqp(k) = l ∧ k < m}) = n := by
  -- === TCCs for exists_nth_in_inf_nr_im_red ===
  -- TCC: exists_nth_in_inf_nr_im_red_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         (s: term[variable, symbol, arity]
  --              | app?[variable, symbol, arity](s)),
  --         (seqt: sequence[term[variable, symbol, ari...
  have exists_nth_in_inf_nr_im_red_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: exists_nth_in_inf_nr_im_red_TCC2
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         (s: term[variable, symbol, arity]
  --              | app?[variable, symbol, arity](s)),
  --         (seqt: sequence[term[variable, symbol, ari...
  have exists_nth_in_inf_nr_im_red_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.nth_index
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: choose({m: nat |
--           args_of_pos_seq(seqp)(m) = l AND
--            card({k: nat | args_of_pos_seq(seqp)(k) = l AND k < m}) = n})
axiom nth_index {pvs_τ83 : Type*} {pvs_τ84 : Type*} {pvs_τ85 : Type*} {pvs_τ86 : Type*} {pvs_τ87 : Type*} {pvs_τ88 : Type*} : pvs_τ83 → pvs_τ84 → pvs_τ85 → pvs_τ86 → pvs_τ87 → pvs_τ88 → Prop

-- pvs2lean: inn_dp_termination.nth_index_increasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E) (s: term | app?(s))
--        (seqt: sequence[term[variable, symbol, arity]]
--             | FORALL (n: nat):
--                 RTC(non_root_innermost_reduction?(E))(s, seqt(n)))
--        (seqp: seq
theorem nth_index_increasing : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (s : {s : term pvs_variable symbol NIL // app_p s}), ∀ (seqt : {seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∀ (n : ℕ), RTC (non_root_innermost_reduction_p E) (s, seqt n)}), ∀ (seqp : {seqp : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // ∀ (n : ℕ), positionsOF (seqt n) (seqp n) ∧
   ¬ empty_seq = seqp n ∧
    innermost_reduction_fix_p E(seqt n, seqt (n + 1), seqp n)}), ∀ (l : {l : {i : {i : ℝ // i ≥ 0} // i > 0} // l ≤ List.length (args s) ∧ inf_red_arg_in_inf_nr_im_red seqp(l)}), ∀ (i : {i : ℝ // i ≥ 0}) (j : {j : {i : ℝ // i ≥ 0} // i < j}), nth_index E(s) (seqt) (seqp) (l) (i) < nth_index E(s) (seqt) (seqp) (l) (j) := by
  -- === TCCs for nth_index_increasing ===
  -- TCC: nth_index_increasing_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have nth_index_increasing_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.nth_index_continuous
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E) (s: term | app?(s))
--        (seqt: sequence[term[variable, symbol, arity]]
--             | FORALL (n: nat):
--                 RTC(non_root_innermost_reduction?(E))(s, seqt(n)))
--        (seqp: seq
theorem nth_index_continuous : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (s : {s : term pvs_variable symbol NIL // app_p s}), ∀ (seqt : {seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∀ (n : ℕ), RTC (non_root_innermost_reduction_p E) (s, seqt n)}), ∀ (seqp : {seqp : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // ∀ (n : ℕ), positionsOF (seqt n) (seqp n) ∧
   ¬ empty_seq = seqp n ∧
    innermost_reduction_fix_p E(seqt n, seqt (n + 1), seqp n)}), ∀ (l : {l : {i : {i : ℝ // i ≥ 0} // i > 0} // l ≤ List.length (args s) ∧ inf_red_arg_in_inf_nr_im_red seqp(l)}), ∀ (i : {i : ℝ // i ≥ 0}), card ({k_1: nat |
        args_of_pos_seq seqp(k_1) = l ∧
         k_1 < nth_index E(s) (seqt) (seqp) (l) (i + 1)}) = card ({k_1: nat |
        args_of_pos_seq seqp(k_1) = l ∧
         k_1 < nth_index E(s) (seqt) (seqp) (l) (i)})
 + 1 := by
  -- === TCCs for nth_index_continuous ===
  -- TCC: nth_index_continuous_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have nth_index_continuous_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: nth_index_continuous_TCC2
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have nth_index_continuous_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: nth_index_continuous_TCC3
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have nth_index_continuous_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.argument_protected_in_non_nth_index
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E) (s: term | app?(s))
--        (seqt: sequence[term[variable, symbol, arity]]
--             | FORALL (n: nat):
--                 RTC(non_root_innermost_reduction?(E))(s, seqt(n)))
--        (seqp: seq
theorem argument_protected_in_non_nth_index : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (s : {s : term pvs_variable symbol NIL // app_p s}), ∀ (seqt : {seqt : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∀ (n : ℕ), RTC (non_root_innermost_reduction_p E) (s, seqt n)}), ∀ (seqp : {seqp : {i : ℝ // i ≥ 0} → {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // ∀ (n : ℕ), positionsOF (seqt n) (seqp n) ∧
   ¬ empty_seq = seqp n ∧
    innermost_reduction_fix_p E(seqt n, seqt (n + 1), seqp n)}), ∀ (l : {l : {i : {i : ℝ // i ≥ 0} // i > 0} // l ≤ List.length (args s) ∧ inf_red_arg_in_inf_nr_im_red seqp(l)}), ∀ (j : {i : ℝ // i ≥ 0}), (j < nth_index E(s) (seqt) (seqp) (l) (0) ∨
  (∃ (n : ℕ), nth_index E(s) (seqt) (seqp) (l) (n) < j ∧
      j < nth_index E(s) (seqt) (seqp) (l) (n + 1))) → ¬ arg_rest_p E(s) (l) (seqt j, seqt (j + 1)) (seqp j) := by
  -- === TCCs for argument_protected_in_non_nth_index ===
  -- TCC: argument_protected_in_non_nth_index_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have argument_protected_in_non_nth_index_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: argument_protected_in_non_nth_index_TCC2
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | app?[variable, symbol, arity](s),
  --         seqt: sequence[term[variable, symbol, arity]]...
  have argument_protected_in_non_nth_index_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.mint_is_nr_inn_terminating
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: minimal_innermost_non_terminating?(E)(s) IMPLIES
--  noetherian?(rest?(non_root_innermost_reduction?(E), s))
theorem mint_is_nr_inn_terminating : minimal_innermost_non_terminating_p E(s) → noetherian_p (rest_p (non_root_innermost_reduction_p E) s) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.reductions_below_min_root_are_non_root
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (seq: sequence[term[variable, symbol, arity]]
--             | EXISTS (i: nat):
--                 NOT rest?(non_root_innermost_reduction?(E), seq(0))
--                          (seq(i), seq(i + 1)),
--  
theorem reductions_below_min_root_are_non_root : ∀ (seq : {seq : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL // ∃ (i : ℕ), ¬ rest_p (non_root_innermost_reduction_p E) (seq 0) (seq i, seq (i + 1))}) (j : {j : {i : ℝ // i ≥ 0} // j =
 min ({i: nat |
        ¬ rest_p (non_root_innermost_reduction_p E) (seq 0)
                 (seq i, seq (i + 1))})}), ∀ (k : {k : {i : {i : ℝ // i ≥ 0} // i > 0} // k ≤ j}), iterate (non_root_innermost_reduction_p E) k (seq 0) (seq k) := by
  -- === TCCs for reductions_below_min_root_are_non_root ===
  -- TCC: reductions_below_min_root_are_non_root_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         seq: sequence[term[variable, symbol, arity]]
  --             | EXISTS (i: nat):
  --                 NOT rest?(non_root_innermost_reduction?(E)...
  have reductions_below_min_root_are_non_root_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inf_inn_deriv_of_mint_has_min_root_reduction_index
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (seq: sequence[term[variable, symbol, arity]]):
--   (minimal_innermost_non_terminating?(E)(seq(0)) AND
--     FORALL (i: nat): innermost_reduction?(E)(seq(i), seq(i + 1)))
--    IMPLIES
--    EXISTS (j: n
theorem inf_inn_deriv_of_mint_has_min_root_reduction_index : ∀ (seq : {i : ℝ // i ≥ 0} → term pvs_variable symbol NIL), (minimal_innermost_non_terminating_p E(seq 0) ∧
  ∀ (i : ℕ), innermost_reduction_p E(seq i, seq (i + 1))) → ∃ (j : ℕ), innermost_reduction_fix_p E(seq j, seq (j + 1), empty_seq) ∧
   ∀ (k : ℕ), innermost_reduction_fix_p E(seq k, seq (k + 1), empty_seq) →
      k ≥ j := by
  -- === TCCs for inf_inn_deriv_of_mint_has_min_root_reduction_index ===
  -- TCC: inf_inn_deriv_of_mint_has_min_root_reduction_index_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         seq: sequence[term[variable, symbol, arity]]):
  --   (minimal_innermost_non_terminating?(E)(seq(0)) AND
  --     FORALL (i: nat): innermost_red...
  have inf_inn_deriv_of_mint_has_min_root_reduction_index_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: inf_inn_deriv_of_mint_has_min_root_reduction_index_TCC2
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         seq: sequence[term[variable, symbol, arity]]):
  --   (minimal_innermost_non_terminating?(E)(seq(0)) AND
  --     FORALL (i: nat): innermost_red...
  have inf_inn_deriv_of_mint_has_min_root_reduction_index_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.mint_reduces_to_int_nrnf_term
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (s: (minimal_innermost_non_terminating?(E))):
--   EXISTS (t: term | NOT terminating?(innermost_reduction?(E))(t)):
--     RTC(non_root_innermost_reduction?(E))(s, t) AND
--      is_normal_form?(non_roo
theorem mint_reduces_to_int_nrnf_term : ∀ (s : term pvs_variable symbol NIL), ∃ (t : {t : term pvs_variable symbol NIL // ¬ terminating_p (innermost_reduction_p E) (t)}), RTC (non_root_innermost_reduction_p E) (s, t) ∧ is_normal_form_p (non_root_reduction_p E) (t) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.reducible_position_of_normal_inst_is_app_pos_of_term
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E) (t, (sigma: (normal_sub?(E))), p: positions?(ext(sigma)(t))):
--   reducible?(reduction?(E))(subtermOF(ext(sigma)(t), p)) IMPLIES
--    positionsOF(t)(p) AND app?(subtermOF(t, p))
theorem reducible_position_of_normal_inst_is_app_pos_of_term : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (t : term pvs_variable symbol NIL) (sigma : term pvs_variable symbol NIL → term pvs_variable symbol NIL) (p : {p : {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // positionsOF (ext sigma(t)) (p)}), reducible_p (reduction_p E) (subtermOF (ext sigma(t)) p) → positionsOF t(p) ∧ app_p (subtermOF t p) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.normal_inst_of_rule_with_mint_on_rhs_gives_dp_alt
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E)
--        (e: rewrite_rule[variable, symbol, arity] | member(e, E),
--         sigma: (normal_sub?(E)), p: positions?(ext(sigma)(rhs(e)))):
--   minimal_innermost_non_terminating?(E)(subtermOF(ext(s
theorem normal_inst_of_rule_with_mint_on_rhs_gives_dp_alt : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), ∀ (e : {e : term pvs_variable symbol NIL × term pvs_variable symbol NIL // member e E}) (sigma : term pvs_variable symbol NIL → term pvs_variable symbol NIL) (p : {p : {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // positionsOF (ext sigma(rhs e)) (p)}), minimal_innermost_non_terminating_p E(subtermOF (ext sigma(rhs e)) p) → dep_pair_alt_p E(e, p) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.mint_to_nit_nrnf
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: choose({t: term |
--           RTC(non_root_innermost_reduction?(E))(s, t) AND
--            is_normal_form?(non_root_reduction?(E))(t) AND
--             NOT terminating?(innermost_reduction?(E))(t)})
axiom mint_to_nit_nrnf {pvs_τ74 : Type*} {pvs_τ75 : Type*} : pvs_τ74 → pvs_τ75 → Prop

-- pvs2lean: inn_dp_termination.reduced_nit_nrnf_has_mint
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (s: term | minimal_innermost_non_terminating?(E)(s)):
--   EXISTS (sigma: Sub, e: rewrite_rule | member(e, E),
--           p: positions?(rhs(e))):
--     ext(sigma)(lhs(e)) = mint_to_nit_nrnf(E)(s) AND
theorem reduced_nit_nrnf_has_mint : ∀ (s : {s : term pvs_variable symbol NIL // minimal_innermost_non_terminating_p E(s)}), ∃ (sigma : term pvs_variable symbol NIL → term pvs_variable symbol NIL) (e : {e : term pvs_variable symbol NIL × term pvs_variable symbol NIL // member e E}) (p : {p : {i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}) // positionsOF (rhs e) (p)}), ext sigma(lhs e) = mint_to_nit_nrnf E(s) ∧ minimal_innermost_non_terminating_p E(subtermOF (ext sigma(rhs e)) p) := by
  -- === TCCs for reduced_nit_nrnf_has_mint ===
  -- TCC: reduced_nit_nrnf_has_mint_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         s: term[variable, symbol, arity]
  --             | minimal_innermost_non_terminating?(E)(s),
  --         sigma: Sub[variable, symbol, arity],
  -- ...
  have reduced_nit_nrnf_has_mint_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.dp_and_sub_from_int_nrnf
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET nf_term = mint_to_nit_nrnf(E)(s),
--     sub_e_p =
--       choose({(sigma: Sub, e: rewrite_rule, p: positions?(rhs(e))) |
--                 member(e, E) AND
--                  ext(sigma)(lhs(e)) = nf_term 
axiom dp_and_sub_from_int_nrnf {pvs_τ24 : Type*} {pvs_τ25 : Type*} : pvs_τ24 → pvs_τ25 → Prop

-- pvs2lean: inn_dp_termination.next_inst_dp_is_inn_chained_and_mnt
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E: set[rewrite_rule[variable, symbol, arity]], dp: dep_pair_alt(E),
--         sigma: Sub[variable, symbol, arity]
--             | minimal_innermost_non_terminating?(E)
--                             
theorem next_inst_dp_is_inn_chained_and_mnt : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool) (dp : (term pvs_variable symbol NIL × term pvs_variable symbol NIL) × ({i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}))) (sigma : {sigma : term pvs_variable symbol NIL → term pvs_variable symbol NIL // minimal_innermost_non_terminating_p E
                                  (subtermOF (ext sigma(rhs dp.1)) dp.2)
 ∧ is_normal_form_p (non_root_reduction_p E) (ext sigma(lhs dp.1))}), fun (std_dp : term pvs_variable symbol NIL × term pvs_variable symbol NIL) => fun (next_dp_sub : ((term pvs_variable symbol NIL × term pvs_variable symbol NIL) × ({i : ℝ // i ≥ 0} × ({s : {i : ℝ // i ≥ 0} // s < List.length} → {i : {i : ℝ // i ≥ 0} // i > 0}))) × (term pvs_variable symbol NIL → term pvs_variable symbol NIL)) => fun (next_std_dp : term pvs_variable symbol NIL × term pvs_variable symbol NIL) => fun (next_sub : term pvs_variable symbol NIL → term pvs_variable symbol NIL) => inn_chained_dp_p E(std_dp, next_std_dp) (sigma, next_sub) ∧ minimal_innermost_non_terminating_p E(ext next_sub(next_std_dp.2)) next_dp_sub.2 (lhs next_dp_sub.1.1) (subtermOF (rhs next_dp_sub.1.1) next_dp_sub.1.2) (dp_and_sub_from_int_nrnf E (subtermOF (ext sigma(rhs dp.1)) dp.2)) (lhs dp.1) (subtermOF (rhs dp.1) dp.2) := by
  -- === TCCs for next_inst_dp_is_inn_chained_and_mnt ===
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC1
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]):
  --   positionsOF[variable, symbol, arity]
  --    ...
  have next_inst_dp_is_inn_chained_and_mnt_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC2
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]
  --             | minimal_innermost_non_terminat...
  have next_inst_dp_is_inn_chained_and_mnt_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC3
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]
  --             | minimal_innermost_non_terminat...
  have next_inst_dp_is_inn_chained_and_mnt_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC4
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]
  --             | minimal_innermost_non_terminat...
  have next_inst_dp_is_inn_chained_and_mnt_tcc4 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC5
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]
  --             | minimal_innermost_non_terminat...
  have next_inst_dp_is_inn_chained_and_mnt_tcc5 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: next_inst_dp_is_inn_chained_and_mnt_TCC6
  -- Statement: FORALL (E: set[rewrite_rule[variable, symbol, arity]],
  --         dp: dep_pair_alt[variable, symbol, arity](E),
  --         sigma: Sub[variable, symbol, arity]
  --             | minimal_innermost_non_terminat...
  have next_inst_dp_is_inn_chained_and_mnt_tcc6 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.next_dp_and_sub
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: dp_and_sub_from_int_nrnf(E)(subtermOF(ext(dp_s`2)(rhs(dp_s`1`1)), dp_s`1`2))
noncomputable def next_dp_and_sub : sorry := by
  sorry  -- pvs2lean: definition stub for dp_and_sub_from_int_nrnf(E)(subtermOF(ext(dp_s`2)(rhs(dp_s`1`1)), dp_s`1`2))

-- pvs2lean: inn_dp_termination.inn_dp_termination_implies_noetherian
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E):
--   inn_dp_termination?(E) IMPLIES noetherian?(innermost_reduction?(E))
theorem inn_dp_termination_implies_noetherian : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), inn_dp_termination_p E → noetherian_p (innermost_reduction_p E) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inn_dp_termination_iff_innermost_noetherian
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E): inn_dp_termination?(E) IFF noetherian?(innermost_reduction?(E))
theorem inn_dp_termination_iff_innermost_noetherian : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), inn_dp_termination_p E ↔ noetherian_p (innermost_reduction_p E) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: inn_dp_termination.inn_chain
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: inn_chained_dp?(E)(dps1`1, dps2`1)(dps1`2, dps2`2)
axiom inn_chain {pvs_τ35 : Type*} {pvs_τ36 : Type*} : pvs_τ35 → pvs_τ36

-- pvs2lean: inn_dp_termination.inn_dp_termination_noetherian
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (E): inn_dp_termination?(E) IFF noetherian?(inn_chain(E))
theorem inn_dp_termination_noetherian : ∀ (E : term pvs_variable symbol NIL × term pvs_variable symbol NIL → Bool), inn_dp_termination_p E ↔ noetherian_p (inn_chain E) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.inn_dp_termination