-- Auto-generated by pvs2lean/translator.py
-- PVS theory: trs
-- PVSLib library: TRS
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: trs

Auto-generated stubs from PVSLib theory `trs`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.trs

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (is_countably_infinite : pvs_τ1 → pvs_τ2)

-- pvs2lean: trs.var_countable
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: is_countably_infinite(V)
theorem var_countable : is_countably_infinite V := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.trs