-- Auto-generated by pvs2lean/translator.py
-- PVS theory: bags
-- PVSLib library: structures
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: bags

Auto-generated stubs from PVSLib theory `bags`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.bags

noncomputable section

variable {pvs_τ19 : Type*} {pvs_τ20 : Type*} {pvs_τ21 : Type*} (max : pvs_τ19 → pvs_τ20 → pvs_τ21)
variable {pvs_τ22 : Type*} {pvs_τ23 : Type*} {pvs_τ24 : Type*} (min : pvs_τ22 → pvs_τ23 → pvs_τ24)

-- pvs2lean: bags.count
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: b(x)
noncomputable def count : sorry := by
  sorry  -- pvs2lean: definition stub for b(x)

-- pvs2lean: bags.emptybag
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: 0)
noncomputable def emptybag : sorry := by
  sorry  -- pvs2lean: definition stub for (LAMBDA t: 0)

-- pvs2lean: bags.singleton_bag
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA (x: T): IF x = t THEN 1 ELSE 0 ENDIF)
noncomputable def singleton_bag : sorry := by
  sorry  -- pvs2lean: definition stub for (LAMBDA (x: T): IF x = t THEN 1 ELSE 0 ENDIF)

-- pvs2lean: bags.insert
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: IF x = t THEN b(t) + 1 ELSE b(t) ENDIF)
axiom insert {pvs_τ14 : Type*} {pvs_τ15 : Type*} : pvs_τ14 → pvs_τ15 → Prop

-- pvs2lean: bags.purge
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: IF x = t THEN 0 ELSE b(t) ENDIF)
axiom purge {pvs_τ28 : Type*} {pvs_τ29 : Type*} {pvs_τ30 : Type*} : pvs_τ28 → pvs_τ29 → pvs_τ30

-- pvs2lean: bags.delete
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t:
--    IF x = t THEN IF b(t) >= n THEN b(t) - n ELSE 0 ENDIF ELSE b(t) ENDIF)
axiom delete {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} : pvs_τ1 → pvs_τ2 → pvs_τ3 → Prop

-- pvs2lean: bags.extract
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: IF x = t THEN b(t) ELSE 0 ENDIF)
axiom extract {pvs_τ11 : Type*} {pvs_τ12 : Type*} {pvs_τ13 : Type*} : pvs_τ11 → pvs_τ12 → pvs_τ13

-- pvs2lean: bags.plus
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: a(t) + b(t))
axiom plus {pvs_τ25 : Type*} {pvs_τ26 : Type*} {pvs_τ27 : Type*} : pvs_τ25 → pvs_τ26 → pvs_τ27

-- pvs2lean: bags.union
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: max(a(t), b(t)))
axiom union {pvs_τ33 : Type*} {pvs_τ34 : Type*} {pvs_τ35 : Type*} : pvs_τ33 → pvs_τ34 → pvs_τ35

-- pvs2lean: bags.intersection
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (LAMBDA t: min(a(t), b(t)))
axiom intersection {pvs_τ16 : Type*} {pvs_τ17 : Type*} {pvs_τ18 : Type*} : pvs_τ16 → pvs_τ17 → pvs_τ18

-- pvs2lean: bags.member
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: b(x) > 0
noncomputable def member : sorry := by
  sorry  -- pvs2lean: definition stub for b(x) > 0

-- pvs2lean: bags.empty?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: b(x) = 0)
axiom empty_p {pvs_τ6 : Type*} : pvs_τ6 → Prop

-- pvs2lean: bags.nonempty_bag?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NOT empty?(b)
noncomputable def nonempty_bag_p : sorry := by
  sorry  -- pvs2lean: definition stub for NOT empty?(b)

-- pvs2lean: bags.eqmult
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (a(x) = b(x))
axiom eqmult {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} {pvs_τ10 : Type*} : pvs_τ7 → pvs_τ8 → pvs_τ9 → pvs_τ10

-- pvs2lean: bags.subbag?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: a(x) <= b(x))
axiom subbag_p {pvs_τ31 : Type*} {pvs_τ32 : Type*} : pvs_τ31 → pvs_τ32 → Prop

-- pvs2lean: bags.proper_subbag?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL x: a(x) < b(x))
noncomputable def proper_subbag_p : sorry := by
  sorry  -- pvs2lean: definition stub for (FORALL x: a(x) < b(x))

-- pvs2lean: bags.disjoint?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: empty?(intersection(a, b))
axiom disjoint_p {pvs_τ4 : Type*} {pvs_τ5 : Type*} : pvs_τ4 → pvs_τ5 → Prop

-- pvs2lean: bags.emptybag_is_empty?
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: empty?(b) IFF b = emptybag
theorem emptybag_is_empty_p : empty_p b ↔ b = emptybag := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.delete_purge
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: n >= b(x) IMPLIES delete(x, b, n) = purge(x, b)
theorem delete_purge : n ≥ b x → delete x b n = purge x b := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.insert_unique
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: insert(x, a) = insert(x, b) IMPLIES a = b
theorem insert_unique : insert x a = insert x b → a = b := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.insert_exchange
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: insert(x, insert(y, b)) = insert(y, insert(x, b))
theorem insert_exchange : insert x (insert y b) = insert y (insert x b) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.delete_insert
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: n > 0 IMPLIES (delete(x, insert(x, b), n) = delete(x, b, n - 1))
theorem delete_insert : n > 0 → (delete x (insert x b) n = delete x b (n - 1)) := by
  -- === TCCs for delete_insert ===
  -- TCC: delete_insert_TCC1
  -- Statement: FORALL (n: nat): n > 0 IMPLIES n - 1 >= 0
  have delete_insert_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.insert_delete
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: b(x) > 0 IMPLIES insert(x, delete(x, b, 1)) = b
theorem insert_delete : b x > 0 → insert x (delete x b 1) = b := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.delete_insert_diff
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x /= y IMPLIES (delete(x, insert(y, b), n) = insert(y, delete(x, b, n)))
theorem delete_insert_diff : x ≠ y → (delete x (insert y b) n = insert y (delete x b n)) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.decomposition
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NOT empty?(b) IMPLIES (EXISTS a, x: b = insert(x, a))
theorem decomposition : ¬ empty_p b → (∃ a x,  b = insert x a) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.bag_equality
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: a = b IFF (FORALL x: eqmult(x, a, b))
theorem bag_equality : a = b ↔ (∀ x,  eqmult x a b) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.subbag_empty
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subbag?(emptybag, a)
theorem subbag_empty : subbag_p emptybag a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.subbag_equality
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: a = b IFF subbag?(a, b) AND subbag?(b, a)
theorem subbag_equality : a = b ↔ subbag_p a b ∧ subbag_p b a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.subbag_trans
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subbag?(a, b) AND subbag?(b, c) IMPLIES subbag?(a, c)
theorem subbag_trans : subbag_p a b ∧ subbag_p b c → subbag_p a c := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.bag_plus_union
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: plus(union(a, b), intersection(a, b)) = plus(a, b)
theorem bag_plus_union : plus (union a b) (intersection a b) = plus a b := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_plus_comm
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: plus(a, b) = plus(b, a)
theorem bag_plus_comm : plus a b = plus b a := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.plus_emptybag
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: plus(emptybag, a) = a
theorem plus_emptybag : plus emptybag a = a := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_plus_insert
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: plus(insert(x, a), b) = insert(x, plus(a, b))
theorem bag_plus_insert : plus (insert x a) b = insert x (plus a b) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: intersection(a, union(b, c)) = union(intersection(a, b), intersection(a, c))
theorem bag_distributive : intersection a (union b c) = union (intersection a b) (intersection a c) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.extract_subbag
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subbag?(extract(x, a), a)
theorem extract_subbag : subbag_p (extract x a) a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.extract_disj
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x /= y IMPLIES disjoint?(extract(x, a), extract(y, a))
theorem extract_disj : x ≠ y → disjoint_p (extract x a) (extract y a) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.bag_disj_comm
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: disjoint?(a, b) = disjoint?(b, a)
theorem bag_disj_comm : disjoint_p a b = disjoint_p b a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.bag_union_comm
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: union(a, b) = union(b, a)
theorem bag_union_comm : union a b = union b a := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_union_fix_pt
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: union(a, a) = a
theorem bag_union_fix_pt : union a a = a := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_purge_extract
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: a = union(purge(x, a), extract(x, a))
theorem bag_purge_extract : a = union (purge x a) (extract x a) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: bags.bag_disj_extract_perge
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: disjoint?(extract(x, a), purge(x, a))
theorem bag_disj_extract_perge : disjoint_p (extract x a) (purge x a) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.bag_extract_union_subbag
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: x /= y IMPLIES subbag?(union(extract(x, a), extract(y, a)), a)
theorem bag_extract_union_subbag : x ≠ y → subbag_p (union (extract x a) (extract y a)) a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: bags.union_upper_bound
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subbag?(a, c) AND subbag?(b, c) IMPLIES subbag?(union(a, b), c)
theorem union_upper_bound : subbag_p a c ∧ subbag_p b c → subbag_p (union a b) c := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.bags