-- Auto-generated by pvs2lean/translator.py
-- PVS theory: function_props_aux
-- PVSLib library: structures
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: function_props_aux

Auto-generated stubs from PVSLib theory `function_props_aux`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.function_props_aux

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (inverse_alt : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} (inverse_image : pvs_τ3 → pvs_τ4 → pvs_τ5)

-- pvs2lean: function_props_aux.inverse_image_composition
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: inverse_image(f1, inverse_image(f2, Y)) = inverse_image(f2 o f1, Y)
theorem inverse_image_composition : inverse_image f1 (inverse_image f2 Y) = inverse_image (f2 ∘ f1) Y := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: function_props_aux.composition_inverse_alt
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (f1: (bijective?[T1, T2]), f2: (bijective?[T2, T3])):
--   inverse_alt(f2 o f1) = inverse_alt(f1) o inverse_alt(f2)
theorem composition_inverse_alt : ∀ (f1 : T1 → T2) (f2 : T2 → T3), inverse_alt (f2 ∘ f1) = inverse_alt f1 ∘ inverse_alt f2 := by
  -- === TCCs for composition_inverse_alt ===
  -- TCC: composition_inverse_alt_TCC1
  -- Statement: FORALL (f1: (bijective?[T1, T2]), f2: (bijective?[T2, T3])):
  --   (EXISTS (d: T1): TRUE) OR (FORALL (r: T3): FALSE)
  have composition_inverse_alt_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: composition_inverse_alt_TCC2
  -- Statement: FORALL (f1: (bijective?[T1, T2]), f2: (bijective?[T2, T3])):
  --   (EXISTS (d: T1): TRUE) OR (FORALL (r: T2): FALSE)
  have composition_inverse_alt_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: composition_inverse_alt_TCC3
  -- Statement: FORALL (f1: (bijective?[T1, T2]), f2: (bijective?[T2, T3])):
  --   (EXISTS (d: T2): TRUE) OR (FORALL (r: T3): FALSE)
  have composition_inverse_alt_tcc3 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.function_props_aux