-- Auto-generated by pvs2lean/translator.py
-- PVS theory: cd2d_ever
-- PVSLib library: ACCoRD
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: cd2d_ever

Auto-generated stubs from PVSLib theory `cd2d_ever`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.cd2d_ever

noncomputable section

variable {pvs_τ4 : Type*} {pvs_τ5 : Type*} (sq : pvs_τ4 → pvs_τ5)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (sqv : pvs_τ6 → pvs_τ7)

-- pvs2lean: cd2d_ever.cd2d_ever
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF s * v < 0 THEN (sq(s * v) - sqv(v) * (sqv(s) - sq(D)) > 0)
-- ELSE (sqv(s) < sq(D))
-- ENDIF
axiom cd2d_ever {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} : pvs_τ1 → pvs_τ2 → pvs_τ3 → Prop

-- pvs2lean: cd2d_ever.cd2d_ever_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: cd2d_ever(D, s, v) IFF horizontal_conflict?[D](s, v)
theorem cd2d_ever_def : cd2d_ever D s v ↔ horizontal_conflict_p s v := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.cd2d_ever