-- Auto-generated by pvs2lean/translator.py
-- PVS theory: cd_vertical
-- PVSLib library: ACCoRD
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: cd_vertical

Auto-generated stubs from PVSLib theory `cd_vertical`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.cd_vertical

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} {pvs_τ4 : Type*} (Theta_H : pvs_τ1 → pvs_τ2 → pvs_τ3 → pvs_τ4)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} {pvs_τ11 : Type*} (max : pvs_τ9 → pvs_τ10 → pvs_τ11)
variable {pvs_τ12 : Type*} {pvs_τ13 : Type*} (min : pvs_τ12 → pvs_τ13 → Prop)
variable {pvs_τ14 : Type*} {pvs_τ15 : Type*} (sign : pvs_τ14 → pvs_τ15)

-- pvs2lean: cd_vertical.conflict_vertical?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: EXISTS (t: Lookahead): abs(sz + t * vz) < H
axiom conflict_vertical_p {pvs_τ7 : Type*} {pvs_τ8 : Type*} : pvs_τ7 → pvs_τ8 → Prop

-- pvs2lean: cd_vertical.cd_vertical?
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (vz = 0 AND abs(sz) < H) OR
--  (vz /= 0 AND
--    min(max(-H - sign(vz) * sz, B * abs(vz)), T * abs(vz)) <
--     max(min(H - sign(vz) * sz, T * abs(vz)), B * abs(vz)))
axiom cd_vertical_p {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: cd_vertical.cd_vertical_rewrite
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: cd_vertical?(sz, vz) IFF
--  (vz = 0 AND abs(sz) < H) OR
--   (vz /= 0 AND
--     min(max(Theta_H(sz, vz, -1), B), T) <
--      max(min(Theta_H(sz, vz, 1), T), B))
theorem cd_vertical_rewrite : cd_vertical_p sz vz ↔ (vz = 0 ∧ |sz| < H) ∨
 (vz ≠ 0 ∧
   min (max (Theta_H sz vz -1) B) T < max (min (Theta_H sz vz 1) T) B) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cd_vertical.cd_vertical_correct
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: cd_vertical?(sz, vz) IMPLIES conflict_vertical?(sz, vz)
theorem cd_vertical_correct : cd_vertical_p sz vz → conflict_vertical_p sz vz := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cd_vertical.cd_vertical_complete
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: conflict_vertical?(sz, vz) IMPLIES cd_vertical?(sz, vz)
theorem cd_vertical_complete : conflict_vertical_p sz vz → cd_vertical_p sz vz := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cd_vertical.cd_vertical
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: conflict_vertical?(sz, vz) IFF cd_vertical?(sz, vz)
theorem cd_vertical : conflict_vertical_p sz vz ↔ cd_vertical_p sz vz := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cd_vertical.conflict_vertical_on_open_interval
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: conflict_vertical?(sz, vz) IFF
--  EXISTS (topen: Lookahead):
--    B < topen AND topen < T AND abs(sz + topen * vz) < H
theorem conflict_vertical_on_open_interval : conflict_vertical_p sz vz ↔ ∃ (topen : Lookahead), B < topen ∧ topen < T ∧ |sz + topen * vz| < H := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.cd_vertical