-- Auto-generated by pvs2lean/translator.py
-- PVS theory: horizontal_los_criterion
-- PVSLib library: ACCoRD
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: horizontal_los_criterion

Auto-generated stubs from PVSLib theory `horizontal_los_criterion`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.horizontal_los_criterion

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} {pvs_τ4 : Type*} (repulsive_criteria : pvs_τ1 → pvs_τ2 → pvs_τ3 → pvs_τ4 → Prop)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} {pvs_τ7 : Type*} (repulsive_p : pvs_τ5 → pvs_τ6 → pvs_τ7 → Prop)

-- pvs2lean: horizontal_los_criterion.horizontal_los_criterion
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: repulsive_criteria(s, vo - vi, eps)(nvo - vi)
noncomputable def horizontal_los_criterion : sorry := by
  sorry  -- pvs2lean: definition stub for repulsive_criteria(s, vo - vi, eps)(nvo - vi)

-- pvs2lean: horizontal_los_criterion.horizontal_los_criterion_repulsive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: repulsive_criteria(s, vo - vi, eps)(nvo - vi) IMPLIES
--  repulsive?(s, vo - vi)(nvo - vi)
theorem horizontal_los_criterion_repulsive : repulsive_criteria s (vo - vi) eps(nvo - vi) → repulsive_p s (vo - vi) (nvo - vi) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: horizontal_los_criterion.horizontal_los_criterion_coordinately_repulsive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: repulsive_criteria(s, vo - vi, eps)(nvo - vi) AND
--  repulsive_criteria(-s, vi - vo, eps)(nvi - vo)
--  IMPLIES repulsive?(s, vo - vi)(nvo - nvi)
theorem horizontal_los_criterion_coordinately_repulsive : repulsive_criteria s (vo - vi) eps(nvo - vi) ∧
 repulsive_criteria -s (vi - vo) eps(nvi - vo) → repulsive_p s (vo - vi) (nvo - nvi) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.horizontal_los_criterion