-- Auto-generated by pvs2lean/translator.py
-- PVS theory: clock_shift
-- PVSLib library: fault_tolerance
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: clock_shift

Auto-generated stubs from PVSLib theory `clock_shift`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.clock_shift

noncomputable section

variable {pvs_τ3 : Type*} {pvs_τ4 : Type*} (c1 : pvs_τ3 → pvs_τ4)
variable {pvs_τ5 : Type*} {pvs_τ6 : Type*} (c2 : pvs_τ5 → pvs_τ6)
variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} (clock_edge_p : pvs_τ7 → pvs_τ8 → Prop)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (le1 : pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} (le2 : pvs_τ11 → Prop)
variable {pvs_τ12 : Type*} {pvs_τ13 : Type*} (local_event : pvs_τ12 → pvs_τ13)
variable {pvs_τ18 : Type*} {pvs_τ19 : Type*} (offset_clocks_p : pvs_τ18 → pvs_τ19 → Prop)

-- pvs2lean: clock_shift.all_clock_edge?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL n: clock_edge?(c(n), local_event(n))
axiom all_clock_edge_p {pvs_τ1 : Type*} {pvs_τ2 : Type*} : pvs_τ1 → pvs_τ2 → Prop

-- pvs2lean: clock_shift.offset
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: c(n)(C(c(n))(local_event(n)) + T)
axiom offset {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} : pvs_τ14 → pvs_τ15 → pvs_τ16 → pvs_τ17 → Prop

-- pvs2lean: clock_shift.same_edges?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL n: offset_clocks?(c1(n), c2(n))
axiom same_edges_p {pvs_τ20 : Type*} {pvs_τ21 : Type*} : pvs_τ20 → pvs_τ21 → Prop

-- pvs2lean: clock_shift.offset_left_edge
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: clock_edge?(c(n), local_event(n)) AND 0 <= T IMPLIES
--  T / rate <= offset(c, T)(local_event)(n) - local_event(n)
theorem offset_left_edge : clock_edge_p (c n) (local_event n) ∧ 0 ≤ T → T / rate ≤ offset c T(local_event) (n) - local_event n := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_left
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: X / rate < offset(c, X)(local_event)(n) - local_event(n) + rate
theorem offset_left : X / rate < offset c X(local_event) (n) - local_event n + rate := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_right_edge
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: clock_edge?(c(n), local_event(n)) AND 0 <= T IMPLIES
--  offset(c, T)(local_event)(n) - local_event(n) <= rate * T
theorem offset_right_edge : clock_edge_p (c n) (local_event n) ∧ 0 ≤ T → offset c T(local_event) (n) - local_event n ≤ rate * T := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_right
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: offset(c, X)(local_event)(n) - local_event(n) <= rate * X
theorem offset_right : offset c X(local_event) (n) - local_event n ≤ rate * X := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_zero
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: all_clock_edge?(c, local_event) IMPLIES
--  offset(c, 0)(local_event) = local_event
theorem offset_zero : all_clock_edge_p c local_event → offset c 0(local_event) = local_event := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_drift
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: offset(c, X)(local_event)(n2) - offset(c, X)(local_event)(n1) <
--  local_event(n2) - local_event(n1) + drift * X + rate
theorem offset_drift : offset c X(local_event) (n2) - offset c X(local_event) (n1) < local_event n2 - local_event n1 + drift * X + rate := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_nondecreasing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: le1(n) <= le2(n) IMPLIES offset(c, T)(le1)(n) <= offset(c, T)(le2)(n)
theorem offset_nondecreasing : le1 n ≤ le2 n → offset c T(le1) (n) ≤ offset c T(le2) (n) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: clock_shift.offset_drift_edge
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: clock_edge?(c(n1), le1(n1)) AND clock_edge?(c(n2), le2(n2)) IMPLIES
--  offset(c, X)(le2)(n2) - offset(c, X)(le1)(n1) <=
--   le2(n2) - le1(n1) + drift * X
theorem offset_drift_edge : clock_edge_p (c n1) (le1 n1) ∧ clock_edge_p (c n2) (le2 n2) → offset c X(le2) (n2) - offset c X(le1) (n1) ≤
 le2 n2 - le1 n1 + drift * X := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.double_offset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: offset(c, T1)(offset(c, T2)(local_event)) = offset(c, T1 + T2)(local_event)
theorem double_offset : offset c T1(offset c T2(local_event)) = offset c (T1 + T2) (local_event) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_same
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: same_edges?(c1, c2) IMPLIES
--  (offset(c1, T1 + T2)(le1) = offset(c2, T1 + T2)(le2) IFF
--    offset(c1, T2)(le1) = offset(c2, T2)(le2))
theorem offset_same : same_edges_p c1 c2 → (offset c1 (T1 + T2) (le1) = offset c2 (T1 + T2) (le2) ↔
  offset c1 T2(le1) = offset c2 T2(le2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: clock_shift.offset_same2
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: same_edges?(c1, c2) AND
--  all_clock_edge?(c1, le1) AND all_clock_edge?(c2, le2)
--  IMPLIES (offset(c1, T1)(le1) = offset(c2, T1)(le2) IFF le1 = le2)
theorem offset_same2 : same_edges_p c1 c2 ∧
 all_clock_edge_p c1 le1 ∧ all_clock_edge_p c2 le2 → (offset c1 T1(le1) = offset c2 T1(le2) ↔ le1 = le2) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.clock_shift