-- Auto-generated by pvs2lean/translator.py
-- PVS theory: virtual_clocks
-- PVSLib library: fault_tolerance
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: virtual_clocks

Auto-generated stubs from PVSLib theory `virtual_clocks`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.virtual_clocks

noncomputable section

variable {pvs_τ7 : Type*} {pvs_τ8 : Type*} (ceiling : pvs_τ7 → pvs_τ8)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} {pvs_τ11 : Type*} (compatible_p : pvs_τ9 → pvs_τ10 → pvs_τ11 → Prop)
variable {pvs_τ21 : Type*} (es : pvs_τ21 → Prop)
variable {pvs_τ22 : Type*} {pvs_τ23 : Type*} (es1 : pvs_τ22 → pvs_τ23)
variable {pvs_τ24 : Type*} {pvs_τ25 : Type*} (es2 : pvs_τ24 → pvs_τ25)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} (ic : pvs_τ26 → pvs_τ27 → pvs_τ28)
variable {pvs_τ29 : Type*} {pvs_τ30 : Type*} (ic1 : pvs_τ29 → pvs_τ30)
variable {pvs_τ31 : Type*} {pvs_τ32 : Type*} (ic2 : pvs_τ31 → pvs_τ32)
variable {pvs_τ33 : Type*} {pvs_τ34 : Type*} (index_of : pvs_τ33 → pvs_τ34 → Prop)
variable {pvs_τ41 : Type*} {pvs_τ42 : Type*} {pvs_τ43 : Type*} (lower_accuracy_bound_p : pvs_τ41 → pvs_τ42 → pvs_τ43 → Prop)
variable {pvs_τ44 : Type*} {pvs_τ45 : Type*} (max : pvs_τ44 → pvs_τ45 → Prop)
variable {pvs_τ46 : Type*} {pvs_τ47 : Type*} (nonoverlap_p : pvs_τ46 → pvs_τ47 → Prop)
variable {pvs_τ48 : Type*} {pvs_τ49 : Type*} {pvs_τ50 : Type*} {pvs_τ51 : Type*} (obs_p : pvs_τ48 → pvs_τ49 → pvs_τ50 → pvs_τ51 → Prop)
variable {pvs_τ52 : Type*} {pvs_τ53 : Type*} {pvs_τ54 : Type*} (peer_precision_p : pvs_τ52 → pvs_τ53 → pvs_τ54 → Prop)
variable {pvs_τ58 : Type*} {pvs_τ59 : Type*} {pvs_τ60 : Type*} (upper_accuracy_bound_p : pvs_τ58 → pvs_τ59 → pvs_τ60 → Prop)

-- pvs2lean: virtual_clocks.VC
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: C(ic(index_of(es)(t1)))(t1)
axiom VC {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ4 → pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: virtual_clocks.VC_j
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: VC(es)(ic)(es(k)) = C(ic(k))(es(k))
theorem VC_j : VC es(ic) (es k) = C (ic k) (es k) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: virtual_clocks.earliest_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL k: ic(k)(T(k) - A) <= es(k)
axiom earliest_adjustment_p {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} : pvs_τ15 → pvs_τ16 → pvs_τ17 → Prop

-- pvs2lean: virtual_clocks.latest_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL k: es(k + 1) <= ic(k)(T(k + 1) + A)
axiom latest_adjustment_p {pvs_τ35 : Type*} {pvs_τ36 : Type*} {pvs_τ37 : Type*} : pvs_τ35 → pvs_τ36 → pvs_τ37 → Prop

-- pvs2lean: virtual_clocks.earliest_cross_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL k: ic(k)(T(k + 1) - A) <= es(k + 1)
axiom earliest_cross_adjustment_p {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} : pvs_τ18 → pvs_τ19 → pvs_τ20 → Prop

-- pvs2lean: virtual_clocks.latest_cross_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL k: es(k) <= ic(k)(T(k) + A)
axiom latest_cross_adjustment_p {pvs_τ38 : Type*} {pvs_τ39 : Type*} {pvs_τ40 : Type*} : pvs_τ38 → pvs_τ39 → pvs_τ40 → Prop

-- pvs2lean: virtual_clocks.self_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: earliest_adjustment?(ic, A)(es) AND latest_adjustment?(ic, A)(es)
axiom self_adjustment_p {pvs_τ55 : Type*} {pvs_τ56 : Type*} {pvs_τ57 : Type*} : pvs_τ55 → pvs_τ56 → pvs_τ57 → Prop

-- pvs2lean: virtual_clocks.cross_adjustment?
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: earliest_cross_adjustment?(ic, A)(es) AND
--  latest_cross_adjustment?(ic, A)(es)
axiom cross_adjustment_p {pvs_τ12 : Type*} {pvs_τ13 : Type*} {pvs_τ14 : Type*} : pvs_τ12 → pvs_τ13 → pvs_τ14 → Prop

-- pvs2lean: virtual_clocks.observable_peers
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: self_adjustment?(ic, A)(es) AND es(0) <= t1 IMPLIES
--  obs?(P + A, T(index_of(es)(t1)), ic(index_of(es)(t1)), t1)
theorem observable_peers : self_adjustment_p ic A(es) ∧ es 0 ≤ t1 → obs_p (P + A) (T (index_of es(t1))) (ic (index_of es(t1))) t1 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.observable_master
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: self_adjustment?(ic1, A)(es1) AND
--  cross_adjustment?(ic1, A)(es2) AND
--   max(es1(0), es2(0)) <= t1 AND index_of(es2)(t1) = index_of(es1)(t1) + 1
--  IMPLIES obs?(A, T(index_of(es1)(t1) + 1), ic1(index_of(
theorem observable_master : self_adjustment_p ic1 A(es1) ∧
 cross_adjustment_p ic1 A(es2) ∧
  max (es1 0) (es2 0) ≤ t1 ∧ index_of es2(t1) = index_of es1(t1) + 1 → obs_p A (T (index_of es1(t1) + 1)) (ic1 (index_of es1(t1))) t1 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.observable_slave
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: self_adjustment?(ic2, A)(es2) AND
--  cross_adjustment?(ic2, A)(es1) AND
--   max(es1(0), es2(0)) <= t1 AND index_of(es2)(t1) = index_of(es1)(t1) + 1
--  IMPLIES obs?(A, T(index_of(es1)(t1) + 1), ic2(index_of(
theorem observable_slave : self_adjustment_p ic2 A(es2) ∧
 cross_adjustment_p ic2 A(es1) ∧
  max (es1 0) (es2 0) ≤ t1 ∧ index_of es2(t1) = index_of es1(t1) + 1 → obs_p A (T (index_of es1(t1) + 1)) (ic2 (index_of es1(t1) + 1)) t1 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.adjustment_nonoverlap
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: latest_cross_adjustment?(ic, A)(es1) AND
--  earliest_cross_adjustment?(ic, A)(es2) AND 2 * A <= P
--  IMPLIES nonoverlap?(es1, es2)
theorem adjustment_nonoverlap : latest_cross_adjustment_p ic A(es1) ∧
 earliest_cross_adjustment_p ic A(es2) ∧ 2 * A ≤ P → nonoverlap_p es1 es2 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.Pi
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: ceiling(rate * (adj + drift * (P + A)))
axiom Pi {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} : pvs_τ1 → pvs_τ2 → pvs_τ3

-- pvs2lean: virtual_clocks.VC_precision_0
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt:      peer_precision?(ic1, ic2, adj) AND peer_precision?(ic2, ic1, adj)
--  AND self_adjustment?(ic1, A)(es1) AND self_adjustment?(ic2, A)(es2)
--  AND (max(es1(0), es2(0)) <= t1)
--  AND (index_of(es2)(t1) = i
theorem VC_precision_0 : peer_precision_p ic1 ic2 adj ∧ peer_precision_p ic2 ic1 adj
 ∧ self_adjustment_p ic1 A(es1) ∧ self_adjustment_p ic2 A(es2)
 ∧ (max (es1 0) (es2 0) ≤ t1) ∧ (index_of es2(t1) = index_of es1(t1)) → |VC es1(ic1) (t1) - VC es2(ic2) (t1)| ≤ Pi adj A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.VC_precision_1
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt:      compatible?(ic1, ic2, adj) AND self_adjustment?(ic1, A)(es1)
--  AND self_adjustment?(ic2, A)(es2) AND cross_adjustment?(ic1, A)(es2)
--  AND cross_adjustment?(ic2, A)(es1) AND (max(es1(0), es2(0)) <= 
theorem VC_precision_1 : compatible_p ic1 ic2 adj ∧ self_adjustment_p ic1 A(es1)
 ∧ self_adjustment_p ic2 A(es2) ∧ cross_adjustment_p ic1 A(es2)
 ∧ cross_adjustment_p ic2 A(es1) ∧ (max (es1 0) (es2 0) ≤ t1)
 ∧ (index_of es2(t1) = index_of es1(t1) + 1) → |VC es1(ic1) (t1) - VC es2(ic2) (t1)| ≤ Pi adj A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.VC_precision_sym
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt:      compatible?(ic1, ic2, adj) AND compatible?(ic2, ic1, adj)
--  AND nonoverlap?(es1, es2) AND self_adjustment?(ic1, A)(es1)
--  AND self_adjustment?(ic2, A)(es2) AND cross_adjustment?(ic1, A)(es2)
--  AND c
theorem VC_precision_sym : compatible_p ic1 ic2 adj ∧ compatible_p ic2 ic1 adj
 ∧ nonoverlap_p es1 es2 ∧ self_adjustment_p ic1 A(es1)
 ∧ self_adjustment_p ic2 A(es2) ∧ cross_adjustment_p ic1 A(es2)
 ∧ cross_adjustment_p ic2 A(es1) ∧ (max (es1 0) (es2 0) ≤ t1)
 ∧ (index_of es2(t1) ≥ index_of es1(t1)) → |VC es1(ic1) (t1) - VC es2(ic2) (t1)| ≤ Pi adj A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.VC_precision
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt:      compatible?(ic1, ic2, adj) AND compatible?(ic2, ic1, adj)
--  AND nonoverlap?(es1, es2) AND nonoverlap?(es2, es1)
--  AND self_adjustment?(ic1, A)(es1) AND self_adjustment?(ic2, A)(es2)
--  AND cross_adju
theorem VC_precision : compatible_p ic1 ic2 adj ∧ compatible_p ic2 ic1 adj
 ∧ nonoverlap_p es1 es2 ∧ nonoverlap_p es2 es1
 ∧ self_adjustment_p ic1 A(es1) ∧ self_adjustment_p ic2 A(es2)
 ∧ cross_adjustment_p ic1 A(es2) ∧ cross_adjustment_p ic2 A(es1)
 ∧ (max (es1 0) (es2 0) ≤ t1) → |VC es1(ic1) (t1) - VC es2(ic2) (t1)| ≤ Pi adj A := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.index_upper_bound
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: lower_accuracy_bound?(ic, al, pi) AND
--  earliest_adjustment?(ic, A)(es) AND p = P / rate - al AND es(0) <= t1
--  IMPLIES index_of(es)(t1) <= (t1 - t(ic)(0) + A * rate + pi) / p
theorem index_upper_bound : lower_accuracy_bound_p ic al pi ∧
 earliest_adjustment_p ic A(es) ∧ p = P / rate - al ∧ es 0 ≤ t1 → index_of es(t1) ≤ (t1 - t ic(0) + A * rate + pi) / p := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.VC_lower_accuracy
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt:      upper_accuracy_bound?(ic, au, pi) AND lower_accuracy_bound?(ic, al, pi)
--  AND earliest_adjustment?(ic, A)(es) AND (p = P / rate - al)
--  AND (es(0) <= t1)
--  IMPLIES
--  ((t1 - t(ic)(0)) * (1 - au / p) -
theorem VC_lower_accuracy : upper_accuracy_bound_p ic au pi ∧ lower_accuracy_bound_p ic al pi
 ∧ earliest_adjustment_p ic A(es) ∧ (p = P / rate - al)
 ∧ (es 0 ≤ t1) → ((t1 - t ic(0)) * (1 - au / p) - pi * (1 + au / p) -
  A * (drift + rate * au / p))
 / rate
 < 1 + VC es(ic) (t1) - T 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: virtual_clocks.VC_upper_accuracy
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: lower_accuracy_bound?(ic, al, pi) AND
--  earliest_adjustment?(ic, A)(es) AND p = P / rate - al AND es(0) <= t1
--  IMPLIES
--  VC(es)(ic)(t1) - T(0) <=
--   ((t1 - t(ic)(0)) * (1 + al / p) + pi * (1 + al / p) +
-- 
theorem VC_upper_accuracy : lower_accuracy_bound_p ic al pi ∧
 earliest_adjustment_p ic A(es) ∧ p = P / rate - al ∧ es 0 ≤ t1 → VC es(ic) (t1) - T 0 ≤
 ((t1 - t ic(0)) * (1 + al / p) + pi * (1 + al / p) +
   A * (drift + rate * al / p))
  * rate := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.virtual_clocks