-- Auto-generated by pvs2lean/translator.py
-- PVS theory: LTL_past_prop
-- PVSLib library: LTL
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: LTL_past_prop

Auto-generated stubs from PVSLib theory `LTL_past_prop`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.LTL_past_prop

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (AND_LTL : pvs_τ1 → pvs_τ2 → pvs_τ3)
variable {pvs_τ4 : Type*} {pvs_τ5 : Type*} (CNST : pvs_τ4 → pvs_τ5)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (HISTORICALLY : pvs_τ6 → pvs_τ7)
variable {pvs_τ8 : Type*} {pvs_τ9 : Type*} {pvs_τ10 : Type*} (HISTORICALLY_BD : pvs_τ8 → pvs_τ9 → pvs_τ10)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} (NOT_LTL : pvs_τ11 → pvs_τ12)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} (ONCE : pvs_τ13 → pvs_τ14)
variable {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} (ONCE_BD : pvs_τ15 → pvs_τ16 → pvs_τ17)
variable {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} (OR_LTL : pvs_τ18 → pvs_τ19 → pvs_τ20)
variable {pvs_τ21 : Type*} {pvs_τ22 : Type*} (PREVIOUS : pvs_τ21 → pvs_τ22)
variable {pvs_τ23 : Type*} {pvs_τ24 : Type*} {pvs_τ25 : Type*} (SINCE : pvs_τ23 → pvs_τ24 → pvs_τ25)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} (TRIGGERED : pvs_τ26 → pvs_τ27 → pvs_τ28)
variable {pvs_τ29 : Type*} {pvs_τ30 : Type*} (ZETA : pvs_τ29 → pvs_τ30)
variable {pvs_τ31 : Type*} {pvs_τ32 : Type*} (equiv : pvs_τ31 → pvs_τ32 → Prop)

-- pvs2lean: LTL_past_prop.previous_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES equiv(PREVIOUS(f1), PREVIOUS(f2))
theorem previous_equiv : equiv f1 f2 → equiv (PREVIOUS f1) (PREVIOUS f2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.zeta_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES equiv(ZETA(f1), ZETA(f2))
theorem zeta_equiv : equiv f1 f2 → equiv (ZETA f1) (ZETA f2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES equiv(HISTORICALLY(f1), HISTORICALLY(f2))
theorem historically_equiv : equiv f1 f2 → equiv (HISTORICALLY f1) (HISTORICALLY f2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_bd_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES
--  equiv(HISTORICALLY_BD(f1, interval), HISTORICALLY_BD(f2, interval))
theorem historically_bd_equiv : equiv f1 f2 → equiv (HISTORICALLY_BD f1 interval) (HISTORICALLY_BD f2 interval) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES equiv(ONCE(f1), ONCE(f2))
theorem once_equiv : equiv f1 f2 → equiv (ONCE f1) (ONCE f2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_bd_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(f1, f2) IMPLIES equiv(ONCE_BD(f1, interval), ONCE_BD(f2, interval))
theorem once_bd_equiv : equiv f1 f2 → equiv (ONCE_BD f1 interval) (ONCE_BD f2 interval) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (equiv(f1, f2) AND equiv(g1, g2)) IMPLIES
--  equiv(SINCE(f1, g1), SINCE(f2, g2))
theorem since_equiv : (equiv f1 f2 ∧ equiv g1 g2) → equiv (SINCE f1 g1) (SINCE f2 g2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.triggered_equiv
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (equiv(f1, f2) AND equiv(g1, g2)) IMPLIES
--  equiv(TRIGGERED(f1, g1), TRIGGERED(f2, g2))
theorem triggered_equiv : (equiv f1 f2 ∧ equiv g1 g2) → equiv (TRIGGERED f1 g1) (TRIGGERED f2 g2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_since
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ONCE(f1), SINCE(CNST(TRUE), f1))
theorem once_since : equiv (ONCE f1) (SINCE (CNST True) f1) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_dual
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY(f1), NOT_LTL(ONCE(NOT_LTL(f1))))
theorem historically_dual : equiv (HISTORICALLY f1) (NOT_LTL (ONCE (NOT_LTL f1))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_bd_dual
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY_BD(f1, interval),
--       NOT_LTL(ONCE_BD(NOT_LTL(f1), interval)))
theorem historically_bd_dual : equiv (HISTORICALLY_BD f1 interval) (NOT_LTL (ONCE_BD (NOT_LTL f1) interval)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_dual
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(SINCE(f1, f2), NOT_LTL(TRIGGERED(NOT_LTL(f1), NOT_LTL(f2))))
theorem since_dual : equiv (SINCE f1 f2) (NOT_LTL (TRIGGERED (NOT_LTL f1) (NOT_LTL f2))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_idempotent
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ONCE(f1), ONCE(ONCE(f1)))
theorem once_idempotent : equiv (ONCE f1) (ONCE (ONCE f1)) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_idempotent
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY(f1), HISTORICALLY(HISTORICALLY(f1)))
theorem historically_idempotent : equiv (HISTORICALLY f1) (HISTORICALLY (HISTORICALLY f1)) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_idempotent
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(SINCE(f1, f2), SINCE(SINCE(f1, f2), f2))
theorem since_idempotent : equiv (SINCE f1 f2) (SINCE (SINCE f1 f2) f2) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_previous
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(SINCE(f1, f2), OR_LTL(f2, AND_LTL(f1, PREVIOUS(SINCE(f1, f2)))))
theorem since_previous : equiv (SINCE f1 f2) (OR_LTL f2 (AND_LTL f1 (PREVIOUS (SINCE f1 f2)))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.triggered_zeta
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(TRIGGERED(f1, f2), AND_LTL(f2, OR_LTL(f1, ZETA(TRIGGERED(f1, f2)))))
theorem triggered_zeta : equiv (TRIGGERED f1 f2) (AND_LTL f2 (OR_LTL f1 (ZETA (TRIGGERED f1 f2)))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_zeta
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY(f1), AND_LTL(f1, ZETA(HISTORICALLY(f1))))
theorem historically_zeta : equiv (HISTORICALLY f1) (AND_LTL f1 (ZETA (HISTORICALLY f1))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.zeta_or_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ZETA(OR_LTL(f1, f2)), OR_LTL(ZETA(f1), ZETA(f2)))
theorem zeta_or_distributive : equiv (ZETA (OR_LTL f1 f2)) (OR_LTL (ZETA f1) (ZETA f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.zeta_and_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ZETA(AND_LTL(f1, f2)), AND_LTL(ZETA(f1), ZETA(f2)))
theorem zeta_and_distributive : equiv (ZETA (AND_LTL f1 f2)) (AND_LTL (ZETA f1) (ZETA f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.previous_or_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(PREVIOUS(OR_LTL(f1, f2)), OR_LTL(PREVIOUS(f1), PREVIOUS(f2)))
theorem previous_or_distributive : equiv (PREVIOUS (OR_LTL f1 f2)) (OR_LTL (PREVIOUS f1) (PREVIOUS f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.previous_and_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(PREVIOUS(AND_LTL(f1, f2)), AND_LTL(PREVIOUS(f1), PREVIOUS(f2)))
theorem previous_and_distributive : equiv (PREVIOUS (AND_LTL f1 f2)) (AND_LTL (PREVIOUS f1) (PREVIOUS f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_or_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ONCE(OR_LTL(f1, f2)), OR_LTL(ONCE(f1), ONCE(f2)))
theorem once_or_distributive : equiv (ONCE (OR_LTL f1 f2)) (OR_LTL (ONCE f1) (ONCE f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.once_bd_or_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(ONCE_BD(OR_LTL(f1, f2), interval),
--       OR_LTL(ONCE_BD(f1, interval), ONCE_BD(f2, interval)))
theorem once_bd_or_distributive : equiv (ONCE_BD (OR_LTL f1 f2) interval) (OR_LTL (ONCE_BD f1 interval) (ONCE_BD f2 interval)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_and_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY(AND_LTL(f1, f2)),
--       AND_LTL(HISTORICALLY(f1), HISTORICALLY(f2)))
theorem historically_and_distributive : equiv (HISTORICALLY (AND_LTL f1 f2)) (AND_LTL (HISTORICALLY f1) (HISTORICALLY f2)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.historically_bd_and_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(HISTORICALLY_BD(AND_LTL(f1, f2), interval),
--       AND_LTL(HISTORICALLY_BD(f1, interval), HISTORICALLY_BD(f2, interval)))
theorem historically_bd_and_distributive : equiv (HISTORICALLY_BD (AND_LTL f1 f2) interval) (AND_LTL (HISTORICALLY_BD f1 interval) (HISTORICALLY_BD f2 interval)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_or_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(SINCE(f1, OR_LTL(f2, f3)), OR_LTL(SINCE(f1, f2), SINCE(f1, f3)))
theorem since_or_distributive : equiv (SINCE f1 (OR_LTL f2 f3)) (OR_LTL (SINCE f1 f2) (SINCE f1 f3)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: LTL_past_prop.since_and_distributive
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: equiv(SINCE(AND_LTL(f2, f3), f1), AND_LTL(SINCE(f2, f1), SINCE(f3, f1)))
theorem since_and_distributive : equiv (SINCE (AND_LTL f2 f3) f1) (AND_LTL (SINCE f2 f1) (SINCE f3 f1)) := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.LTL_past_prop