-- Auto-generated by pvs2lean/translator.py
-- PVS theory: reverse_polygons
-- PVSLib library: polygons
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: reverse_polygons

Auto-generated stubs from PVSLib theory `reverse_polygons`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.reverse_polygons

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} (below : pvs_τ1 → pvs_τ2)
variable {pvs_τ3 : Type*} (ccw_vertex_order_p : pvs_τ3 → Prop)
variable {pvs_τ4 : Type*} {pvs_τ5 : Type*} (dir_parallel_p : pvs_τ4 → pvs_τ5 → Prop)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} {pvs_τ8 : Type*} (edge_crossing_point : pvs_τ6 → pvs_τ7 → pvs_τ8)
variable {pvs_τ9 : Type*} {pvs_τ10 : Type*} (edge_of_polygon_p : pvs_τ9 → pvs_τ10 → Prop)
variable {pvs_τ11 : Type*} {pvs_τ12 : Type*} (edges_of_polygon : pvs_τ11 → pvs_τ12 → Prop)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} (find_index_any : pvs_τ13 → pvs_τ14 → Prop)
variable {pvs_τ15 : Type*} {pvs_τ16 : Type*} (has_rightward_crossings_p : pvs_τ15 → pvs_τ16 → Prop)
variable {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} (leftmost_intersection_point : pvs_τ17 → pvs_τ18 → pvs_τ19)
variable {pvs_τ20 : Type*} (leftmost_vertex_val : pvs_τ20 → Prop)
variable {pvs_τ21 : Type*} {pvs_τ22 : Type*} {pvs_τ23 : Type*} {pvs_τ24 : Type*} {pvs_τ25 : Type*} (miter_point : pvs_τ21 → pvs_τ22 → pvs_τ23 → pvs_τ24 → pvs_τ25)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} {pvs_τ28 : Type*} (next_index : pvs_τ26 → pvs_τ27 → pvs_τ28)
variable {pvs_τ29 : Type*} {pvs_τ30 : Type*} (point_on_polygon_perimeter_p : pvs_τ29 → pvs_τ30 → Prop)
variable {pvs_τ31 : Type*} {pvs_τ32 : Type*} (point_on_segment_p : pvs_τ31 → pvs_τ32 → Prop)
variable {pvs_τ33 : Type*} {pvs_τ34 : Type*} (prev_index : pvs_τ33 → pvs_τ34 → Prop)
variable {pvs_τ38 : Type*} {pvs_τ39 : Type*} (reverse_segment : pvs_τ38 → pvs_τ39)
variable {pvs_τ40 : Type*} {pvs_τ41 : Type*} (rightward_edge_crossing_p : pvs_τ40 → pvs_τ41 → Prop)
variable {pvs_τ42 : Type*} {pvs_τ43 : Type*} (segment_endpoint_p : pvs_τ42 → pvs_τ43 → Prop)
variable {pvs_τ44 : Type*} (segment_falling_p : pvs_τ44 → Prop)
variable {pvs_τ45 : Type*} (segment_rising_p : pvs_τ45 → Prop)
variable {pvs_τ46 : Type*} (simple_polygon_2d_p : pvs_τ46 → Prop)
variable {pvs_τ47 : Type*} (topleft_vertex_idx : pvs_τ47 → Prop)
variable {pvs_τ48 : Type*} {pvs_τ49 : Type*} (topleft_vertex_val : pvs_τ48 → pvs_τ49)
variable {pvs_τ50 : Type*} (uniq_vertex_list_p : pvs_τ50 → Prop)
variable {pvs_τ51 : Type*} (vertices : pvs_τ51 → Prop)

-- pvs2lean: reverse_polygons.rev_polygon_index
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i = 0 THEN 0 ELSE G`num_vertices - i ENDIF
axiom rev_polygon_index {pvs_τ35 : Type*} {pvs_τ36 : Type*} : pvs_τ35 → pvs_τ36 → Prop

-- pvs2lean: reverse_polygons.reverse_polygon
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (# num_vertices := G`num_vertices,
--    vertices
--      := LAMBDA (i: below(G`num_vertices)):
--           G`vertices(rev_polygon_index(G, i)) #)
axiom reverse_polygon {pvs_τ37 : Type*} : pvs_τ37 → Prop

-- pvs2lean: reverse_polygons.rev_polygon_index_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   rev_polygon_index(reverse_polygon(G), i) = rev_polygon_index(G, i)
theorem rev_polygon_index_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), rev_polygon_index (reverse_polygon G) i = rev_polygon_index G i := by
  -- === TCCs for rev_polygon_index_reverse ===
  -- TCC: rev_polygon_index_reverse_TCC1
  -- Statement: FORALL (G: polygon_2d, i: below(G`num_vertices)):
  --   i < reverse_polygon(G)`num_vertices
  have rev_polygon_index_reverse_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.rev_rev_polygon_index
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   rev_polygon_index(G, rev_polygon_index(G, i)) = i
theorem rev_rev_polygon_index : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), rev_polygon_index G (rev_polygon_index G i) = i := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.reverse_reverse_polygon
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d): reverse_polygon(reverse_polygon(G)) = G
theorem reverse_reverse_polygon : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)), reverse_polygon (reverse_polygon G) = G := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.reverse_vertex_rev_index
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   reverse_polygon(G)`vertices(rev_polygon_index(G, i)) = G`vertices(i)
theorem reverse_vertex_rev_index : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), reverse_polygon G.vertices (rev_polygon_index G i) = G.vertices i := by
  -- === TCCs for reverse_vertex_rev_index ===
  -- TCC: reverse_vertex_rev_index_TCC1
  -- Statement: FORALL (G: polygon_2d, i: below(G`num_vertices)):
  --   rev_polygon_index(G, i) < reverse_polygon(G)`num_vertices
  have reverse_vertex_rev_index_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.prev_index_rev_index_next
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   prev_index(G, rev_polygon_index(G, i)) =
--    rev_polygon_index(G, next_index(G, i))
theorem prev_index_rev_index_next : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), prev_index G (rev_polygon_index G i) = rev_polygon_index G (next_index G i) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.prev_index_of_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   reverse_polygon(G)`vertices(prev_index(reverse_polygon(G), i)) =
--    G`vertices(next_index(G, rev_polygon_index(G, i)))
theorem prev_index_of_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), reverse_polygon G.vertices (prev_index (reverse_polygon G) i) = G.vertices (next_index G (rev_polygon_index G i)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.next_index_rev_index_prev
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   next_index(G, rev_polygon_index(G, i)) =
--    rev_polygon_index(G, prev_index(G, i))
theorem next_index_rev_index_prev : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), next_index G (rev_polygon_index G i) = rev_polygon_index G (prev_index G i) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.next_index_of_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   reverse_polygon(G)`vertices(next_index(reverse_polygon(G), i)) =
--    G`vertices(prev_index(G, rev_polygon_index(G, i)))
theorem next_index_of_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), reverse_polygon G.vertices (next_index (reverse_polygon G) i) = G.vertices (prev_index G (rev_polygon_index G i)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.edges_of_reverse_polygon
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices)):
--   edges_of_polygon(reverse_polygon(G))(i) =
--    reverse_segment(edges_of_polygon(G)
--                                    (prev_index(G, rev_polygon_index
theorem edges_of_reverse_polygon : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), edges_of_polygon (reverse_polygon G) (i) = reverse_segment (edges_of_polygon G(prev_index G (rev_polygon_index G i))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.point_on_edge_of_rev_polygon
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (p: point_2d, G: polygon_2d, i: below(G`num_vertices)):
--   point_on_segment?(p, edges_of_polygon(reverse_polygon(G))(i)) IFF
--    point_on_segment?(p,
--                      edges_of_polygon(G)
--     
theorem point_on_edge_of_rev_polygon : ∀ (p : ℝ × ℝ) (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), point_on_segment_p p (edges_of_polygon (reverse_polygon G) (i)) ↔ point_on_segment_p p (edges_of_polygon G
                                  (prev_index G (rev_polygon_index G i))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.edge_of_rev_polygon_rev_segment
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, s: segment_2d):
--   edge_of_polygon?(G)(s) IMPLIES
--    edge_of_polygon?(reverse_polygon(G))(reverse_segment(s))
theorem edge_of_rev_polygon_rev_segment : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (s : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})), edge_of_polygon_p G(s) → edge_of_polygon_p (reverse_polygon G) (reverse_segment s) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.edge_of_rev_polygon_imp_edge_rev_seg
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, s: segment_2d):
--   edge_of_polygon?(reverse_polygon(G))(s) IMPLIES
--    edge_of_polygon?(G)(reverse_segment(s))
theorem edge_of_rev_polygon_imp_edge_rev_seg : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (s : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})), edge_of_polygon_p (reverse_polygon G) (s) → edge_of_polygon_p G(reverse_segment s) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.rev_polygon_edge_is_rev_segment
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, i: below(G`num_vertices), s: segment_2d):
--   edges_of_polygon(reverse_polygon(G))(i) = s IMPLIES
--    edges_of_polygon(G)(prev_index(G, rev_polygon_index(G, i))) =
--     reverse_segm
theorem rev_polygon_edge_is_rev_segment : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}) (s : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})), edges_of_polygon (reverse_polygon G) (i) = s → edges_of_polygon G(prev_index G (rev_polygon_index G i)) =
 reverse_segment s := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.on_rev_perim_eqv_on_perim
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: polygon_2d, p: point_2d):
--   point_on_polygon_perimeter?(reverse_polygon(G))(p) IFF
--    point_on_polygon_perimeter?(G)(p)
theorem on_rev_perim_eqv_on_perim : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (p : ℝ × ℝ), point_on_polygon_perimeter_p (reverse_polygon G) (p) ↔ point_on_polygon_perimeter_p G(p) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.topleft_index_of_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d):
--   topleft_vertex_idx(reverse_polygon(G)) =
--    rev_polygon_index(G, topleft_vertex_idx(G))
theorem topleft_index_of_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)), topleft_vertex_idx (reverse_polygon G) = rev_polygon_index G (topleft_vertex_idx G) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.topleft_vertex_of_reverse_is_same
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d):
--   reverse_polygon(G)`vertices(topleft_vertex_idx(reverse_polygon(G))) =
--    G`vertices(topleft_vertex_idx(G))
theorem topleft_vertex_of_reverse_is_same : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)), reverse_polygon G.vertices (topleft_vertex_idx (reverse_polygon G)) = G.vertices (topleft_vertex_idx G) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.find_index_any_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, p: point_2d, i: below(G`num_vertices)):
--   point_on_segment?(p, edges_of_polygon(G)(i)) AND
--    NOT segment_endpoint?(edges_of_polygon(G)(i))(p)
--    IMPLIES
--    find_index_an
theorem find_index_any_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (p : ℝ × ℝ) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), point_on_segment_p p (edges_of_polygon G(i)) ∧
 ¬ segment_endpoint_p (edges_of_polygon G(i)) (p) → find_index_any (reverse_polygon G) p =
 prev_index G (rev_polygon_index G i) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.find_index_any_vertex_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, i: below(G`num_vertices)):
--   find_index_any(reverse_polygon(G), G`vertices(i)) =
--    rev_polygon_index(G, i)
theorem find_index_any_vertex_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), find_index_any (reverse_polygon G) (G.vertices i) = rev_polygon_index G i := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.ccw_reverse_polygon
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d):
--   ccw_vertex_order?(G) IFF NOT ccw_vertex_order?(reverse_polygon(G))
theorem ccw_reverse_polygon : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)), ccw_vertex_order_p G ↔ ¬ ccw_vertex_order_p (reverse_polygon G) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.ccw_miter_pt_left_of_topleft_vtx
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
theorem ccw_miter_pt_left_of_topleft_vtx : True := by
  -- === TCCs for ccw_miter_pt_left_of_topleft_vtx ===
  -- TCC: ccw_miter_pt_left_of_topleft_vtx_TCC1
  -- Statement: FORALL (G: simple_polygon_2d,
  --         i:
  --           {i: below(G`num_vertices) |
  --              G`vertices(i)`x = leftmost_vertex_val(G) AND
  --               G`vertices(i)`y = topleft_vertex_val(G)}):
  --   i...
  have ccw_miter_pt_left_of_topleft_vtx_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: ccw_miter_pt_left_of_topleft_vtx_TCC2
  -- Statement: FORALL (G: simple_polygon_2d,
  --         i:
  --           {i: below(G`num_vertices) |
  --              G`vertices(i)`x = leftmost_vertex_val(G) AND
  --               G`vertices(i)`y = topleft_vertex_val(G)}):
  --   i...
  have ccw_miter_pt_left_of_topleft_vtx_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- needs_human: automated tactics exhausted

-- pvs2lean: reverse_polygons.segment_falling_reverse_rising
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, i: below(G`num_vertices)):
--   LET H = reverse_polygon(G),
--       e = edges_of_polygon(G)(i),
--       j = prev_index(H, rev_polygon_index(G, i)),
--       r = edges_of_polygon(H)
theorem segment_falling_reverse_rising : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), fun (H : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) => fun (e : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) => fun (j : {s : {i : ℝ // i ≥ 0} // s < H.num_vertices}) => fun (r : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) => segment_falling_p e ↔ segment_rising_p r (edges_of_polygon H j) (prev_index H (rev_polygon_index G i)) (edges_of_polygon G i) (reverse_polygon G) := by
  -- === TCCs for segment_falling_reverse_rising ===
  -- TCC: segment_falling_reverse_rising_TCC1
  -- Statement: FORALL (G: simple_polygon_2d, i: below(G`num_vertices),
  --         H: simple_polygon_2d, e: segment_2d):
  --   H = reverse_polygon(G) AND e = edges_of_polygon(G)(i) IMPLIES
  --    rev_polygon_index(G, i) < H`...
  have segment_falling_reverse_rising_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.segment_falling_reverse_image
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, i: below(G`num_vertices)):
--   LET H = reverse_polygon(G),
--       e = edges_of_polygon(G)(i),
--       j = prev_index(G, rev_polygon_index(G, i)),
--       r = edges_of_polygon(H)
theorem segment_falling_reverse_image : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (i : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}), fun (H : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) => fun (e : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) => fun (j : {s : {i : ℝ // i ≥ 0} // s < G.num_vertices}) => fun (r : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) => segment_falling_p e ↔ segment_falling_p (reverse_segment r) (edges_of_polygon H j) (prev_index G (rev_polygon_index G i)) (edges_of_polygon G i) (reverse_polygon G) := by
  -- === TCCs for segment_falling_reverse_image ===
  -- TCC: segment_falling_reverse_image_TCC1
  -- Statement: FORALL (G: simple_polygon_2d, i: below(G`num_vertices),
  --         H: simple_polygon_2d, e: segment_2d, j: below(G`num_vertices)):
  --   H = reverse_polygon(G) AND
  --    e = edges_of_polygon(G)(i) AND
  --     j ...
  have segment_falling_reverse_image_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.reverse_seg_rightward_edge_crossing
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (e: segment_2d, p: (rightward_edge_crossing?(e))):
--   rightward_edge_crossing?(reverse_segment(e))(p)
theorem reverse_seg_rightward_edge_crossing : ∀ (e : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) (p : ℝ × ℝ), rightward_edge_crossing_p (reverse_segment e) p := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.reverse_has_rightward_crossings
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, p: point_2d):
--   has_rightward_crossings?(G)(p) IFF
--    has_rightward_crossings?(reverse_polygon(G))(p)
theorem reverse_has_rightward_crossings : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (p : ℝ × ℝ), has_rightward_crossings_p G(p) ↔ has_rightward_crossings_p (reverse_polygon G) (p) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.edge_crossing_point_same_in_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (e: segment_2d, p: (rightward_edge_crossing?(e))):
--   edge_crossing_point(reverse_segment(e), p) = edge_crossing_point(e, p)
theorem edge_crossing_point_same_in_reverse : ∀ (e : (ℝ × ℝ) × ({p : ℝ × ℝ // p ≠ p1})) (p : ℝ × ℝ), edge_crossing_point (reverse_segment e) p = edge_crossing_point e p := by
  -- === TCCs for edge_crossing_point_same_in_reverse ===
  -- TCC: edge_crossing_point_same_in_reverse_TCC1
  -- Statement: FORALL (e: segment_2d, p: (rightward_edge_crossing?(e))):
  --   rightward_edge_crossing?(reverse_segment(e))(p)
  have edge_crossing_point_same_in_reverse_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: reverse_polygons.leftmost_crossing_same_in_reverse
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (G: simple_polygon_2d, p: (has_rightward_crossings?(G))):
--   leftmost_intersection_point(reverse_polygon(G), p) =
--    leftmost_intersection_point(G, p)
theorem leftmost_crossing_same_in_reverse : ∀ (G : {s : ℝ // s ≥ 3} × ({s : {i : ℝ // i ≥ 0} // s < num_vertices} → ℝ × ℝ)) (p : ℝ × ℝ), leftmost_intersection_point (reverse_polygon G) p = leftmost_intersection_point G p := by
  -- === TCCs for leftmost_crossing_same_in_reverse ===
  -- TCC: leftmost_crossing_same_in_reverse_TCC1
  -- Statement: FORALL (G: simple_polygon_2d, p: (has_rightward_crossings?(G))):
  --   has_rightward_crossings?(reverse_polygon(G))(p)
  have leftmost_crossing_same_in_reverse_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.reverse_polygons