-- Auto-generated by pvs2lean/translator.py
-- PVS theory: cosets
-- PVSLib library: algebra
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: cosets

Auto-generated stubs from PVSLib theory `cosets`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.cosets

noncomputable section

variable {pvs_τ1 : Type*} (bijective_p : pvs_τ1 → Prop)
variable {pvs_τ2 : Type*} {pvs_τ3 : Type*} (choose : pvs_τ2 → pvs_τ3)
variable {pvs_τ9 : Type*} (group_p : pvs_τ9 → Prop)
variable {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} (image : pvs_τ10 → pvs_τ11 → pvs_τ12)
variable {pvs_τ13 : Type*} {pvs_τ14 : Type*} (inv : pvs_τ13 → pvs_τ14)
variable {pvs_τ21 : Type*} {pvs_τ22 : Type*} {pvs_τ23 : Type*} (left_cosets : pvs_τ21 → pvs_τ22 → pvs_τ23)
variable {pvs_τ24 : Type*} {pvs_τ25 : Type*} (member : pvs_τ24 → pvs_τ25 → Prop)
variable {pvs_τ26 : Type*} (nonempty_p : pvs_τ26 → Prop)
variable {pvs_τ34 : Type*} {pvs_τ35 : Type*} {pvs_τ36 : Type*} (right_cosets : pvs_τ34 → pvs_τ35 → pvs_τ36)
variable {pvs_τ37 : Type*} {pvs_τ38 : Type*} (subgroup : pvs_τ37 → pvs_τ38)
variable {pvs_τ39 : Type*} {pvs_τ40 : Type*} (subgroup_p : pvs_τ39 → pvs_τ40 → Prop)
variable {pvs_τ41 : Type*} {pvs_τ42 : Type*} (subset_p : pvs_τ41 → pvs_τ42 → Prop)

-- pvs2lean: cosets.fullset_is_group
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: group?(fullset[T])
theorem fullset_is_group : group_p fullset := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.congruent_mod
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: member(a * inv(b), H)
axiom congruent_mod {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} {pvs_τ7 : Type*} {pvs_τ8 : Type*} : pvs_τ4 → pvs_τ5 → pvs_τ6 → pvs_τ7 → pvs_τ8

-- pvs2lean: cosets.congruence_is_equivalence
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) IMPLIES equivalence?[T](congruent_mod(G, H))
theorem congruence_is_equivalence : subgroup_p H G → equivalence_p (congruent_mod G H) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.*
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: {t: T | EXISTS (h: (H)): t = a * h}
noncomputable def pvs_op_3389da : sorry := by
  sorry  -- pvs2lean: definition stub for {t: T | EXISTS (h: (H)): t = a * h}

-- pvs2lean: cosets.left_coset_subset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (H: subgroup(G)), (a: (G)): subset?(a * H, G)
theorem left_coset_subset : ∀ (H : {H : T → Bool // subgroup_p H G}) (a : T), subset_p (a * H) G := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.right_coset_subset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (H: subgroup(G)), (a: (G)): subset?(H * a, G)
theorem right_coset_subset : ∀ (H : {H : T → Bool // subgroup_p H G}) (a : T), subset_p (H * a) G := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.left_coset_one
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: one * S = S
theorem left_coset_one : one * S = S := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cosets.right_coset_one
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: S * one = S
theorem right_coset_one : S * one = S := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cosets.left_coset_assoc
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: a * (b * S) = (a * b) * S
theorem left_coset_assoc : a * (b * S) = (a * b) * S := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cosets.right_coset_assoc
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (S * a) * b = S * (a * b)
theorem right_coset_assoc : (S * a) * b = S * (a * b) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cosets.lr_coset_assoc
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: (a * S) * b = a * (S * b)
theorem lr_coset_assoc : (a * S) * b = a * (S * b) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: cosets.subset_left_coset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subset?(S, R) IMPLIES subset?(a * S, a * R)
theorem subset_left_coset : subset_p S R → subset_p (a * S) (a * R) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.subset_right_coset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subset?(S, R) IMPLIES subset?(S * a, R * a)
theorem subset_right_coset : subset_p S R → subset_p (S * a) (R * a) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.right_coset
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: H * a
axiom right_coset {pvs_τ31 : Type*} {pvs_τ32 : Type*} {pvs_τ33 : Type*} : pvs_τ31 → pvs_τ32 → pvs_τ33 → Prop

-- pvs2lean: cosets.right_coset_image
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES
--  right_coset(G, H)(a) =
--   image((LAMBDA (h: (H)): h * a), (restrict[T, (H), bool]((H))))
theorem right_coset_image : subgroup_p H G ∧ member a G → right_coset G H(a) =
 image ((fun (h : (H))=> h * a)) ((restrict (H))) := by
  -- === TCCs for right_coset_image ===
  -- TCC: right_coset_image_TCC1
  -- Statement: FORALL (G, H: group[T, *, one], a: T):
  --   member(a, G) AND subgroup?(H, G) IMPLIES G(a)
  have right_coset_image_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.right_coset_is
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES
--  right_coset(G, H)(a) = {x: T | congruent_mod(G, H)(a, x)}
theorem right_coset_is : subgroup_p H G ∧ member a G → right_coset G H(a) = {x: T | congruent_mod G H(a, x)} := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.right_coset_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES right_coset(G, H)(a) = H * a
theorem right_coset_def : subgroup_p H G ∧ member a G → right_coset G H(a) = H * a := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.nonempty_right_coset
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES nonempty?(right_coset(G, H)(a))
theorem nonempty_right_coset : subgroup_p H G ∧ member a G → nonempty_p (right_coset G H(a)) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.right_coset_correspondence
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (A, B: set[T]):
--        subgroup?(H, G) AND member(a, G) AND member(b, G)
--    AND (A = right_coset(G, H)(a)) AND (B = right_coset(G, H)(b))
--    IMPLIES EXISTS (f: [(A) -> (B)]): bijective?(f)
theorem right_coset_correspondence : ∀ (A : T → Bool) (B : T → Bool), subgroup_p H G ∧ member a G ∧ member b G
 ∧ (A = right_coset G H(a)) ∧ (B = right_coset G H(b)) → ∃ (f: [(A): bijective_p f := by
  -- === TCCs for right_coset_correspondence ===
  -- TCC: right_coset_correspondence_TCC1
  -- Statement: FORALL (G, H: group[T, *, one], a, b: T, A: set[T]):
  --   subgroup?(H, G) AND
  --    member(a, G) AND member(b, G) AND A = right_coset(G, H)(a)
  --    IMPLIES G(b)
  have right_coset_correspondence_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.left_coset
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: a * H
axiom left_coset {pvs_τ18 : Type*} {pvs_τ19 : Type*} {pvs_τ20 : Type*} : pvs_τ18 → pvs_τ19 → pvs_τ20 → Prop

-- pvs2lean: cosets.left_coset_image
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES
--  left_coset(G, H)(a) =
--   image((LAMBDA (h: (H)): a * h), (restrict[T, (H), bool]((H))))
theorem left_coset_image : subgroup_p H G ∧ member a G → left_coset G H(a) =
 image ((fun (h : (H))=> a * h)) ((restrict (H))) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.left_coset_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND member(a, G) IMPLIES left_coset(G, H)(a) = a * H
theorem left_coset_def : subgroup_p H G ∧ member a G → left_coset G H(a) = a * H := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.lc_gen
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: choose({a: T | G(a) AND lc = a * H})
axiom lc_gen {pvs_τ15 : Type*} {pvs_τ16 : Type*} {pvs_τ17 : Type*} : pvs_τ15 → pvs_τ16 → pvs_τ17 → Prop

-- pvs2lean: cosets.lc_gen_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND G(a) IMPLIES lc_gen(G, H, a * H) * H = a * H
theorem lc_gen_def : subgroup_p H G ∧ G a → lc_gen G H (a * H) * H = a * H := by
  -- === TCCs for lc_gen_def ===
  -- TCC: lc_gen_def_TCC1
  -- Statement: FORALL (G, H: group[T, *, one], a: T):
  --   G(a) AND subgroup?(H, G) IMPLIES EXISTS (a_1: (G)): a * H = a_1 * H
  have lc_gen_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.rc_gen
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: choose({a: T | G(a) AND rc = H * a})
axiom rc_gen {pvs_τ27 : Type*} {pvs_τ28 : Type*} {pvs_τ29 : Type*} {pvs_τ30 : Type*} : pvs_τ27 → pvs_τ28 → pvs_τ29 → pvs_τ30

-- pvs2lean: cosets.rc_gen_def
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND G(a) IMPLIES H * rc_gen(G, H, H * a) = H * a
theorem rc_gen_def : subgroup_p H G ∧ G a → H * rc_gen G H (H * a) = H * a := by
  -- === TCCs for rc_gen_def ===
  -- TCC: rc_gen_def_TCC1
  -- Statement: FORALL (G, H: group[T, *, one], a: T):
  --   G(a) AND subgroup?(H, G) IMPLIES EXISTS (a_1: (G)): H * a = H * a_1
  have rc_gen_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.lc_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND a * H = b * H IMPLIES (EXISTS (h: (H)): a = b * h)
theorem lc_eq : subgroup_p H G ∧ a * H = b * H → (∃ (h : (H)), a = b * h) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.lc_is_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND (EXISTS (h: (H)): a = b * h) IMPLIES a * H = b * H
theorem lc_is_eq : subgroup_p H G ∧ (∃ (h : (H)), a = b * h) → a * H = b * H := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.rc_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND H * a = H * b IMPLIES (EXISTS (h: (H)): a = h * b)
theorem rc_eq : subgroup_p H G ∧ H * a = H * b → (∃ (h : (H)), a = h * b) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: cosets.rc_is_eq
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: subgroup?(H, G) AND (EXISTS (h: (H)): a = h * b) IMPLIES H * a = H * b
theorem rc_is_eq : subgroup_p H G ∧ (∃ (h : (H)), a = h * b) → H * a = H * b := by
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.cosets