-- Auto-generated by pvs2lean/translator.py
-- PVS theory: polynomial_pseudo_divide
-- PVSLib library: Sturm
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: polynomial_pseudo_divide

Auto-generated stubs from PVSLib theory `polynomial_pseudo_divide`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.polynomial_pseudo_divide

noncomputable section

variable {pvs_τ17 : Type*} {pvs_τ18 : Type*} {pvs_τ19 : Type*} (array2list : pvs_τ17 → pvs_τ18 → pvs_τ19)
variable {pvs_τ20 : Type*} {pvs_τ21 : Type*} {pvs_τ22 : Type*} (cons : pvs_τ20 → pvs_τ21 → pvs_τ22)
variable {pvs_τ23 : Type*} {pvs_τ24 : Type*} {pvs_τ25 : Type*} (descalarize_list : pvs_τ23 → pvs_τ24 → pvs_τ25)
variable {pvs_τ26 : Type*} {pvs_τ27 : Type*} (divides : pvs_τ26 → pvs_τ27 → Prop)
variable {pvs_τ28 : Type*} (length : pvs_τ28 → Prop)
variable {pvs_τ33 : Type*} {pvs_τ34 : Type*} (max : pvs_τ33 → pvs_τ34 → Prop)
variable {pvs_τ35 : Type*} {pvs_τ36 : Type*} (mod : pvs_τ35 → pvs_τ36 → Prop)
variable {pvs_τ37 : Type*} {pvs_τ38 : Type*} (nonzero_version : pvs_τ37 → pvs_τ38)
variable {pvs_τ39 : Type*} {pvs_τ40 : Type*} (nth : pvs_τ39 → pvs_τ40 → Prop)
variable {pvs_τ41 : Type*} {pvs_τ42 : Type*} {pvs_τ43 : Type*} {pvs_τ44 : Type*} {pvs_τ45 : Type*} (poly_divide : pvs_τ41 → pvs_τ42 → pvs_τ43 → pvs_τ44 → pvs_τ45 → Prop)
variable {pvs_τ46 : Type*} {pvs_τ47 : Type*} {pvs_τ48 : Type*} (polynomial : pvs_τ46 → pvs_τ47 → pvs_τ48)
variable {pvs_τ49 : Type*} {pvs_τ50 : Type*} (primitize_list : pvs_τ49 → pvs_τ50)
variable {pvs_τ56 : Type*} {pvs_τ57 : Type*} (rem : pvs_τ56 → pvs_τ57)
variable {pvs_τ58 : Type*} (thispoly : pvs_τ58 → Prop)

-- pvs2lean: polynomial_pseudo_divide.make_divlisttype
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (# quotl := qul, qdegl := n, reml := rml, rdegl := m #)
axiom make_divlisttype {pvs_τ29 : Type*} {pvs_τ30 : Type*} {pvs_τ31 : Type*} {pvs_τ32 : Type*} : pvs_τ29 → pvs_τ30 → pvs_τ31 → pvs_τ32 → Prop

-- pvs2lean: polynomial_pseudo_divide.pseudo_div
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF m > n OR i > n - m
--   THEN make_divlisttype((: :), 0, array2list(n + 1)(g), n)
-- ELSIF m = 0 THEN make_divlisttype(array2list(n + 1)(g), n, (: :), 0)
-- ELSE LET ldt =
--            IF i = n - m
--            
axiom pseudo_div {pvs_τ51 : Type*} {pvs_τ52 : Type*} {pvs_τ53 : Type*} {pvs_τ54 : Type*} {pvs_τ55 : Type*} : pvs_τ51 → pvs_τ52 → pvs_τ53 → pvs_τ54 → pvs_τ55 → Prop

-- pvs2lean: polynomial_pseudo_divide.pseudo_div_lengths
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 IMPLIES
--  LET psd = pseudo_div(g, n)(h, m)(i),
--      pd = poly_divide(g, n)(h, m)(i),
--      qlength = length(psd`quotl),
--      rlength = length(psd`reml)
--    IN
--    psd`qdegl = pd`qdeg AND
--     psd
theorem pseudo_div_lengths : h m ≠ 0 → (let psd := pseudo_div g n(h, m) (i); let pd := poly_divide g n(h, m) (i); let qlength := List.length psd.quotl; let rlength := List.length psd.reml; psd.qdegl = pd.qdeg ∧
   psd.rdegl = pd.rdeg ∧
    psd.rdegl = max (rlength - 1) 0 ∧
     qlength =
      (if i > n - m then 0
       ELSIF m = 0 then n - m + 1
       else n - m - i + 1
       )) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.Ka
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Ka : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Kn
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Kn : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Km
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Km : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Ki
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Ki : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Ca
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Ca : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Cn
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Cn : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Cm
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Cm : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.Ci
-- pvs_status: definition  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: NIL
noncomputable def Ci : sorry := by
  sorry  -- pvs2lean: definition stub for NIL

-- pvs2lean: polynomial_pseudo_divide.GG
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i > n - m THEN 0
-- ELSIF m = 0 OR i = n - m OR k < i THEN 1
-- ELSE (1 + (n - m - k))
-- ENDIF
axiom GG {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} {pvs_τ4 : Type*} {pvs_τ5 : Type*} {pvs_τ6 : Type*} : pvs_τ1 → pvs_τ2 → pvs_τ3 → pvs_τ4 → pvs_τ5 → pvs_τ6 → Prop

-- pvs2lean: polynomial_pseudo_divide.HH
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: IF i > n - m THEN 0
-- ELSIF m = 0 OR i = n - m OR k >= i + m THEN 1
-- ELSE 1 + (n - m - i)
-- ENDIF
axiom HH {pvs_τ7 : Type*} {pvs_τ8 : Type*} {pvs_τ9 : Type*} {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} : pvs_τ7 → pvs_τ8 → pvs_τ9 → pvs_τ10 → pvs_τ11 → pvs_τ12 → Prop

-- pvs2lean: polynomial_pseudo_divide.HHGGLEM
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (k: nat):
--   (k <= n - m AND i <= n - m) IMPLIES
--    (GG(k, n, 0, i, R, T) = 1 AND
--           (n - m >= 0 IMPLIES GG(k, n, m, n - m, R, T) = 1)
--       AND (k <= n - m AND k > i IMPLIES
--             
theorem HHGGLEM : ∀ (k : {i : ℝ // i ≥ 0}), (k ≤ n - m ∧ i ≤ n - m) → (GG k n 0 i R T = 1 ∧
       (n - m ≥ 0 → GG k n m (n - m) R T = 1)
   ∧ (k ≤ n - m ∧ k > i →
         GG k n m (1 + i) R T = GG k n m i R T)
   ∧ (HH k n 0 i R T = 1)
   ∧ (n - m ≥ 0 → HH k n m (n - m) R T = 1)
   ∧ (m ≠ 0 →
         HH (i + m) n m (1 + i) R T + 1 = GG i n m i R T)
   ∧ (m ≠ 0 ∧ k < i →
         HH k n m i R T = HH k n m (1 + i) R T + 1)
   ∧ (m ≠ 0 ∧ k ≥ i ∧ k < i + m →
         (HH k n m i R T = HH k n m (1 + i) R T + 1 ∧
           HH (i + m) n m (1 + i) R T + 1 = HH k n m i R T ∧
            HH (i + m) n m (1 + i) R T = HH k n m (1 + i) R T))) := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.pseudo_div_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 AND
--  (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND
--   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0)
--  IMPLIES
--  LET psd = pseudo_div(g, n)(h, m)(i),
--      pd = poly_divide(g, n)(h, m)(i),
--     
theorem pseudo_div_def : h m ≠ 0 ∧
 (∀ (ii : ℕ), ii > n → g ii = 0) ∧
  (∀ (ii : ℕ), ii > m → h ii = 0) → (let psd := pseudo_div g n(h, m) (i); let pd := poly_divide g n(h, m) (i); let qlength := List.length psd.quotl; let rlength := List.length psd.reml; pd.quot =
   (fun (k : ℕ)=> (1 / h m) ^ GG k n m i R T) *
    (fun (k : ℕ)=> if k ≤ pd.qdeg ∧ k ≥ pd.qdeg - qlength + 1
         then nth psd.quotl (k - (pd.qdeg - qlength + 1))
       else 0
       )
   ∧
   pd.rem =
    (fun (k : ℕ)=> (1 / h m) ^ HH k n m i R T) *
     (fun (k : ℕ)=> if k ≤ pd.rdeg ∧ (i > n - m ∨ m > 0) then nth psd.reml k
        else 0
        )) := by
  -- === TCCs for pseudo_div_def ===
  -- TCC: pseudo_div_def_TCC1
  -- Statement: FORALL (g, h: [nat -> int], i, m, n: nat):
  --   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0) AND
  --    (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND h(m) /= 0
  --    IMPLIES
  --    FORALL (psd:
  --              {...
  have pseudo_div_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  -- TCC: pseudo_div_def_TCC2
  -- Statement: FORALL (R, T: nat, g, h: [nat -> int], i, m, n: nat):
  --   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0) AND
  --    (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND h(m) /= 0
  --    IMPLIES
  --    FORALL (psd:
  --    ...
  have pseudo_div_def_tcc2 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.poly_pseudo_remainder_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 AND
--  n >= m AND
--   (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND
--    (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0)
--  IMPLIES
--  LET psd = pseudo_div(g, n)(h, m)(0),
--      pd = poly_divide(g, n)(
theorem poly_pseudo_remainder_def : h m ≠ 0 ∧
 n ≥ m ∧
  (∀ (ii : ℕ), ii > n → g ii = 0) ∧
   (∀ (ii : ℕ), ii > m → h ii = 0) → (let psd := pseudo_div g n(h, m) (0); let pd := poly_divide g n(h, m) (0); let qlength := List.length psd.quotl; let rlength := List.length psd.reml; pd.rem =
   (1 / h m) ^ (n - m + 1) *
    (fun (k : ℕ)=> if k ≤ psd.rdegl ∧ m > 0 then nth psd.reml k else 0 )) := by
  -- === TCCs for poly_pseudo_remainder_def ===
  -- TCC: poly_pseudo_remainder_def_TCC1
  -- Statement: FORALL (g, h: [nat -> int], m, n: nat):
  --   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0) AND
  --    (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND n >= m AND h(m) /= 0
  --    IMPLIES
  --    FORALL (psd:
  --       ...
  have poly_pseudo_remainder_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder
-- pvs_status: definition  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET ppd = pseudo_div(g, n)(h, m)(0),
--     thisrem = ppd`reml,
--     pseudosign: nzint =
--       IF h(m) > 0 OR mod(n - m + 1, 2) = 0 OR m > n THEN 1 ELSE -1 ENDIF
--   IN descalarize_list(nonzero_version(prim
axiom adjusted_remainder {pvs_τ13 : Type*} {pvs_τ14 : Type*} {pvs_τ15 : Type*} {pvs_τ16 : Type*} : pvs_τ13 → pvs_τ14 → pvs_τ15 → pvs_τ16 → Prop

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder_def
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 AND
--  (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND
--   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0)
--  IMPLIES
--  LET thisrem = adjusted_remainder(g, n)(h, m),
--      pd = poly_divide(g, n)(h, m)
theorem adjusted_remainder_def : h m ≠ 0 ∧
 (∀ (ii : ℕ), ii > n → g ii = 0) ∧
  (∀ (ii : ℕ), ii > m → h ii = 0) → (let thisrem := adjusted_remainder g n(h, m); let pd := poly_divide g n(h, m) (0); let thisdeg := List.length thisrem - 1; let thispoly := (fun (i : ℕ)=> if i ≤ thisdeg then nth thisrem i else 0 ); thisdeg ≥ 0 →
   ((∃ (cp : {x : ℝ // 0 < x}), polynomial thispoly thisdeg = polynomial (-cp * pd.rem) pd.rdeg)
     ∧ thispoly thisdeg ≠ 0)) := by
  -- === TCCs for adjusted_remainder_def ===
  -- TCC: adjusted_remainder_def_TCC1
  -- Statement: FORALL (g, h: [nat -> int], m, n: nat):
  --   (FORALL (ii: nat): ii > m IMPLIES h(ii) = 0) AND
  --    (FORALL (ii: nat): ii > n IMPLIES g(ii) = 0) AND h(m) /= 0
  --    IMPLIES
  --    FORALL (thisrem: list[int], pd...
  have adjusted_remainder_def_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder_length
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 IMPLIES LET pr = adjusted_remainder(g, n)(h, m) IN length(pr) <= m
theorem adjusted_remainder_length : h m ≠ 0 → (let pr := adjusted_remainder g n(h, m); List.length pr ≤ m) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder_length2
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: h(m) /= 0 IMPLIES
--  LET pr = adjusted_remainder(g, n)(h, m) IN length(pr) <= n + 1
theorem adjusted_remainder_length2 : h m ≠ 0 → (let pr := adjusted_remainder g n(h, m); List.length pr ≤ n + 1) := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder_empty
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: (FORALL (i: nat): i > n IMPLIES g(i) = 0) AND
--  (FORALL (i: nat): i > m IMPLIES h(i) = 0) AND
--   h(m) /= 0 AND length(adjusted_remainder(g, n)(h, m)) = 0
--  IMPLIES
--  FORALL (j: nat):
--    j <= poly_divide(g
theorem adjusted_remainder_empty : (∀ (i : ℕ), i > n → g i = 0) ∧
 (∀ (i : ℕ), i > m → h i = 0) ∧
  h m ≠ 0 ∧ List.length (adjusted_remainder g n(h, m)) = 0 → ∀ (j : ℕ), j ≤ poly_divide g n(h, m) (0).rdeg →
   poly_divide g n(h, m) (0).rem j = 0 := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: polynomial_pseudo_divide.adjusted_remainder_test
-- pvs_status: unproved  lean_tactic_class: arithmetic_norm_num
-- stmt_confidence: high  [ast]
-- pvs_stmt: LET g =
--       (LAMBDA (i: nat):
--          IF i = 0 THEN 1
--          ELSIF i = 1 THEN 2
--          ELSIF i = 2 THEN 2
--          ELSIF i = 3 THEN 5
--          ELSIF i = 5 THEN 2
--          ELSIF i = 6 THEN -7
--   
theorem adjusted_remainder_test : fun (g : {i : ℝ // i ≥ 0} → ℝ) => fun (h : {i : ℝ // i ≥ 0} → ℝ) => adjusted_remainder g 6(h, 4) = (: -740, -996, -10, 887 :) (fun (i : {i : ℝ // i ≥ 0}) => IF (i = 0) -4 (if i = 1 then -4
 ELSIF i = 2 then 2
 ELSIF i = 3 then 5
 ELSIF i = 4 then -2
 else 0)) (fun (i : {i : ℝ // i ≥ 0}) => IF (i = 0) 1 (if i = 1 then 2
 ELSIF i = 2 then 2
 ELSIF i = 3 then 5
 ELSIF i = 5 then 2
 ELSIF i = 6 then -7
 else 0)) := by
  -- === TCCs for adjusted_remainder_test ===
  -- TCC: adjusted_remainder_test_TCC1
  -- Statement: FORALL (g: [nat -> int], h: [nat -> int]):
  --   g =
  --    (LAMBDA (i: nat):
  --       IF i = 0 THEN 1
  --       ELSIF i = 1 THEN 2
  --       ELSIF i = 2 THEN 2
  --       ELSIF i = 3 THEN 5
  --       ELSIF i = 5 THEN 2
  --      ...
  have adjusted_remainder_test_tcc1 : True := by
    trivial  -- pvs2lean tcc_discharge: replace with norm_num/decide if needed
  sorry  -- phase2_medium: type translated, proof pending

end

end NavierStokesClean.PVSLib.polynomial_pseudo_divide