-- Auto-generated by pvs2lean/translator.py
-- PVS theory: interval_props
-- PVSLib library: interval_arith
-- DO NOT EDIT manually; re-run the pvs2lean pipeline to regenerate.

import Mathlib

/-!
# PVSLib → Lean4: interval_props

Auto-generated stubs from PVSLib theory `interval_props`.
Phase-2: real Lean4 type signatures (translated from PVS statements).
Run `lake build` to find which stubs the automated tactics close.
-/

-- Stubs: allow auto-implicit to handle undeclared PVS type names
set_option autoImplicit true

namespace NavierStokesClean.PVSLib.interval_props

noncomputable section

variable {pvs_τ1 : Type*} {pvs_τ2 : Type*} {pvs_τ3 : Type*} (Div : pvs_τ1 → pvs_τ2 → pvs_τ3)
variable {pvs_τ4 : Type*} {pvs_τ5 : Type*} (Gt : pvs_τ4 → pvs_τ5 → Prop)
variable {pvs_τ6 : Type*} {pvs_τ7 : Type*} (Lt : pvs_τ6 → pvs_τ7 → Prop)
variable {pvs_τ8 : Type*} (NonNeg_p : pvs_τ8 → Prop)
variable {pvs_τ9 : Type*} (Pos_p : pvs_τ9 → Prop)
variable {pvs_τ10 : Type*} {pvs_τ11 : Type*} {pvs_τ12 : Type*} (Sub : pvs_τ10 → pvs_τ11 → pvs_τ12)

-- pvs2lean: interval_props.gt_weak_cancelation_sub
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: Gt(Sub(pX, pY), 0) IFF gt(pX, pY)
theorem gt_weak_cancelation_sub : Gt (Sub pX pY) 0 ↔ gt pX pY := by
  sorry  -- phase2_high: type translated, proof pending

-- pvs2lean: interval_props.gt_weak_cancelation_div
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (pX: ProperInterval, ppY: ProperInterval | Pos?(ppY)):
--   Gt(Div(pX, ppY), 1) IFF gt(pX, ppY)
theorem gt_weak_cancelation_div : ∀ (pX : ℝ × ℝ) (ppY : {ppY : ℝ × ℝ // Pos_p ppY}), Gt (Div pX ppY) 1 ↔ gt pX ppY := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: interval_props.lt_weak_cancelation_div
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: FORALL (ppX: ProperInterval | Pos?(ppX),
--         nnpY: ProperInterval | NonNeg?(nnpY)):
--   Lt(Div(nnpY, ppX), 1) IFF lt(nnpY, ppX)
theorem lt_weak_cancelation_div : ∀ (ppX : {ppX : ℝ × ℝ // Pos_p ppX}) (nnpY : {nnpY : ℝ × ℝ // NonNeg_p nnpY}), Lt (Div nnpY ppX) 1 ↔ lt nnpY ppX := by
  sorry  -- phase2_medium: type translated, proof pending

-- pvs2lean: interval_props.both_sides_1minus_lt1
-- pvs_status: unproved  lean_tactic_class: needs_human
-- stmt_confidence: high  [ast]
-- pvs_stmt: Lt(X, 1) IFF Gt(Sub([|1|], X), 0)
theorem both_sides_1minus_lt1 : Lt X 1 ↔ Gt (Sub [|1|] X) 0 := by
  sorry  -- phase2_high: type translated, proof pending

end

end NavierStokesClean.PVSLib.interval_props